### ISSUE TITLE
Web版的软解demo不生效

### ISSUE THREAD

**Issue by lastnigtic** [Tencent/libpag#1318]
https://github.com/libpag/pag-web/blob/main/pages/software-decoder.html

这个例子运行之后会报错
![image](https://github.com/Tencent/libpag/assets/17680884/b71546e7-7ddf-4164-b264-4fead73cf337)

## 【版本信息】

4.2.88

## 【平台信息】

Web 浏览器

**Comment by zhalice2011** [comment]
你好,  我在线查看该demo是正常运行的啊  https://pagtest.zhalice.com/pages/software-decoder.html

<img width="1264" alt="image" src="https://github.com/Tencent/libpag/assets/24289349/b36f1608-6862-49e7-9e22-c339c3370e54">

**Comment by domchen** [comment]
软解就是更卡的，有这个提醒是软解生效了，提示没有多线程支持这个是正常的，忽略就行。
