### ISSUE TITLE
业务层显存泄漏 ---- E/libEGL: call to OpenGL ES API with no current context (logged once per thread)

### ISSUE THREAD

**Issue by XJiong** [Tencent/libpag#144]
### Bug 描述
<img width="826" alt="image" src="https://user-images.githubusercontent.com/14952406/156339322-8c68299a-52a9-4d6c-b3cf-80d1f635b3ef.png">

#### 问题
业务层调用pag渲染环节出现显存泄漏，并偶现黑屏，日志如上所示。

#### 环境
libpag 版本：-android（v3.3.0.166）

**Comment by XJiong** [comment]
原因：资源释放顺序问题；
业务层GLSurfaceView 先释放了，后续在进行释放pag资源的时候，已经没有glContext了，所以产生了显存泄漏。
具体顺序如下图所示：
<img width="571" alt="image" src="https://user-images.githubusercontent.com/14952406/156345699-e0c70d36-0ade-472f-93ca-b3a5d23275ba.png">

**Comment by domchen** [comment]
没有GLContext的时候，关联的GPU资源就已经都释放了。这个就是OpenGL的内存管理机制。
