### ISSUE TITLE
Caused by java.lang.ClassNotFoundException Didn't find class "android.hardware.HardwareBuffer" 

### ISSUE THREAD

**Issue by peter100u** [Tencent/libpag#1569]
## 【版本信息】

4.2.100

## 【平台信息】

Android 原生 ， 海外googleplay市场

## 【预期的表现】
不闪退

## 【实际的情况】
更新到4.2.100,线上出现大量crash, 无法必现

## 【Demo及附件】
Caused by java.lang.ClassNotFoundException: Didn't find class "android.hardware.HardwareBuffer" on path: DexPathList[[zip file "/data/app/com.ohla.socialapps-1/base.apk", zip file "/data/app/com.ohla.socialapps-1/split_config.armeabi_v7a.apk", zip file "/data/app/com.ohla.socialapps-1/split_config.mdpi.apk"],nativeLibraryDirectories=[/data/app/com.ohla.socialapps-1/lib/arm, /data/app/com.ohla.socialapps-1/base.apk!/lib/armeabi-v7a, /data/app/com.ohla.socialapps-1/split_config.armeabi_v7a.apk!/lib/armeabi-v7a, /data/app/com.ohla.socialapps-1/split_config.mdpi.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
       at org.libpag.PAGImageView.a(SourceFile:36)
       at org.libpag.PAGImageView.flush(SourceFile:8)
       at org.libpag.PAGImageView.onAnimationUpdate(SourceFile:4)
       at org.libpag.PAGAnimator.onAnimationUpdate(SourceFile:2)

**Comment by h3r3x3** [comment]
具体是哪些手机会报错？ 系统是什么版本？ 可以发一些上来，我们复测下

**Comment by peter100u** [comment]
![image](https://github.com/Tencent/libpag/assets/14010579/8c18f2b4-834a-4926-a47e-94bc155b081d)

**Comment by h3r3x3** [comment]
我用demo复测了一些7.0的机型，并不会crash，另外7.0的版本并不会开启HardwareBuffer。另外我也下载了你们的ohla，大概点了一会，在7.0上也没有crash。

**Comment by peter100u** [comment]
> 
嗯，我们也在看，之前没出现过的闪退，升级后出现

**Comment by peter100u** [comment]
还是无法重现，实在不行，就降级看看

**Comment by h3r3x3** [comment]
最好能找到一个crash的设备，然后模拟从老版本升级到新版本，然后看下crash具体在操作什么的时候出现的，整体还原下用户的操作，如果有必现的路径就好分析了

**Comment by peter100u** [comment]
> 最好能找到一个crash的设备，然后模拟从老版本升级到新版本，然后看下crash具体在操作什么的时候出现的，整体还原下用户的操作，如果有必现的路径就好分析了

已经降到'com.tencent.tav:libpag:4.2.92' 已经没有闪退了, 但是4.3.3这个问题还是存在，很难重现

**Comment by spardas** [comment]
我这里有台设备稳定复现
<img width="1259" alt="image" src="https://github.com/Tencent/libpag/assets/8586281/c951d4c0-615d-4060-8bcd-123d0d0560ba">

**Comment by peter100u** [comment]
> 

可以啊，老哥，具体机型发出来，方便他们查问题

**Comment by spardas** [comment]
![image](https://github.com/Tencent/libpag/assets/8586281/7928eae8-63d6-40f0-8566-91a2bbdc25dc)

**Comment by h3r3x3** [comment]
> 

在官方的demo里面可以复测吗？ 还是要有特定的流程调用，我这边没有这台测试机。 可以在官方demo测试，然后抓一下全量的log吗

**Comment by h3r3x3** [comment]
在4.3版本查到了原因，4.2是没问题了的，4.3.8 已经修复了这个问题。
