### ISSUE TITLE
iOS 偶现崩溃 pag::VideoSequence::getVideoHeight()

### ISSUE THREAD

**Issue by WELONG** [Tencent/libpag#1570]
## 【版本信息】

4.2.88

## 【平台信息】

 iOS 原生

## 【实际的情况】
bulgy 崩溃记录
![img_v2_9fe4421c-b24f-4f70-9722-84de49fc5a6g](https://github.com/Tencent/libpag/assets/16712584/9198c396-e803-49f6-afac-cc11be87c19c)

![img_v2_e8bb6a1b-e4f9-45a7-a102-33c8c877e5fg](https://github.com/Tencent/libpag/assets/16712584/b9d18894-3f73-4ec0-a4d5-92fa2dd1df8d)

![img_v2_f2eef700-8b89-4524-a4cc-183d6cd0a49g](https://github.com/Tencent/libpag/assets/16712584/a815dbc0-1349-4309-bad8-ca774d563e35)

**Comment by peter100u** [comment]
我们也遇到了，但是无法重现

**Comment by yxdyxd** [comment]
+1，无法复现，也不知道怎么问题出在哪里

**Comment by yxdyxd** [comment]
有解决的办法吗？升级最新的版本可以解决吗？

**Comment by peter100u** [comment]
> 
最新版本也没有解决

**Comment by yxdyxd** [comment]
> > 
> 
> 最新版本也没有解决

好吧，那我再找找其他的解决办法吧

**Comment by Alienchang** [comment]
我出现同样问题了，经过和设计一番追查发现，pag文件支持封装视频和序列帧两种动画，当大量初始化序列帧的pag文件时就会出现这个问题，使用视频的pag文件就没有问题

**Comment by swiftZhou** [comment]
4.3.18版本也遇到同样的问题

**Comment by domchen** [comment]
这个堆栈里从StrokeStyle到ImageBytes再到VideoSequence三个函数在代码里是完全不存在调用关系的，应该不是一个真实的堆栈，比较怀疑是野指针的错误，发生错误的地方并不是堆栈指示的地方。因为还有别的一些issue报错也是指向一样的无效堆栈，不排除有可能是别的模块或者库野指针了导致访问越界，正好指向了libpag的库函数。有几个方式可以尝试一下：1.把怀疑可能带来野指针的代码模块或者其他库一个个屏蔽掉测试看看能否定位出具体引入问题的代码位置范围。2.如果在本地也可以复现，随机的也行。可以在xcode里开启Address Sanitizer选项，这样野指针的时候会挂在真正出错的地方。然后想办法制造出类似crash把堆栈再贴出来。

**Comment by WELONG** [comment]
> 这个堆栈里从StrokeStyle到ImageBytes再到VideoSequence三个函数在代码里是完全不存在调用关系的，应该不是一个真实的堆栈，比较怀疑是野指针的错误，发生错误的地方并不是堆栈指示的地方。因为还有别的一些issue报错也是指向一样的无效堆栈，不排除有可能是别的模块或者库野指针了导致访问越界，正好指向了libpag的库函数。有几个方式可以尝试一下：1.把怀疑可能带来野指针的代码模块或者其他库一个个屏蔽掉测试看看能否定位出具体引入问题的代码位置范围。2.如果在本地也可以复现，随机的也行。可以在xcode里开启Address Sanitizer选项，这样野指针的时候会挂在真正出错的地方。然后想办法制造出类似crash把堆栈再贴出来。 ![image](https://user-images.githubusercontent.com/6849001/267014291-21f50e39-82e5-4fca-8b7c-6ae16b05d4c1.png)

可能是这个原因，我们前段时间排查了一些内存泄漏问题，目前线上已经没有报这个了

**Comment by duxinfeng** [comment]
我们用的v4.3.3 版本，使用 Firebase 统计的也有这个问题，更新版本前用的v4.1.49 没有这个问题
![WX20231201-102546@2x](https://github.com/Tencent/libpag/assets/8338102/814330c2-c0ce-4088-87c9-1d370a07959e)

**Comment by domchen** [comment]
还有个实际出现过的情况参考，只发生在安卓端，如果做了so动态下发的话，升级过程出险的crash，会导致旧版本库的日志上报到新版本分类下，从而导致用错符号表。建议可以把最近几个版本的符号表都尝试还原一下，看看哪个堆栈是对的。楼上的堆栈可以确认是错的。代码里没有这个调用关系。

**Comment by domchen** [comment]
最新的4.3.43修复了iOS上隐藏比较久的crash问题，建议大家升级一下。这个issue先关闭，如果还有出现问题可以还原一下有效的堆栈信息重新重新提问。
