### ISSUE TITLE
 org.libpag.PAGPlayer.finalize() timed out after 10 seconds

### ISSUE THREAD

**Issue by sansan-cc** [Tencent/libpag#1581]
## 【版本信息】

4.1.49

## 【平台信息】

Android 原生

## 【实际的情况】
出现在 bugly 上的一个问题，我记得以前这个问题论坛上提过说已经解决了，但是现在又出现了

<html>
<body>

16407-20 15:37:53.529 5291 5304 E AndroidRuntime: java.util.concurrent.TimeoutException: org.libpag.PAGPlayer.finalize() timed out after 10 seconds
--
16507-20 15:37:53.529 5291 5304 E AndroidRuntime: at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:260)
16607-20 15:37:53.529 5291 5304 E AndroidRuntime: at java.lang.Daemons$Daemon.run(Daemons.java:139)
16707-20 15:37:53.529 5291 5304 E AndroidRuntime: at java.lang.Thread.run(Thread.java:930)
16807-20 15:37:53.594 13652 13652 E m.lmf.xidi:cor: Not starting debugger since process cannot load the jdwp agent.

</body>
</html>

**Comment by kevingpqi123** [comment]
这类问题需要有具体的复现场景才好分析，Android 平台碎片化比较严重，且中低端机型较多，仅仅靠描述难以定位问题
PAG  的渲染接口内部都是添加的有锁的，只有 flush 的方法相对耗时，一种规避的方式时在销毁前提前调用 PAGView 的 stop 方法先停止播放

**Comment by domchen** [comment]
长时间进一步信息反馈先关闭，有新的附加信息可重新开启。
