### ISSUE TITLE
偶现crash

### ISSUE THREAD

**Issue by zengke328** [Tencent/libpag#1617]
## 【版本信息】

4.2.100 

## 【平台信息】

Android 原生    vivo 2120 (V2120)  Android 11 (SDK 30)

## 【预期的表现】

无crash

## 【实际的情况】

#00  pc 0x000000000010f0cc  /vendor/lib/egl/libGLESv2_mtk.so
  #01  pc 0x000000000004ef59  /vendor/lib/egl/libGLESv2_mtk.so
  #02  pc 0x00000000000c0e27  /vendor/lib/egl/libGLESv2_mtk.so
  #03  pc 0x0000000000085f0d  /vendor/lib/egl/libGLESv2_mtk.so
  #04  pc 0x00000000000864a5  /vendor/lib/egl/libGLESv2_mtk.so (glClear+476)
  #05  pc 0x00000000000cec83  /data/app/~~1gWIsValOa8gZaWBWZ_Wsg==/com.hkfuliao.chamet-U9gBjcSql5Ds7KA491-wNw==/lib/arm/libpag.so
  #06  pc 0x00000000000bc9bd  /data/app/~~1gWIsValOa8gZaWBWZ_Wsg==/com.hkfuliao.chamet-U9gBjcSql5Ds7KA491-wNw==/lib/arm/libpag.so
  #07  pc 0x00000000000cedff  /data/app/~~1gWIsValOa8gZaWBWZ_Wsg==/com.hkfuliao.chamet-U9gBjcSql5Ds7KA491-wNw==/lib/arm/libpag.so
  #08  pc 0x00000000000be987  /data/app/~~1gWIsValOa8gZaWBWZ_Wsg==/com.hkfuliao.chamet-U9gBjcSql5Ds7KA491-wNw==/lib/arm/libpag.so
  #09  pc 0x00000000000dada7  /data/app/~~1gWIsValOa8gZaWBWZ_Wsg==/com.hkfuliao.chamet-U9gBjcSql5Ds7KA491-wNw==/lib/arm/libpag.so
  #10  pc 0x00000000000dae91  /data/app/~~1gWIsValOa8gZaWBWZ_Wsg==/com.hkfuliao.chamet-U9gBjcSql5Ds7KA491-wNw==/lib/arm/libpag.so
  #11  pc 0x000000000008a621  /data/app/~~1gWIsValOa8gZaWBWZ_Wsg==/com.hkfuliao.chamet-U9gBjcSql5Ds7KA491-wNw==/lib/arm/libpag.so
  #12  pc 0x000000000006fb8d  /data/app/~~1gWIsValOa8gZaWBWZ_Wsg==/com.hkfuliao.chamet-U9gBjcSql5Ds7KA491-wNw==/lib/arm/libpag.so
  #13  pc 0x000000000008a381  /data/app/~~1gWIsValOa8gZaWBWZ_Wsg==/com.hkfuliao.chamet-U9gBjcSql5Ds7KA491-wNw==/lib/arm/libpag.so
  #14  pc 0x0000000000088065  /data/app/~~1gWIsValOa8gZaWBWZ_Wsg==/com.hkfuliao.chamet-U9gBjcSql5Ds7KA491-wNw==/lib/arm/libpag.so
  #15  pc 0x00000000000883ff  /data/app/~~1gWIsValOa8gZaWBWZ_Wsg==/com.hkfuliao.chamet-U9gBjcSql5Ds7KA491-wNw==/lib/arm/libpag.so
  #16  pc 0x0000000000089071  /data/app/~~1gWIsValOa8gZaWBWZ_Wsg==/com.hkfuliao.chamet-U9gBjcSql5Ds7KA491-wNw==/lib/arm/libpag.so
  #17  pc 0x0000000000088765  /data/app/~~1gWIsValOa8gZaWBWZ_Wsg==/com.hkfuliao.chamet-U9gBjcSql5Ds7KA491-wNw==/lib/arm/libpag.so
  #18  pc 0x0000000000088065  /data/app/~~1gWIsValOa8gZaWBWZ_Wsg==/com.hkfuliao.chamet-U9gBjcSql5Ds7KA491-wNw==/lib/arm/libpag.so
  #19  pc 0x0000000000089071  /data/app/~~1gWIsValOa8gZaWBWZ_Wsg==/com.hkfuliao.chamet-U9gBjcSql5Ds7KA491-wNw==/lib/arm/libpag.so
  #20  pc 0x0000000000088765  /data/app/~~1gWIsValOa8gZaWBWZ_Wsg==/com.hkfuliao.chamet-U9gBjcSql5Ds7KA491-wNw==/lib/arm/libpag.so
  #21  pc 0x00000000000685dd  /data/app/~~1gWIsValOa8gZaWBWZ_Wsg==/com.hkfuliao.chamet-U9gBjcSql5Ds7KA491-wNw==/lib/arm/libpag.so (pag::PAGSurface::draw(pag::RenderCache*, std::__ndk1::shared_ptr<pag::Graphic>, pag::BackendSemaphore*, bool)+352)
  #22  pc 0x0000000000067627  /data/app/~~1gWIsValOa8gZaWBWZ_Wsg==/com.hkfuliao.chamet-U9gBjcSql5Ds7KA491-wNw==/lib/arm/libpag.so (pag::PAGPlayer::flushInternal(pag::BackendSemaphore*)+154)
  #23  pc 0x0000000000067569  /data/app/~~1gWIsValOa8gZaWBWZ_Wsg==/com.hkfuliao.chamet-U9gBjcSql5Ds7KA491-wNw==/lib/arm/libpag.so (pag::PAGPlayer::flush()+64)
  #24  pc 0x00000000000b384f  /data/app/~~1gWIsValOa8gZaWBWZ_Wsg==/com.hkfuliao.chamet-U9gBjcSql5Ds7KA491-wNw==/lib/arm/libpag.so (Java_org_libpag_PAGPlayer_flushAndFenceSync+114)
  #25  pc 0x00000000002a1f3d  /data/app/~~1gWIsValOa8gZaWBWZ_Wsg==/com.hkfuliao.chamet-U9gBjcSql5Ds7KA491-wNw==/oat/arm/base.odex (art_jni_trampoline+92)
  #26  pc 0x00000000009c9235  /data/app/~~1gWIsValOa8gZaWBWZ_Wsg==/com.hkfuliao.chamet-U9gBjcSql5Ds7KA491-wNw==/oat/arm/base.odex (org.libpag.PAGView.flush+500)
  #27  pc 0x000000000097af8f  /data/app/~~1gWIsValOa8gZaWBWZ_Wsg==/com.hkfuliao.chamet-U9gBjcSql5Ds7KA491-wNw==/oat/arm/base.odex (org.libpag.PAGView$g.handleMessage+702)
  #28  pc 0x000000000057aa99  /system/framework/arm/boot-framework.oat (android.os.Handler.dispatchMessage+136)
  #29  pc 0x000000000057d5d3  /system/framework/arm/boot-framework.oat (android.os.Looper.loop+1562)
  #30  pc 0x000000000057c50b  /system/framework/arm/boot-framework.oat (android.os.HandlerThread.run+538)
  #31  pc 0x00000000000d3dd5  /apex/com.android.art/lib/libart.so (art_quick_invoke_stub_internal+68)
  #32  pc 0x00000000004ec2bb  /apex/com.android.art/lib/libart.so (art_quick_invoke_stub+282)
  #33  pc 0x000000000012c12d  /apex/com.android.art/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+148)
  #34  pc 0x00000000003f9a97  /apex/com.android.art/lib/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, jvalue const*)+374)
  #35  pc 0x00000000003f9ba7  /apex/com.android.art/lib/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue const*)+42)
  #36  pc 0x000000000043acb5  /apex/com.android.art/lib/libart.so (art::Thread::CreateCallback(void*)+1056)
  #37  pc 0x00000000000ab141  /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+40)
  #38  pc 0x00000000000642af  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+30)

**Comment by kevingpqi123** [comment]
这个问题是一直问题，属于 MTK 芯片兼容性问题，暂无解决方案，如果你的项目中有使用 OpenGL 相关接口，应该也能搜索到类似的 crash 堆栈
提供一种规避方案： 如果你这边的 PAGView 不是全屏播放，且不涉及到 pag 文件中的文本编辑和占位图替换，可以切换使用 PAGImageView，PAGImageView 会将渲染结果缓存至本地，第二次加载的时候直接读取缓存数据， 可以大幅降低这类问题出现的概率。
