### ISSUE TITLE
android通过设置matrix缩放实现图片Layers实现宽高自适应出现异常位移问题

### ISSUE THREAD

**Issue by WenxiaohuaEdward** [Tencent/libpag#1621]
### Discussed in https://github.com/Tencent/libpag/discussions/1620

<div type='discussions-op-text'>

<sup>Originally posted by **WenxiaohuaEdward** July 27, 2023</sup>
PAG SDK 版本 ：com.tencent.tav:libpag:4.1.49
平台： Android 原生
预期实现效果：pag文件中imageLayers可根据实际图片的宽高来自适应
![image](https://github.com/Tencent/libpag/assets/10917249/9e402cd8-c6b8-43c0-a8be-8f8ea13e70b5)
实际效果：
![image](https://github.com/Tencent/libpag/assets/10917249/fb5d5397-3f55-42fc-afba-65e8a717e20f)
实际图片宽高是50*50， 图片Layers的宽高是48*48，通过上图代码设置matrix，Matrix{[1.0416666, 0.0, -1.0][0.0, 1.0416666, -1.0][0.0, 0.0, 1.0]}。   异常向下平移了一些位置，而我没有对matrix处理平移操作
![image](https://github.com/Tencent/libpag/assets/10917249/5664ed25-d55f-4641-bf38-8ad40aaf2ea1)
 
</div>

**Comment by kevingpqi123** [comment]
已有问题：https://github.com/Tencent/libpag/discussions/1620
