### ISSUE TITLE
Redmi k60 运行闪退(高概率)

### ISSUE THREAD

**Issue by manymore13** [Tencent/libpag#1629]
## 【版本信息】

4.3.3

## 【平台信息】

Android 原生  Redmi k60

## 测试代码
```java
boolean isFront = true;

PagImageView pagViewtext = findViewById(R.id.imageView);
pagViewtext.setPathAsync("assets://front_to_back.pag", result -> {
});
pagViewtext.setOnClickListener(v -> {
    if(isFront){
        pagViewtext.setPathAsync("assets://front_to_back.pag", result -> {
            pagViewtext.play();
        });
        isFront = false;
    }else{
        pagViewtext.setPathAsync("assets://back_to_front.pag", result -> {
            pagViewtext.play();
        });
        isFront = true;
    }
});
```

## 出错日志
Redmi/mondrian/mondrian:13/TKQ1.220905.001/V14.0.25.0.TMNCNXM:user/release-keys

      #00 pc 000000000031055c  /data/data/com.example.customdrawable/code_cache/libjvmtiagent_arm64.so
      #01 pc 0000000000311970  /data/data/com.example.customdrawable/code_cache/libjvmtiagent_arm64.so
      #02 pc 00000000000cf684  /data/data/com.example.customdrawable/code_cache/libjvmtiagent_arm64.so
      #03 pc 000000000008597c  /data/data/com.example.customdrawable/code_cache/libjvmtiagent_arm64.so
      #04 pc 000000000008a9d0  /data/data/com.example.customdrawable/code_cache/libjvmtiagent_arm64.so
      #05 pc 00000000000ffc7c  /data/app/~~VF5IOvQ1H7WHLBphotEeow==/com.example.customdrawable-rWJ5ILH8-9p7vmX0i5K8Ng==/base.apk!libpag.so (Java_org_libpag_NativeTask_Run+92) (BuildId: a0decb68b92c42991c5846dcf86c994be1a52d29)
      #06 pc 000000000021a354  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+148) (BuildId: d12e7186a25c1ddd3163f9bf5ae7c82b)
      #07 pc 0000000000209398  /apex/com.android.art/lib64/libart.so (nterp_helper+152) (BuildId: d12e7186a25c1ddd3163f9bf5ae7c82b)
      #08 pc 000000000000acae  [anon:dalvik-classes3.dex extracted in memory from /data/app/~~VF5IOvQ1H7WHLBphotEeow==/com.example.customdrawable-rWJ5ILH8-9p7vmX0i5K8Ng==/base.apk!classes3.dex] (org.libpag.PAGImageView.setPathAsync+10)
      #09 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: d12e7186a25c1ddd3163f9bf5ae7c82b)
      #10 pc 000000000000accc  [anon:dalvik-classes3.dex extracted in memory from /data/app/~~VF5IOvQ1H7WHLBphotEeow==/com.example.customdrawable-rWJ5ILH8-9p7vmX0i5K8Ng==/base.apk!classes3.dex] (org.libpag.PAGImageView.setPathAsync+4)
      #11 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: d12e7186a25c1ddd3163f9bf5ae7c82b)
      #12 pc 0000000000032e02  [anon:dalvik-classes2.dex extracted in memory from /data/app/~~VF5IOvQ1H7WHLBphotEeow==/com.example.customdrawable-rWJ5ILH8-9p7vmX0i5K8Ng==/base.apk!classes2.dex] (com.example.customdrawable.PagActivity.lambda$onCreate$6$PagActivity+22)
      #13 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: d12e7186a25c1ddd3163f9bf5ae7c82b)
      #14 pc 0000000000032b98  [anon:dalvik-classes2.dex extracted in memory from /data/app/~~VF5IOvQ1H7WHLBphotEeow==/com.example.customdrawable-rWJ5ILH8-9p7vmX0i5K8Ng==/base.apk!classes2.dex] (com.example.customdrawable.-$$Lambda$PagActivity$DIuzHz_NbXl_xbKjWkJ8JVOl8ew.onClick+8)
      #15 pc 000000000020b074  /apex/com.android.art/lib64/libart.so (nterp_helper+7540) (BuildId: d12e7186a25c1ddd3163f9bf5ae7c82b)
      #16 pc 00000000004dc816  /system/framework/framework.jar (android.view.View.performClick+34)
      #17 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: d12e7186a25c1ddd3163f9bf5ae7c82b)
      #18 pc 00000000004dc84a  /system/framework/framework.jar (android.view.View.performClickInternal+6)
      #19 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: d12e7186a25c1ddd3163f9bf5ae7c82b)
      #20 pc 00000000004d7948  /system/framework/framework.jar (android.view.View.-$$Nest$mperformClickInternal+0)
      #21 pc 0000000000209334  /apex/com.android.art/lib64/libart.so (nterp_helper+52) (BuildId: d12e7186a25c1ddd3163f9bf5ae7c82b)
      #22 pc 00000000004b1500  /system/framework/framework.jar (android.view.View$PerformClick.run+16)
      #23 pc 000000000020b074  /apex/com.android.art/lib64/libart.so (nterp_helper+7540) (BuildId: d12e7186a25c1ddd3163f9bf5ae7c82b)
      #24 pc 00000000001c7e60  /system/framework/framework.jar (android.os.Handler.handleCallback+4)
      #25 pc 0000000000209334  /apex/com.android.art/lib64/libart.so (nterp_helper+52) (BuildId: d12e7186a25c1ddd3163f9bf5ae7c82b)
      #26 pc 00000000001c7cac  /system/framework/framework.jar (android.os.Handler.dispatchMessage+8)
      #27 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: d12e7186a25c1ddd3163f9bf5ae7c82b)
      #28 pc 00000000001eb22c  /system/framework/framework.jar (android.os.Looper.loopOnce+364)
      #29 pc 0000000000209334  /apex/com.android.art/lib64/libart.so (nterp_helper+52) (BuildId: d12e7186a25c1ddd3163f9bf5ae7c82b)
      #30 pc 00000000001eb954  /system/framework/framework.jar (android.os.Looper.loop+164)
      #31 pc 0000000000209334  /apex/com.android.art/lib64/libart.so (nterp_helper+52) (BuildId: d12e7186a25c1ddd3163f9bf5ae7c82b)
      #32 pc 00000000001c71fa  /system/framework/framework.jar (android.app.ActivityThread.main+246)
      #33 pc 0000000000210c00  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+576) (BuildId: d12e7186a25c1ddd3163f9bf5ae7c82b)
      #34 pc 000000000027b4ac  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+240) (BuildId: d12e7186a25c1ddd3163f9bf5ae7c82b)
      #35 pc 0000000000616f84  /apex/com.android.art/lib64/libart.so (_jobject* art::InvokeMethod<(art::PointerSize)8>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+1400) (BuildId: d12e7186a25c1ddd3163f9bf5ae7c82b)
      #36 pc 0000000000596aa0  /apex/com.android.art/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+52) (BuildId: d12e7186a25c1ddd3163f9bf5ae7c82b)
      #37 pc 0000000000099148  /system/framework/arm64/boot.oat (art_jni_trampoline+120) (BuildId: 8866718553fbb042237b10160dc0900ab55a1ed6)
      #38 pc 000000000020a2b0  /apex/com.android.art/lib64/libart.so (nterp_helper+4016) (BuildId: d12e7186a25c1ddd3163f9bf5ae7c82b)
      #39 pc 0000000000414082  /system/framework/framework.jar (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+22)
      #40 pc 00000000007d04cc  /system/framework/arm64/boot-framework.oat (com.android.internal.os.ZygoteInit.main+3228) (BuildId: cab484a9d26c83b956c3f8504c572a12bbc5e52a)
      #41 pc 0000000000210c00  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+576) (BuildId: d12e7186a25c1ddd3163f9bf5ae7c82b)
      #42 pc 000000000027b4ac  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+240) (BuildId: d12e7186a25c1ddd3163f9bf5ae7c82b)
      #43 pc 000000000061770c  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, std::__va_list)+452) (BuildId: d12e7186a25c1ddd3163f9bf5ae7c82b)
      #44 pc 0000000000617bf8  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+96) (BuildId: d12e7186a25c1ddd3163f9bf5ae7c82b)
      #45 pc 00000000004ff01c  /apex/com.android.art/lib64/libart.so (art::JNI<true>::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+600) (BuildId: d12e7186a25c1ddd3163f9bf5ae7c82b)
      #46 pc 00000000000c1c04  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+124) (BuildId: e68abca06f3b81b7eb0567bfbd99abd5)
      #47 pc 00000000000ce80c  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+924) (BuildId: e68abca06f3b81b7eb0567bfbd99abd5)
      #48 pc 0000000000002610  /system/bin/app_process64 (main+1464) (BuildId: 6363373b68588b10c93602a28a32bb57)
      #49 pc 00000000000859b8  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+100) (BuildId: 449f781894033dce6346794a1ee593e0)

**Comment by h3r3x3** [comment]
有demo吗，你这个堆栈看起来很普通的不一样，还原不了什么信息。我在机型用你的代码没有复测出来。最好能提供下你们这个场景的demo

**Comment by domchen** [comment]
长时间进一步信息反馈先关闭，有新的附加信息可重新开启。
