### ISSUE TITLE
Android 10 以上偶现崩溃 pag::Layer::~Layer

### ISSUE THREAD

**Issue by PJYGit** [Tencent/libpag#1640]
## 【版本信息】

4.1.49

## 【平台信息】

Android 原生 

## 【崩溃信息】
<img width="1069" alt="image" src="https://github.com/Tencent/libpag/assets/48624220/7e97d8f9-d830-428e-9a4a-0da2d7d5abc3">

## 【系统分布】
<img width="815" alt="image" src="https://github.com/Tencent/libpag/assets/48624220/71ad4ed3-5c34-4fb8-aa7e-c0fb50ca9ddf">

**Comment by kevingpqi123** [comment]
和 1639 一样，建议附上完整的 crash 信息，包含堆栈和 log

**Comment by domchen** [comment]
先关闭，补充有效信息后可以重新打开。
