### ISSUE TITLE
android设备上文字渲染存在异常显示

### ISSUE THREAD

**Issue by zhangtuanqing** [Tencent/libpag#1641]
## 【版本信息】
4.0.5.82　main分支也有此问题．但是3.0版本没有问题．

## 【平台信息】

Android 原生

## 【预期的表现】
文字渲染正常

## 【实际的情况】
文字（尤其是英文非等宽字符）渲染时存在异常，单个字符上存在一些异常的点，线或者色块, 参考附件图片．
修改libpag的TextAtlas.cpp:addRect后显示正常, 貌似字模在Atlas中的放置位置可能重叠导致．
Demo: https://github.com/zhangtuanqing/pag-android.git

修改处：
![TextAtlas修复字模放置位置重叠](https://github.com/Tencent/libpag/assets/58389929/1cebfcc0-6028-487c-8c0b-a32f4d950c4d)

修改后显示正常的截图：
![修改后](https://github.com/Tencent/libpag/assets/58389929/f187e1d4-77df-4bc5-b5b0-de6a64013a05)

修改前字体显示有小色块的截图（字符o)：
![修改前](https://github.com/Tencent/libpag/assets/58389929/2381c1f6-aa9e-4057-8d8f-7aae2bf0e80e)

**Comment by kevingpqi123** [comment]
感谢反馈，我们看下这个问题

**Comment by lvpengwei** [comment]
非常感谢，我验证了你的修改，是没问题的。我提了 pr 已经合入 main 了，在 commit 里带上了你的信息，可能你的账户不是用的这个邮箱，所以没有关联到 github 账户。
<img width="474" alt="image" src="https://github.com/Tencent/libpag/assets/6805075/fb915e8d-10f4-40af-8a03-9c9de576de7b">
