### ISSUE TITLE
PAGText 字符串自动换行后把单词切开了

### ISSUE THREAD

**Issue by herochengm** [Tencent/libpag#1656]
## 【版本信息】

4.2.100

## 【平台信息】

Android 原生 | iOS 原生 | Web 浏览器 | 微信小程序 | Linux | Flutter | 其他

## 【预期的表现】

![image](https://github.com/Tencent/libpag/assets/6812349/ffb49177-340a-4834-9c85-caa3c27f4019)

## 【实际的情况】

![image](https://github.com/Tencent/libpag/assets/6812349/d08855c1-fbeb-4b9a-b987-e23068d149c2)
demo 中的 mo 不要被拆改, 要么 demo 在上一行, 要么在下一行

附件
[small.pag.zip](https://github.com/Tencent/libpag/files/12327254/small.pag.zip)

**Comment by kevingpqi123** [comment]
pag 侧暂时没有支持换行英文分词的功能，需要业务侧做些处理
两种处理方法：
1、获取文本框的宽度，业务侧计算一行文本排版需要的最大宽度，输入文本中加入相应的换行符；
2、pag 设计成占位图填充的工程，文本渲染部分基于平台侧的 API 接口实现，然后截图做占位图填充
