### ISSUE TITLE
长文本无法居中显示

### ISSUE THREAD

**Issue by herochengm** [Tencent/libpag#1657]
## 【版本信息】

4.2.100

## 【平台信息】

Android 原生 | iOS 原生 | Web 浏览器 | 微信小程序 | Linux | Flutter | 其他

## 【预期的表现】

长文本情况下可以居中显示

## 【实际的情况】
![image](https://github.com/Tencent/libpag/assets/6812349/c50772bc-ea65-4d77-8eaf-a64af8da263a)
单个单词的显示效果是居中的;
![image](https://github.com/Tencent/libpag/assets/6812349/b746714b-1c1a-4ce7-8b78-fab6133ae72a)
长文本的时候的显示效果,文本没有居中,明显偏上了,第二行的地步不应该有这么大空隙

**Comment by kevingpqi123** [comment]
这类问题建议看下 AE 工程，确认下文本框是否和颜色区域是吻合，出现这种情况的原因大概是文本框区域和颜色区域不一致
