### ISSUE TITLE
PAGDiskCache.SetMaxDiskSize 崩溃

### ISSUE THREAD

**Issue by zijinzhiyun** [Tencent/libpag#1659]
## 【版本信息】

4.2.92

## 【平台信息】

Android 原生

#00 pc 00000000002e1ac0 /data/app/com.xintiaotime.yoy-53jpZUTfunQ5Jz-r3jJ3dQ==/lib/arm64/libpag.so [arm64-v8a::] 
#01 pc 00000000002e1908 /data/app/com.xintiaotime.yoy-53jpZUTfunQ5Jz-r3jJ3dQ==/lib/arm64/libpag.so [arm64-v8a::] java: java.lang.Runtime.nativeLoad(Runtime.java:1115) java.lang.Runtime.loadLibrary0(Runtime.java:1069) java.lang.Runtime.loadLibrary0(Runtime.java:1007) java.lang.System.loadLibrary(System.java:1668) org.extra.tools.a.c(SourceFile:2) org.extra.tools.a.d(SourceFile:1) org.extra.tools.a.e(SourceFile:4) 
org.libpag.PAGDiskCache.<clinit>(SourceFile:1) org.libpag.PAGDiskCache.SetMaxDiskSize(Native Method)

**Comment by kevingpqi123** [comment]
后续反馈类似问题建议提供完整的信息：
比如这类信息需要提供是否必现，使用的方式（使用的是 aar 还是 so 下发），出现问题的架构（模拟器还是真机）

信息不全就需要反复确认问题

从堆栈上看，是 JNI 加载的问题，如果是模拟器端的问题，可能要看下自己的架构匹配

**Comment by zijinzhiyun** [comment]
> 后续反馈类似问题建议提供完整的信息： 比如这类信息需要提供是否必现，使用的方式（使用的是 aar 还是 so 下发），出现问题的架构（模拟器还是真机）
> 
> 信息不全就需要反复确认问题
> 
> 从堆栈上看，是 JNI 加载的问题，如果是模拟器端的问题，可能要看下自己的架构匹配

不是必现，使用的gradle引入，是真机，架构的话，堆栈上面应该可以看到，arm64-v8a
手机型号：CDY-AN90、NTH-AN00、STK-AL00、CLT-AL01、JNY-AL10等
操作系统：Android、鸿蒙
操作系统版本：10 - 13

**Comment by h3r3x3** [comment]
堆栈信息不全，无法有效的定位原因，需要提供完整的native堆栈。
另外92是很老的版本了，建议升级到最新的104，修了很多bug。
