### ISSUE TITLE
频繁调用某个Pag动效时，里面有些图层偶尔会一闪一闪

### ISSUE THREAD

**Issue by linxiangcheer** [Tencent/libpag#1670]
## 【版本信息】
4.2.100

## 【平台信息】
Android 原生 

## 【预期的表现】
pag动画正常展示。

## 【实际的情况】
频繁调用某个Pag动效时，里面有些图层偶尔会一闪一闪。

## 【Demo及附件】
![微信截图_20230817094027](https://github.com/Tencent/libpag/assets/13765286/73de1623-63e8-41f3-924b-cdb80b6b5fc8)

**Comment by kevingpqi123** [comment]
这类问题建议附上 demo 工程及复现路径

**Comment by kevingpqi123** [comment]
未提供进一步的信息，暂时关闭
