### ISSUE TITLE
FromTextureForAsyncThread创建的纹理，低端机在OpenGL环境中绘制该纹理，画面闪烁和内容缺失，每次更新flush方法之后，调用makeSnapshot，再进行绘制，画面正常渲染

### ISSUE THREAD

**Issue by tanpan-2021** [Tencent/libpag#1684]
## 【版本信息】

4.3。10

## 【平台信息】

Android 原生 | iOS 原生 | Web 浏览器 | 微信小程序 | Linux | Flutter | 其他

## 【预期的表现】

正常渲染PAG画面
## 【实际的情况】

画面缺失，闪烁，
## 【Demo及附件】    

` //初始化      
        val textureId = genPagTexture(width, height)
        val pagPlayer = PAGPlayer()
        pagPlayer.composition = pagFile
        pagPlayer.surface = PAGSurface.FromTextureForAsyncThread(textureId, width, height, true)
        pagPlayer.prepare()`

`//更新
  player.progress = process
  player.flush()
  //增加下面代码，画面正常渲染
 **player.surface.makeSnapshot()**
`

**Comment by kevingpqi123** [comment]
可以看下 API 文档，flush 的方法的注释：Apply all pending changes to the target surface immediately.
是渲染当前帧的接口，没有渲染当前帧就去调用 makeSnapshot 肯定有问题哈

**Comment by tanpan-2021** [comment]
- 遇到的场景是，调用完Flush方法之后，使用创建PagSurface的纹理直接去绘制到屏幕上，显示内容是缺失的，不过，调用完Flush方法之后，再调用MakeSnapShot，这个时候，拿着这个纹理去绘制，内容就正常显示了，所以很好奇，MakeSnapShot是有做什么神奇的操作么，有一种感觉就是，flush之后，Surface上的内容没有立即更新上，通过调用makeSnapshot的内部某个方法，将Surface的内容刷新了

**Comment by kevingpqi123** [comment]
应该是你实现的问题，makeSnapShot 就是调用 readPixels 的接口，将纹理数据读取出来，没有其他的操作
可以参考下 Android 的官方 demo，上面有 PAGSurface 通过纹理创建的使用范例，整个渲染过程中没有调用过 makeSnapshot

**Comment by tanpan-2021** [comment]
在其他性能好一点 的手机效果都是OK的，只有部分差的机型上 才会出现这个问题，所以很好奇，flush方法的注释不是会立刻渲染内容么，为什么性能差的手机，绘制这个纹理，内容是缺失，仿佛需要GLReadPixel来保证渲染完成

**Comment by kevingpqi123** [comment]
建议提供复现 demo 和 复现机型，如果有类似问题，我们来分析具体的原因，提高对接的效率

**Comment by domchen** [comment]
你这个PAGSurface.FromTextureForAsyncThread 应该不是IOS接口，看写法也不是C++接口，IOS平台是没有暴露纹理方式创建PAGSurface的，你的问题其实就是这里。IOS端推荐一律使用CVPixelBuffer做桥接，你可以通过一个CVPixelBuffer绑定PAGSurface，然后你再用CVPixelBuffer去绘制，不会出现闪烁。闪烁的原因是GPU纹理绘制本身就不是同步的，需要借助 Semaphore机制来实现同步，背后其实就是GLSync，你搜索一下GLSync或者GLFence相关接口的资料就明白原理了。如果用的是CVPixelBuffer，IOS会帮你调用这个。如果你是通过C++方式调用，直接从纹理创建的PAGSurface。需要调用PAGPlayer.flushAndSignalSemaphore(BackendSemaphore*) 这个接口配合使用，不能直接flush。然后获取BackendSemaphore里的GLSync，在你使用纹理绘制的地方，wait它一下就可以实现GPU指令层面的顺序执行不闪烁了。你调用makeSnapshot之所以不闪烁，也是因为readPixels是一次强制GPU和CPU的同步操作，把内容都阻塞刷新了。用 GLSyn不会出现阻塞。

**Comment by hjm1fb** [comment]
直接调用PAG的PAGPlayer::waitSync(long sync)方法的话，还是会闪烁，此时waitSync返回true，即表示同步成功。
改成自行调用
`GLES30.glClientWaitSync(it, GL_SYNC_FLUSH_COMMANDS_BIT, GL_TIMEOUT_IGNORED);
 glDeleteSync(it);`就好了
看了一下PAGPlayer::waitSync(long sync)最终调用的方法是
`gl->waitSync(glSync, 0, GL_TIMEOUT_IGNORED);
  gl->deleteSync(glSync);`
即gpu的数据同步接口glWaitSync。
而glClientWaitSync是cpu和gpu数据都会同步。
猜测是PAG里有用到纹理转cpu数据的操作，所以需要glClientWaitSync。
那是不是可以考虑PAGPlayer::waitSync(long sync)最终也调用glClientWaitSync方法？

**Comment by domchen** [comment]
Skia的实现也是glWaitSync()，GLSync的本意是让wait在GPU异步发生，你如果调用glClientWaitSync()就完全失去意义了，这个接口和执行glFinish()的含义是类似的, 都是阻塞CPU什么都不干等待GPU渲染完成，性能会非常的差。你还会闪烁应该是去检查一下你传入的那个纹理的内容是不是有调用过writePixels之类的同步写入。如果你在正常提交完异步渲染指令到那个纹理之后，又操作了同步的方法去修改像素，那状态就会变成了未定义。
