### ISSUE TITLE
release版本可以更新一下了，Android demo用的4.3.17，文档还是4.2.100。 该版本播放一次动画时，首次加载动画一闪就结束了，后面才能正常播放。

### ISSUE THREAD

**Issue by jzlun** [Tencent/libpag#1685]
## 【版本信息】

4.2.88

## 【平台信息】

Android 原生 | iOS 原生 | Web 浏览器 | 微信小程序 | Linux | Flutter | 其他

**Comment by kevingpqi123** [comment]
同 https://github.com/Tencent/libpag/issues/1683
