### ISSUE TITLE
pag crash

### ISSUE THREAD

**Issue by liuyuesheng** [Tencent/libpag#1688]
java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String org.libpag.PAG.SDKVersion() (tried Java_org_libpag_PAG_SDKVersion and Java_org_libpag_PAG_SDKVersion__)
        at org.libpag.PAG.SDKVersion(Native Method)
        
魅族16th
偶现，app里有arm64得包，cpu是64架构得
参考
https://blog.csdn.net/justFWD/article/details/50339109
安卓有低概率加载so失败
是否采用relinker去加载

**Comment by kevingpqi123** [comment]
pag 一直使用的是 relinker 加载 so， https://github.com/Tencent/libpag/tree/main/android/libpag/src/main/java/org/extra/relinker
可以进一步分析下 so 加载失败的原因，是架构匹配的问题还是其它的，如果有完善方案，欢迎反馈给我们

**Comment by kevingpqi123** [comment]
长时间无进一步的信息提供，关闭该 issue
