### ISSUE TITLE
部分手机无法播放动画 (默认关闭了动画伸缩)

### ISSUE THREAD

**Issue by duxxz** [Tencent/libpag#1698]
![image](https://github.com/Tencent/libpag/assets/6425288/4651f742-bf6d-40db-bda6-377af58c4718)

可以参考这种方式, 开启动画伸缩

## 【版本信息】

4.2.88

## 【平台信息】

Android 原生 | iOS 原生 | Web 浏览器 | 微信小程序 | Linux | Flutter | 其他

**Comment by kevingpqi123** [comment]
动画时长伸缩一般在开发者选项中，默认是打开的
没有计划去强制打开，这是用户的正常行为

**Comment by duxxz** [comment]
> 动画时长伸缩一般在开发者选项中，默认是打开的 没有计划去强制打开，这是用户的正常行为

不是的. 有部分手机是有这种默认关闭的情况的. 比如. vivo s12. Android14,  华为荣耀x30, 用户升级到 Android13对应的版本, 也可能是系统版本升级过程中有什么修改, 根据用户反馈. 是没有手动去开启开发模式的. 
是否能参照svga播放的实现方式. 

> ![image](https://github.com/Tencent/libpag/assets/6425288/4651f742-bf6d-40db-bda6-377af58c4718)
> 
> 可以参考这种方式, 开启动画伸缩
> 
> ## 【版本信息】
> 4.2.88
> 
> ## 【平台信息】
> Android 原生 | iOS 原生 | Web 浏览器 | 微信小程序 | Linux | Flutter | 其他
> 
> ## 【预期的表现】
> ## 【实际的情况】
> ## 【Demo及附件】

这种反射实现的方式解决
