### ISSUE TITLE
APP回到前台时发生内存访问异常：Exception Type: EXC_BAD_ACCESS (SIGBUS)

### ISSUE THREAD

**Issue by zxwo0o** [Tencent/libpag#1701]
## 【版本信息】

4.1.16

## 【平台信息】

iOS 原生，APP同时有集成百度地图SDK

## 【实际的情况】

Xcode 中有收集到较多的内存异常访问的crash  ，大部分的闪退场景都是APP到后台一段时间后，然后再回到前台时发生异常，且崩溃的代码问题点无法解析到；

Exception Type:  EXC_BAD_ACCESS (SIGBUS)
Exception Subtype: UNKNOWN_0x101 at 0x0000000000000001
Exception Codes: 0x0000000000000101, 0x0000000000000001

想请问下，[v4.2.100] 这个版本中关于修复了 iOS 平台同时集成百度地图 SDK 时 crash 问题，这个crash是否类似我这种异常场景  ？

**Comment by kevingpqi123** [comment]
和这个没有关系，和百度地图的 SDK 的crash 时是因为百度地图 SDK 暴露了部分 OpenGL 的方法导致链接出现异常，如果你这边了可以稳定复现，可以提供下复现 demo 及复现场景，能够复现到的问题都比较好解决
