### ISSUE TITLE
怎么关闭上报，不然cta过不去

### ISSUE THREAD

**Issue by liuyuesheng** [Tencent/libpag#1707]

**Comment by liuyuesheng** [comment]
CTA要求再同意上网协议以前不能请求网络，但是如果用这个做空白页，就会自动触发上报

**Comment by kevingpqi123** [comment]
你们是在 APP 启动动画中使用了 pag 吗，只有当首次使用了 PAG 方法的时候才会触发上报，如果没有使用到就不会触发

**Comment by Jxlimeng** [comment]
我这边的情况是就算应用拒绝了隐私弹框，也会进入到应用显示空白页面
这个时候会有请求网络操作，导致cta问题
这种情况是不是只能把空白页动画功能屏蔽了

**Comment by Jxlimeng** [comment]
腾讯能不能开放接口，让应用来决定是否上报呀！
这样应用就可以根据用户是否同意来判断要不要上报

**Comment by kevingpqi123** [comment]
如果你们不需要上报的功能，可以根据开源的源码自己构建版本
外发的官方版本上报是必须的，目前都在降本增效，我们需要根据接入的情况向老板申请开发和维护人力资源

**Comment by liuyuesheng** [comment]
4.2.100是哪个分支哈，我看主分支是4.1

> 如果你们不需要上报的功能，可以根据开源的源码自己构建版本 外发的官方版本上报是必须的，目前都在降本增效，我们需要根据接入的情况向老板申请开发和维护人力资源

**Comment by kevingpqi123** [comment]
release/4.2
