### ISSUE TITLE
PAGImageView加载pag文件有白色噪点

### ISSUE THREAD

**Issue by FoneG** [Tencent/libpag#1718]
## 【版本信息】

4.2.88

## 【平台信息】

 iOS 原生 

## 【实际的情况】
瀑布流上的PAGImageView 设置pag路径并播放，会出现白色噪点, 偶尔甚至画面会抖动

**Comment by FoneG** [comment]
https://github.com/Tencent/libpag/assets/15395364/804eb0d8-9ae3-4eb3-b8f9-44884296941e

**Comment by FoneG** [comment]
[3_4.pag.zip](https://github.com/Tencent/libpag/files/12556836/3_4.pag.zip)

**Comment by domchen** [comment]
文件没啥问题，有复现的demo吗？上传一下吧
