### ISSUE TITLE
在摩托罗拉的Android手机上，pag动画运行速度太快了

### ISSUE THREAD

**Issue by Grasshopper-programmer** [Tencent/libpag#1733]
我们团队录制视频的按钮采用pagView动画，动画为30s的pag动画，录制最长时间也是30s，但是我们发现在摩托罗拉手机中，30s的动画会变快，甚至是20s就跑完了30s的动画，很诧异，其他手机中没有这个问题。

## 【版本信息】

(com.tencent.tav:libpag:4.1.49)

## 【平台信息】

Android 原生----- 手机设备：moto g stylus 5G(2022)

android 版本：12     RAM：8GB   ROM：256GB

## 【Demo及附件】
[photo_camera_hp.txt](https://github.com/Tencent/libpag/files/12639959/photo_camera_hp.txt)

pag文件传不上去，所以我把内容保存为txt文件，请查看；谢谢各位大佬！

**Comment by kevingpqi123** [comment]
pag 动画的播放时钟依赖于系统的 ValueAnimator，检查一下影响 ValueAnimator 时钟的设置，如开发者模式中的 “动画时长伸缩”是否为 1 等
