### ISSUE TITLE
iOS上关于PAG的使用问题反馈（有演示demo）

### ISSUE THREAD

**Issue by FoneG** [Tencent/libpag#1774]
## 【版本信息】

4.3.3

## 【平台信息】

iOS 原生

## 【预期的表现】

瀑布流上复用显示正常，列表滑动不卡顿，低端机上保证不异常奔溃。

## 【实际的情况】
1. 性能较差的设备（iPhone6/6p、iPhone7/7p）上偶发crash，在频繁滑动列表的时候较容易出现 （低端机上比较容易复现）
2. 滑动列表cell复用的时候，PAG经常会错乱（容易复习）
3. 列表滑动的时候设置停止播放且显示第一帧，会导致掉帧（低端机比较明显）
crash截图：
<img width="1986" alt="截屏2023-10-13 20 21 17" src="https://github.com/Tencent/libpag/assets/15395364/563d503b-f26d-479d-bd9d-d9c2effbabec">
<img width="1995" alt="截屏2023-10-13 19 34 16" src="https://github.com/Tencent/libpag/assets/15395364/41c338c7-8d61-4f71-8c88-97f0ab31e96c">

PAG经常会错乱视频
https://github.com/FoneG/pagDemo/blob/main/RPReplay_Final1697198724.MP4

## 【Demo及附件】

demo下载地址：git@github.com:FoneG/pagDemo.git

**Comment by FoneG** [comment]
@domchen

**Comment by kevingpqi123** [comment]
看了下你这边的实现，使用的是 PAGView， PAGView 的每一帧都是实时渲染的：
（1）针对错乱的问题，问题的原因可能是刷新不及时， PAG 的首帧渲染由于需要构建渲染环境及缓存，首帧渲染耗时相对较慢，在中低端机型可能会更明显些，在 cell 复用的过程中，如果上一帧渲染内容没有被清空，可能会短暂显示上一帧渲染的内容，直至当前 PAG 文件的首帧渲染完成；
（2）列表滑动的时候设置停止播放且显示第一帧，此时 pag 将不会再进行渲染，原则上将不会再消耗资源，如果还有掉帧，建议排查下是否还有其它耗时的操作

推荐解决方案：由于这里涉及到占位图替换，使用不了 PAGImageView，只能使用 PAGView，此时一种优化处理方案是针对中低端机型，在 cell 上面添加一个 ImageView，显示一张图片，当 cell 开始展示时， 先展示这张图片，当前 PAGView 的首帧渲染完成中，切换 为 PAGView 的动画播放

**Comment by FoneG** [comment]
感谢回复。

1)  关于复用问题我重新提交了一个[视频](https://github.com/FoneG/pagDemo/blob/main/RPReplay_Final1698054901.mov)，希望能看一下，并非是帧渲染未完成的情况。
2) demo可以验证了是设置显示第一帧这个行为导致了掉帧，注释 [self.pagView setProgress:0]代码再做滑动，在低端机上也会很流畅。
3) 另外就是crash的问题，这个在低端机上真的出现频率挺高的，导致目前我们搁置了pag的使用。希望能得到您的重视!

**Comment by FoneG** [comment]
@kevingpqi123 大佬 请问反馈的问题会解决吗

**Comment by kevingpqi123** [comment]
crash 的问题已经修复，4.2 版本 4.2.108 已经修复， 4.3 下周会发布一个稳定版，也会带上这个修复

至于你提到的 1 和 2 并没有复现到，你可以基于 4.2.108 版本测试下，如果还有问题，可以通过 QQ 联系我

**Comment by kevingpqi123** [comment]
感谢提供复现 demo，只要是必现或有复现路径的问题，一般都能够有效解决

**Comment by FoneG** [comment]
赞 crash和错乱的问题没有再复现了。不过低性能的设备上滑动还是会有点卡顿，如果还有优化，麻烦@我，感谢

**Comment by wangwanjie** [comment]
> 推荐解决方案：由于这里涉及到占位图替换，使用不了 PAGImageView，只能使用 PAGView，此时一种优化处理方案是针对中低端机型，在 cell 上面添加一个 ImageView，显示一张图片，当 cell 开始展示时， 先展示这张图片，当前 PAGView 的首帧渲染完成中，切换 为 PAGView 的动画播放
请问下“当前 PAGView 的首帧渲染完成”这个事件怎么获取？我用的4.2.88貌似没看到这类回调

**Comment by domchen** [comment]
> > 推荐解决方案：由于这里涉及到占位图替换，使用不了 PAGImageView，只能使用 PAGView，此时一种优化处理方案是针对中低端机型，在 cell 上面添加一个 ImageView，显示一张图片，当 cell 开始展示时， 先展示这张图片，当前 PAGView 的首帧渲染完成中，切换 为 PAGView 的动画播放
> 
> 请问下“当前 PAGView 的首帧渲染完成”这个事件怎么获取？我用的4.2.88貌似没看到这类回调

这是同步的，你自己启动一个子线程，手动调用一下PAGVIew.flush()，调用结束就是完成了首帧渲染。

**Comment by wangwanjie** [comment]
> > > 推荐解决方案：由于这里涉及到占位图替换，使用不了 PAGImageView，只能使用 PAGView，此时一种优化处理方案是针对中低端机型，在 cell 上面添加一个 ImageView，显示一张图片，当 cell 开始展示时， 先展示这张图片，当前 PAGView 的首帧渲染完成中，切换 为 PAGView 的动画播放
> > 
> > 
> > 请问下“当前 PAGView 的首帧渲染完成”这个事件怎么获取？我用的4.2.88貌似没看到这类回调
> 
> 这是同步的，你自己启动一个子线程，手动调用一下PAGVIew.flush()，调用结束就是完成了首帧渲染。

PAGView 实现有个属性控制是否同步 flush 的，我这边用的一直是 async 的，这种貌似没接口给出来
