### ISSUE TITLE
wrong version string

### ISSUE THREAD

**Issue by jcyuan** [Tencent/libpag#1798]
https://github.com/Tencent/libpag/blob/06ea5fa432ca2636ad9d468a834fafc28c9138ca/src/rendering/PAG.cpp#L23

not sure if this value is just on purpose in case the release version string is different with this value, so i didn't send a PR and use this thread as a reminder instead.

**Comment by domchen** [comment]
It is just a placeholder which will be replaced by the real version number in the release building process.
