### ISSUE TITLE
iOS 想编译出 arm64 和x86 独立的库，这个能帮忙导出下吗

### ISSUE THREAD

**Issue by ifgyong** [Tencent/libpag#1813]
iOS 想编译出 arm64 和x86 独立的库，这个能帮忙导出下吗？

**Comment by ifgyong** [comment]
有大佬帮个忙 吗？

**Comment by kevingpqi123** [comment]
可以看下这篇文章：https://www.jianshu.com/p/f50053d50436
我们只提供公共的制品库，个性化的需求需要自己处理
