### ISSUE TITLE
Windows编译libpag库时报错The source directory "./third_party/tgfx/third_party/libjpeg-turbo" does not exist.

### ISSUE THREAD

**Issue by jackTJT** [Tencent/libpag#1831]
## 【版本信息】

4.2.100

## 【平台信息】

windows

## 【预期的表现】
执行node .\vendor_tools\cmake-build pag -p win -o .\win\paglib -v -i -DPAG_BUILD_SHARED=OFF后无报错

## 【实际的情况】
执行该命令后，报错The source directory "./third_party/tgfx/third_party/libjpeg-turbo" does not exist.
<img width="858" alt="40959aebb5f6db44f7081af20fec21cb" src="https://github.com/Tencent/libpag/assets/96832322/058f4248-1383-424a-9c19-8b196bedeb70">

不知是否是Generating tgfx-vendor为0/489所影响
<img width="861" alt="612e3f047531c0e1ae9da51e28eb322e" src="https://github.com/Tencent/libpag/assets/96832322/e30de952-fb02-4202-9823-e41630c4d3a1">

**Comment by domchen** [comment]
你没有同步仓库，在libpag的根目录运行一下depsync命令，不要忽略错误提示，提示要升级depsync就npm install -g depsync
升级一下。

**Comment by jackTJT** [comment]
最新的depsync将libjpeg-turbo放在了tgfx之外

**Comment by domchen** [comment]
> 最新的depsync将libjpeg-turbo放在了tgfx之外

你这个就是没有执行过depsync，仓库还是旧的的缓存，执行同步的时候看一下有没报错。
