### ISSUE TITLE
Windows编译Win32Demo.sln生成pag.lib时，出现无rendering/drawables/Drawable.h错误

### ISSUE THREAD

**Issue by jackTJT** [Tencent/libpag#1832]
## 【版本信息】

4.2.100

## 【平台信息】

Windows

## 【实际的情况】
Windows编译Win32Demo.sln生成pag.lib时，出现无rendering/drawables/Drawable.h错误
<img width="514" alt="404f4166dcbc70e342e399e4bb95b4db" src="https://github.com/Tencent/libpag/assets/96832322/43fae2b4-f000-4e99-8fc9-df6c6bb52b70">

<img width="272" alt="a0de28c2e531b2c428cbb04acd651d65" src="https://github.com/Tencent/libpag/assets/96832322/a9f7d164-ae1a-466a-bf07-5d82dd32de70">

**Comment by jackTJT** [comment]
该错误是因为最新的libpag用depsync同步的第三方依赖库的位置与旧版本发生了很大变化，无法用原来的路径来获取了

**Comment by domchen** [comment]
windows demo已经修复了，跟新到main分支最新代码即可。
