### ISSUE TITLE
CVPixelBuffer pixel color reading problem. 

### ISSUE THREAD

**Issue by alyfreym** [Tencent/libpag#1860]
I'm using this library with custom AVComposition on iOS.
When I take source pixel buffer from pipeline and put this image using
 `image = [PAGImage FromPixelBuffer:pixelBuffer]`
 `[replaceImage:editableIndex.intValue data:image]`
color in this frame changed. Screenshots below. 

Source image frame 
<img width="582" alt="Screenshot 2023-11-11 at 15 42 27" src="https://github.com/Tencent/libpag/assets/29518174/555dc6e6-07cc-4c9f-a048-4a03cc8e6ced">

And pag render this image like this 
<img width="582" alt="result" src="https://github.com/Tencent/libpag/assets/29518174/76cdac3a-307a-46f2-9f4b-e2eb56d13f5b">

The color gets darker.

Source video file. 

https://github.com/Tencent/libpag/assets/29518174/89bac8a3-2a95-4858-a8b6-e91e7ae022cd

When I convert CVPixelBuffer to CGImage 
Like this

`myCIImage = CIImage(cvPixelBuffer: buffer)`

`cgImage =  CIContext.createCGImage(myCIImage, from: CGRect(origin: .zero, size: .init(width: w, height: h)))`

`[PAGImage FromCGImage:cgImage]`

Everything works fine.

So we have problems, when user upload custom CVPixelBuffer image in to PAGComposition color changed. We need wrap and render this pixel buffer in to CGImage and then replace it. I think the mistake is that it's wrong CVPixelBuffer color space detection.

**Comment by domchen** [comment]
Is it an HDR video？If so, you need to configure the AVFoundation to generate frames with a normal color range. Or convert it by yourself. Normally you will not be able to tell the difference if you convert the color space property. PAG does not support rendering in wide color range at this moment, which will certainly require a lot of work. For now, use the sRGB color space is the most safe way to avoid color space issues.
