### ISSUE TITLE
iOS crash

### ISSUE THREAD

**Issue by coreyfu1** [Tencent/libpag#1870]
### Discussed in https://github.com/Tencent/libpag/discussions/1865

<div type='discussions-op-text'>

<sup>Originally posted by **coreyfu1** November 13, 2023</sup>
使用libpag的过程中，发现几个比较频繁的崩溃，版本4.3.27
调试模式下：
<img width="1376" alt="截屏2023-11-13 13 27 54" src="https://github.com/Tencent/libpag/assets/17798137/0cd9aee3-474c-4a35-ae2f-14dce66287e8">
线上：
<img width="1299" alt="截屏2023-11-13 13 35 11" src="https://github.com/Tencent/libpag/assets/17798137/76843724-619e-4730-afe8-0f28da326660">
<img width="844" alt="截屏2023-11-13 13 35 39" src="https://github.com/Tencent/libpag/assets/17798137/9bc9814a-a80d-407d-9fe5-e36606779cdf">
</div>
```[tasklist]
### Tasks
```

**Comment by coreyfu1** [comment]
大佬，这个能定位问题吗？ @domchen

**Comment by domchen** [comment]
如之前讨论的，想解决这个问题首先要还原正确的堆栈，线上那几个堆栈都是错的，看不不任何有效的信息，那些函数和verify都不存在调用关系。看看是不是符号还原错了。你本地的那个和线上不一样，堆栈是有效的，可以复现的话传一个demo上来我们排查下。

**Comment by domchen** [comment]
@coreyfu1 有个新的可能的方向，我们刚刚咨询了维护 Bugly 的团队，他们确认了免费版的 Bugly 确实存在堆栈计算错误的问题。现在挂在 getVideoHeight这个地方的堆栈毫无疑问是错的，可以检查一下堆栈是否是从 Bugly 免费版提取的，如果是建议搜索一下怎么使用命令行手动还原一下真正的堆栈再贴出来，问题可能就很快可以定位到了。同时也检查一下还原堆栈用的符号版本是否和SDK版本一致。到目前唯一确定的就是提供出来的报错堆栈是错的，因此什么有效的信息也判断不了。

**Comment by coreyfu1** [comment]
> @coreyfu1 有个新的可能的方向，我们刚刚咨询了维护 Bugly 的团队，他们确认了免费版的 Bugly 确实存在堆栈计算错误的问题。现在挂在 getVideoHeight这个地方的堆栈毫无疑问是错的，可以检查一下堆栈是否是从 Bugly 免费版提取的，如果是建议搜索一下怎么使用命令行手动还原一下真正的堆栈再贴出来，问题可能就很快可以定位到了。同时也检查一下还原堆栈用的符号版本是否和SDK版本一致。到目前唯一确定的就是提供出来的报错堆栈是错的，因此什么有效的信息也判断不了。

好的，我跟踪一下🙏

**Comment by coreyfu1** [comment]
> @coreyfu1 有个新的可能的方向，我们刚刚咨询了维护 Bugly 的团队，他们确认了免费版的 Bugly 确实存在堆栈计算错误的问题。现在挂在 getVideoHeight这个地方的堆栈毫无疑问是错的，可以检查一下堆栈是否是从 Bugly 免费版提取的，如果是建议搜索一下怎么使用命令行手动还原一下真正的堆栈再贴出来，问题可能就很快可以定位到了。同时也检查一下还原堆栈用的符号版本是否和SDK版本一致。到目前唯一确定的就是提供出来的报错堆栈是错的，因此什么有效的信息也判断不了。

我看了下apple搜集的记录，定位的堆栈是这样的，看看有没有用：
![1](https://github.com/Tencent/libpag/assets/17798137/0a7598e5-da43-4651-8cb7-7a696c40a43e)
![2](https://github.com/Tencent/libpag/assets/17798137/692797d9-ad6f-4798-9536-4b45d189b26c)

**Comment by domchen** [comment]
堆栈出问题的关键位置都是没有符号的，看不出有效信息。

**Comment by domchen** [comment]
@DefuDong 你们为啥要使用非release版本？那些不在release页面发布的是中间测试构建的版本号，可能带了各种bug。直接换4.3.33吧

**Comment by DefuDong** [comment]
@domchen 这是我用 4.3.33 版本抓取的堆栈信息，看是否对定位问题有帮助
<img width="1370" alt="截屏2023-12-04 10 20 35" src="https://github.com/Tencent/libpag/assets/4230923/84a13322-2b3b-46f6-92d5-5e87e4651fcf">
<img width="1285" alt="截屏2023-12-04 10 20 55" src="https://github.com/Tencent/libpag/assets/4230923/13b68507-6e1d-4dc9-8d04-22207f26e8ba">

**Comment by domchen** [comment]
@DefuDong 你这个堆栈是对的，我们这边从源码分析一下可能的原因，但不确定一定可以定位到。你这边要是有办法构造出复现的场景，把demo上传一下会很快定位出来。

**Comment by DefuDong** [comment]
@domchen 目前看到的都是Bugly上报， 还没能复现出来。应该是从4.2升级到4.3版本新增的问题，而且都是在iOS17系统。
这个问题崩溃量还是挺多的，我再试试看能不能复现，你那边如果能定位问题也辛苦及时告知

**Comment by domchen** [comment]
@DefuDong 这个问题我们分析出来了，是子线程里无法访问EAGLLayer创建OpenGL环境，最早在好几年前的版本里加过类似的保护，但是加的时候关于出问题场景对应的注释没有补全，后来一直测试不出来子线程创建哪里会挂就把这部分逻辑简化了（可能只有部分设备会限制这个）。大部分情况下都会在主线程就立即初始化OpenGL环境，当视图尺寸改变的时候或者手动调用了freeCache，可能会概率触发这个问题。我们近期修复一下。

**Comment by domchen** [comment]
#2048 已经修复相关的crash，大家可以等这两天发的下个版本测试一下。
