### ISSUE TITLE
手机浏览器兼容性

### ISSUE THREAD

**Issue by evenle** [Tencent/libpag#19]
现在手机浏览器兼容性怎么样？

**Comment by zenoslin** [comment]
支持到
```
iOS Safari 11.3+
Android Chromium 96+
```
目前还是测试版状态，我们正在抓紧做兼容性测试，很快就会覆盖到市面上所有主流的 Web 平台

欢迎加入我们的QQ交流群893379574，提出建议和获取最新资讯
