### ISSUE TITLE
阿拉伯语显示不正确

### ISSUE THREAD

**Issue by Guaidaodl** [Tencent/libpag#1909]
## 【版本信息】

4.3.33-harfbuzz

## 【平台信息】

Android 原生

## 【预期的表现】
可以正确地显示阿拉伯语. 希望可以显示成 كابينة الغابة.

理论上来说, 接入了 harfbuzz, 应该可以跟 iOS 使用 CoreText 有一样的效果吧.

## 【实际的情况】
<img width="431" alt="image" src="https://github.com/Tencent/libpag/assets/3810104/c00aea49-b467-4246-9707-b9e4b5b483cb">

**Comment by kevingpqi123** [comment]
相同问题
https://github.com/Tencent/libpag/discussions/1545
