### ISSUE TITLE
setCompostion api是否可以在 worker方式中使用？

### ISSUE THREAD

**Issue by WhatIsSpark** [Tencent/libpag#1915]
## 【版本信息】

4.2.84

## 【平台信息】

 Web 浏览器 

## 【实际的情况】
![4TMY ~3@ZKQZ84E$P_8C6 R](https://github.com/Tencent/libpag/assets/43886132/ec16d83e-da7d-45b2-a746-a42721686050)

**Comment by WhatIsSpark** [comment]
没有找到setCompostion api
  const pagFile = await WorkerPAGFile.load(worker, buffer);
  const pagView = await WorkerPAGView.init(pagFile, canvas, { useScale: false });

**Comment by kevingpqi123** [comment]
在构造方法中，不是已经将 PAGFile 传入进去了吗，setComposition 就是设置 pag 文件，两者作用是一样的
