### ISSUE TITLE
部分手机无法播放PAG动画

### ISSUE THREAD

**Issue by lewic1987** [Tencent/libpag#1943]
## 【版本信息】
4.2.100

## 【平台信息】
Android 原生

## 【预期的表现】
在如下机型上动画正常展示

## 【实际的情况】
确定在YAL-AL50机型上官方demo动画加载异常

线上有类似机型问题：DBY-W09,HJC-AN90,GOT-W09,7531N,LYA-L29,SCM-W09,SCMR-W09,MRX-W09

## 【Demo及附件】
用官方demo在该机型上验证即可，期望尽快答复，线上客诉严重

**Comment by domchen** [comment]
有个可能的排查方向，如果用户在系统设置里自己关闭了动画功能，animationScale设置为0，表现会类似你描述的。还没开始就直接结束。因为系统层面禁用了动画功能，完全播放不了的情况下会发送结束通知。

**Comment by lewic1987** [comment]
用官方demo同样存在有些手机pag动画无法播放问题，见视频：https://static0.xesimg.com/bigclass-mobile/android/other/lewic 2024-02-02 13.29.29.mp4 @kevingpqi123 @domchen 

设备信息见：
![device-2024-02-27-133757](https://github.com/Tencent/libpag/assets/27275977/dcaafc23-abe2-4d76-8e4b-f2e3957b6929)

**Comment by domchen** [comment]
检查一下手机设置里开发者模式下的动画开关是不是关掉了

**Comment by lewic1987** [comment]
![device-2024-02-27-151625](https://github.com/Tencent/libpag/assets/27275977/504d8dc9-0e46-456d-9a19-ffbf83250322)
![device-2024-02-27-151648](https://github.com/Tencent/libpag/assets/27275977/3ad17923-0b16-488e-9dc7-a2f8b197e7ac)
@domchen 开发者模式中有个动画时长程序调整，默认是1x，如果改成关闭动画：pag动画无法播放，改成1x：pag动画正常，像这种情况pag库层面能够处理吗？lottie动画运行没问题，不然依赖这个系统开关设置，线上好多用户反馈动画问题，我们业务无法使用pag动画了

**Comment by domchen** [comment]
关闭之后lottie也无法播放的，你可以实际测试一下

**Comment by domchen** [comment]
PAG的这部分代码和lottie是一模一样的，都会在检测到系统关闭动画时立即补充一些动画播放结束的回调。如果系统关闭了动画我们还有办法能播放，这个逻辑也就没有必要了。业务方能做的也是这个检测，查看全局的animationScale是否是0就行，然后给用户一些主动提示，大部分用户只是不知道这个具体是有什么影响，这部分操作源头还是在用户那边，SDK做不了太多，并且是小概率的操作，目前手Q也是这样适配的。

**Comment by lewic1987** [comment]
@domchen 明白了，感谢解答问题
