### ISSUE TITLE
微信 WebView 使用 worker 无法播放 iOS 17.1.2

### ISSUE THREAD

**Issue by jiangyijie27** [Tencent/libpag#1953]
https://wxa.wxs.qq.com/wxad-design/yijie/web-worker/web-worker-1.html

在官方例子里，把 pag 链接改了一下。PC Chrome 能播放，iOS 微信 Webview 打开不播放，且无报错信息

## 【版本信息】

latest

## 【平台信息】

微信 WebView

## 【预期的表现】
播放

## 【实际的情况】
不播放

## 【Demo及附件】

https://wxa.wxs.qq.com/wxad-design/yijie/web-worker/web-worker-1.html

**Comment by domchen** [comment]
应该是微信Webview限制了视频自动播放能力。目前只有两种解决方式：1.用ffavc软件解码，会比较卡，并不推荐。2.修改素材，去掉bmp预合成，用矢量的方式导出pag文件。
