### ISSUE TITLE
iOS 4.3.33 崩溃

### ISSUE THREAD

**Issue by Mu7Wind** [Tencent/libpag#1961]
## 【版本信息】

4.3.33

## 【平台信息】

 iOS 原生

bugly信息
<img width="1160" alt="Snipaste_2023-12-06_20-25-06" src="https://github.com/Tencent/libpag/assets/8851165/1912f092-e44f-4522-9f5f-3365353b86fc">

**Comment by domchen** [comment]
堆栈是错的，verify函数不会调用到fileFrameToScaledFrame。免费版的Bugly还原堆栈有已知的问题。检查一下符号版本和SDK是否正确匹配，然后手工还原一下正确的堆栈信息贴出来。错误的堆栈看不出任何有效的信息。

**Comment by domchen** [comment]
先关闭，如果有正确的堆栈信息补充可以从新打开。
