### ISSUE TITLE
ios 多个pag 文件切换 界面闪烁

### ISSUE THREAD

**Issue by xiaopengLOVEcode** [Tencent/libpag#1964]
## 【版本信息】

4.3.3

## 【平台信息】

 iOS 原生

## 【Demo及附件】
![12161701934319_ pic](https://github.com/Tencent/libpag/assets/40853652/2e69fc5c-6c30-4757-8e4d-17e015e3c6c2)

动画1 和动画2 首次安装 必现 闪烁低端机更为明显

**Comment by xiaopengLOVEcode** [comment]
我这个demo 一直 提交不上去 我在qq群@您了 辛苦在百忙之中帮忙看看

**Comment by domchen** [comment]
可以传到网盘上把链接贴过来。

**Comment by xiaopengLOVEcode** [comment]
传上去了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Dom Chen ***@***.***&gt;
发送时间: 2023年12月12日 14:31
收件人: Tencent/libpag ***@***.***&gt;
抄送: xiaoxiaopeng ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Tencent/libpag] ios 多个pag 文件切换 界面闪烁 (Issue #1964)





 
可以传到网盘上把链接贴过来。

**Comment by xiaopengLOVEcode** [comment]
[TestPagDemo.zip](https://github.com/Tencent/libpag/files/13644554/TestPagDemo.zip)
辛苦给看看

**Comment by domchen** [comment]
代码并没有什么问题，只是首次运行有点慢。两个思路解决：1.优化一下素材，你的素材存在大量的图片帧，这种方式不仅文件最大，性能也最差，你不如直接用BMP预合成导出。如果不能纯矢量实现就不要用这种N个图片图层切换的方式制作，除了掩耳盗铃没有什么价值。2、把PAGView换成PAGImageView，性能会好很多，并且可以磁盘缓存。

**Comment by xiaopengLOVEcode** [comment]
bmp 会导致素材质量下降 这边有什么好的处理方式吗

**Comment by domchen** [comment]
参考导出插件的选项里设置一下最小分辨和导出质量就行，
