### ISSUE TITLE
setProgress(0.99)后调用flush，pagView渲染的依然是首帧

### ISSUE THREAD

**Issue by MillionQW** [Tencent/libpag#1967]
## 【版本信息】

4.2.84

## 【平台信息】

 Web 浏览器

## 【预期的表现】
setProgress(0.99)后调用flush，预期应该渲染出0.99时间点对应的画面

## 【实际的情况】
渲染的是首帧

## 【Demo及附件】
https://github.com/libpag/pag-web/blob/main/pages/setprogress.html
setProgress传入0.99
把pag文件替换为下面的pag:  
 https://snsrb.video.qq.com/130/20204/snssvpdownload/SH/reserved/0bc3qqaaaaaa5yagwl3ainsrdbgeaccaaaaa.f0.pag

**Comment by zhalice2011** [comment]
https://github.com/Tencent/libpag/pull/2003
