### ISSUE TITLE
iOS: 多个pag 动画切换会有闪烁的情况 

### ISSUE THREAD

**Issue by xiaopengLOVEcode** [Tencent/libpag#1968]
## 【版本信息】

4.3.3

## 【平台信息】

iOS 原生

Demo 如下  动画1 动画2 都会有闪烁的情况 低端机型会更明显

**Comment by domchen** [comment]
demo是不是忘记了上传？另外请使用正式的版本，4.3.3是预发布版本，可能带了bug。更新到 4.3.33

**Comment by xiaopengLOVEcode** [comment]
Demo我传不上去 我发在qq群@你了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Dom Chen ***@***.***&gt;
发送时间: 2023年12月12日 14:26
收件人: Tencent/libpag ***@***.***&gt;
抄送: xiaoxiaopeng ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Tencent/libpag] iOS: 多个pag 动画切换会有闪烁的情况  (Issue #1968)





 
demo是不是忘记了上传？另外请使用正式的版本，4.3.3是预发布版本，可能带了bug。更新到 4.3.33

**Comment by xiaopengLOVEcode** [comment]
[TestPagDemo.zip](https://github.com/Tencent/libpag/files/13644522/TestPagDemo.zip)
这个可以吗 辛苦给看看

**Comment by domchen** [comment]
与 #1964 重复，关闭。
