### ISSUE TITLE
给多边形或星形加圆角，总会有一个角是直角

### ISSUE THREAD

**Issue by Pinton** [Tencent/libpag#197]
#### 问题

1. 在AE中，给形状图层加圆角（矩形是正常的，出问题的是多边形和星形）
<img width="725" alt="截屏2022-03-21 上午10 30 36" src="https://user-images.githubusercontent.com/42991301/159198476-137fe2c0-e0c7-466a-9015-b62d3259009b.png">
2. AE中显示的是，图形的每个角都有圆角。但是当导出为PAG后，用PAGViewer预览时，总有一个角是直角。
<img width="850" alt="截屏2022-03-21 上午10 30 21" src="https://user-images.githubusercontent.com/42991301/159198685-0263a400-e238-48b7-895a-6946e87aa330.png">

#### 重现

1. 在AE中新建形状图层
2. 画一个多边形或者星形
3. 导出为PAG

#### 环境

libpag 版本：PAGViewer（2.2.1.3 beta）  
设备：iMac 5K（macOS 11.6）

**Comment by domchen** [comment]
@Pinton 麻烦上传一下对应的AE文件。

**Comment by Pinton** [comment]
> @Pinton 麻烦上传一下对应的AE文件。
[PAG多边形圆角导出测试.aep.zip](https://github.com/Tencent/libpag/files/8312797/PAG.aep.zip)

**Comment by domchen** [comment]
@Pinton 感谢反馈~ 这个问题在 #203 PR里已修复，已合入主干。但是目前可能要等待 4.0 版本发布稳定版后才会带出。
