### ISSUE TITLE
打包时使用 Terser 压缩失败，自己 clone 仓库后 build 的版本可以正常使用。

### ISSUE THREAD

**Issue by wiseqingyang** [Tencent/libpag#199]
#### 问题

> 打包时使用 Terser 压缩失败，自己 clone 仓库后 build 的版本可以正常使用。

#### 重现

> 使用代码压缩工具 Terser 时失败
```
🙅   Failed to compile.

js/11.cd37e1af.js from Terser
TypeError: t.replace is not a function
    at Array.forEach (<anonymous>)
```
自己在本地用 main 分支打包链接后，使用正常。猜测 npm 发布的代码有问题

#### 环境

- libpag@^0.1.0:
- @tarojs/webpack-runner@3.2.13
- terser-webpack-plugin "^3.0.5"
- terser "^4.8.0"

#### Demo（可选）

> 请给一个 Demo 项目，我们可以运行并重现这个问题。

#### 其他（可选）

> 如果还有其他信息可以帮助我们定位问题，请添加其他内容。

**Comment by zenoslin** [comment]
NPM 上发布的代码也是使用 build 命令打包出来的应该是一致的。libpag.min.js 是有使用 esbuild 上的 minify 功能的，按道理不需要再使用 terser 去压缩代码。如果你需要使用自己的压缩插件，可以考虑引入 libpag.esm.js。
非常感谢你反馈的猜测 NPM 上发布的代码有问题，我们也会查看对比一下。
