### ISSUE TITLE
对pag文件有大小的限制吗

### ISSUE THREAD

**Issue by FoxChouChou** [Tencent/libpag#1999]
#加载方式
https://cdn.jsdelivr.net/npm/libpag@latest/lib/libpag.min.js

#处理pag
1 fetch('xxx.pag').then(response => response.arrayBuffer()
2 PAG.PAGFile.loadFromBuffer(buffer)

#遇到问题
测试环境加载慢（20s+）但是动画展示正常，线上加载失败控制台报错：
1 falling back to ArrayBuffer instantiation
2 wasm streaming compile failed: TypeError: first argument must be an Response or Promise for Response
3 try catch捕获的error.message：Load failed

报错的pag文件的大小是415kb，请问，是文件过大导致的加载失败吗？
ps：尝试换了个103kb的pag文件，加载成功了。

**Comment by FoxChouChou** [comment]
已解决

**Comment by zkw55** [comment]
> 已解决

请问怎么解决呢
