### ISSUE TITLE
对比 Vap

### ISSUE THREAD

**Issue by CherryLover** [Tencent/libpag#20]
Pag 相比较 Vap，新增了哪些功能吗？视频编辑是不是就是 Vap 中的融合元素？
有没有什么工具能从 Vap 转到 Pap，还是只能在现有 Vap 项目中加入 Pag 的 SDK？

**Comment by domchen** [comment]
VAP 应该只是实现了 PAG 功能里比较小的一个子集。你可以参考一下 [README.md](https://github.com/Tencent/libpag/blob/main/README.zh_CN.md) 里的两篇外链介绍, PAG 实现了完整的AE导出能力，可以支持纯矢量和序列帧混合导出，并且在运行时可以在保留动画效果的前提下修改内容。有其他的问题可以到 QQ 893379574 群提问。
