### ISSUE TITLE
iOS crash，子线程更新UI

### ISSUE THREAD

**Issue by iwangjiajun** [Tencent/libpag#2001]
## 【版本信息】

4.3.8

## 【平台信息】
iOS 原生

**Comment by iwangjiajun** [comment]
![WX20231215-160023@2x](https://github.com/Tencent/libpag/assets/3774362/007b0ee8-f108-49ce-a0c6-31e8245d917f)

**Comment by iwangjiajun** [comment]
请问pag哪个回调在子线程，我们这边处理下

**Comment by moonclock** [comment]
> 请问pag哪个回调在子线程，我们这边处理下

之前最新版本 SDK 也遇到了子线程更新崩溃问题, 回退到 4.2.100 版本, 线上崩溃已经没有了, 请排查一下最近几个版本的提交, 应该问题就在这些提交里面

**Comment by domchen** [comment]
最新的版本 4.3.43已经修复这个问题：https://github.com/Tencent/libpag/releases/tag/v4.3.43
