### ISSUE TITLE
动画卡死，报ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2

### ISSUE THREAD

**Issue by ftevxk** [Tencent/libpag#2002]
## 【版本信息】

4.3.33

## 【平台信息】

Android 原生

## 【预期的表现】
正常播放动画

## 【实际的情况】
正常播放几次动画后会偶发动画卡死

## 【Demo及附件】

![企业微信截图_20231215183405](https://github.com/Tencent/libpag/assets/9601413/fba30834-a9dd-4e11-8f40-2a3b33e0d0ae)

**Comment by domchen** [comment]
这个错误信息并不是来自PAG，检查一下系统是不是其他地方挂掉了
