### ISSUE TITLE
windows系统 使用BMP合成导出 会失败

### ISSUE THREAD

**Issue by EddieHxc** [Tencent/libpag#2025]
windows系统 AE使用BMP合成导出 会失败，没有报错码

## 【版本信息】

4.3.6 stable

## 【平台信息】

windows AE2020-2024

**Comment by EddieHxc** [comment]
![20231221-112122](https://github.com/Tencent/libpag/assets/126870582/1da49b2f-eba3-4269-8368-f988f3f3c59a)
![20231221-112132](https://github.com/Tencent/libpag/assets/126870582/f2f5ac4f-982a-42b1-8336-44d808eb849a)

**Comment by Jasper2016** [comment]
请问这个问题解决了吗，我这里也出现了。
