### ISSUE TITLE
4.3.33 iOS 使用静态库集成后，编译报错。

### ISSUE THREAD

**Issue by guochencheng41** [Tencent/libpag#2032]
## 【版本信息】

4.3.33

## 【平台信息】

 iOS 原生

## 【预期的表现】
可正常编译使用

## 【实际的情况】
编译报错，找不到 tgfx 中的函数
Undefined symbols for architecture arm64:
  "_skcms_Transform", referenced from:
      tgfx::ConvertPixels(tgfx::ImageInfo const&, void const*, tgfx::ImageInfo const&, void*) in libpag(Pixmap.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
<img width="930" alt="image" src="https://github.com/Tencent/libpag/assets/14105753/a374f5d0-a076-4789-ba5d-127074e2c57f">

## 【Demo及附件】

编译问题，无demo

**Comment by kevingpqi123** [comment]
可以升级至 4.3.43
