### ISSUE TITLE
Android realme 真我GT NEO3 机型Pag动画无法执行

### ISSUE THREAD

**Issue by tyqingfeng** [Tencent/libpag#2068]
## 【版本信息】

4.3.33

## 【平台信息】

Android 原生 
realme 真我GT NEO3 

## 【预期的表现】
Pag动画正常执行

## 【实际的情况】
Pag动画无法执行，Pag官网 git项目工程直接运行，就可以看到pag 动画无法正常执行

## 【Demo及附件】

Pag git项目工程直接运行，就可以看到pag 动画无法正常执行

**Comment by kevingpqi123** [comment]
https://github.com/Tencent/libpag/discussions/1496
可以看下这个帖子
