### ISSUE TITLE
Android  部分手机无法播放pag动效

### ISSUE THREAD

**Issue by MrHayden** [Tencent/libpag#2090]
【版本信息】
4.3.45

【平台信息】
Android 原生

【预期的表现】
正常播放pag动效

【实际的情况】

![image](https://github.com/Tencent/libpag/assets/19620807/64963089-8a69-4e64-a505-55bfc0249c22)
![image](https://github.com/Tencent/libpag/assets/19620807/8407b74c-2e60-45e3-acdc-975a667b62b7)

这个手机无法正常播放pag

【Demo及附件】
demo的使用播放视频：
https://github.com/Tencent/libpag/assets/19620807/7948e4c7-f54d-4728-a59e-1976a37375fa

资源
[skill_rank_big_animation_normal_10.zip](https://github.com/Tencent/libpag/files/13957658/skill_rank_big_animation_normal_10.zip)

**Comment by MrHayden** [comment]
这个手机通过还原手机的所有设置后能正常播放了，具体原因未知

**Comment by lewic** [comment]
我这边也遇到了有些手机pag动画无法播放问题，用官方demo一样问题，见视频：https://static0.xesimg.com/bigclass-mobile/android/other/lewic 2024-02-02 13.29.29.mp4
