### ISSUE TITLE
iOS项目报错，缺失源码文件，提示'webp/decode.h' file not found

### ISSUE THREAD

**Issue by Nanxia** [Tencent/libpag#21]

**Comment by domchen** [comment]
请参考 [README.md](https://github.com/Tencent/libpag/blob/main/README.zh_CN.md) 中的开发指南一节，正确安装第三方依赖仓库并编译就可以了。

**Comment by GarthGit** [comment]
> 请参考 [README.md](https://github.com/Tencent/libpag/blob/main/README.zh_CN.md) 中的开发指南一节，正确安装第三方依赖仓库并编译就可以了。

是不是需要  ./sync_deps.sh

**Comment by domchen** [comment]
是的

**Comment by GarthGit** [comment]
> 是的

emscripten 如果单独安装emscripten，会不会对 .sh脚本造成影响呢？

**Comment by domchen** [comment]
如果已经安装过了对应工具，确保版本是比较新的就行，脚本不会帮你重复安装，会跳过。
