### ISSUE TITLE
Crash: -[PAGNormalVideoFinishView buildViews]

### ISSUE THREAD

**Issue by make1a** [Tencent/libpag#2101]
## 【版本信息】

pod 'libpag', '4.2.88'

## 【平台信息】

 iOS 原生

## 【crash】
Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x24a20 objc_moveWeak + 244
1  CoreFoundation                 0x14c96c _CFXNotificationRegistrarAddObserver + 368
2  CoreFoundation                 0x14c790 CFXNotificationRegistrarAdd + 528
3  CoreFoundation                 0x7b660 _CFXNotificationRegisterObserver + 236
4  Foundation                     0x706c -[NSNotificationCenter addObserver:selector:name:object:] + 388
5  UIKitCore                      0xf76dec UILabelCommonInit + 100
6  UIKitCore                      0xf76c4c -[UILabel _commonInit] + 528
7  UIKitCore                      0xf76fac -[UILabel initWithFrame:] + 60
8  XXXXX               0x56adee4 -[PAGNormalVideoFinishView buildViews] + 112 (PAGVideoFinishView.m:112)
9  XXXXX               0x56ad3c4 -[PAGNormalVideoFinishView init] + 44 (PAGVideoFinishView.m:44)
10 XXXXX               0x5693f44 -[PAGVideoAdView finishVideoViewInfo] + 368 (PAGVideoAdView.m:368)
11 XXXXX               0x5693e64 -[PAGVideoAdView layoutSubviews] + 363 (PAGVideoAdView.m:363)
12 UIKitCore                      0x102f8bc -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2544
13 QuartzCore                     0x15e424 -[CALayer layoutSublayers] + 288
14 QuartzCore                     0x164bac CA::Layer::layout_if_needed(CA::Transaction*) + 544
15 UIKitCore                      0x101c9f0 -[UIView(Hierarchy) layoutBelowIfNeeded] + 524
16 UIKitCore                      0x102329c +[UIView(Animation) performWithoutAnimation:] + 96
17 UIKitCore                      0xd44d88 -[UITableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:] + 1448
18 UIKitCore                      0xd12608 -[UITableView _updateVisibleCellsNow:] + 2616
19 UIKitCore                      0xd2f898 -[UITableView layoutSubviews] + 356
20 UIKitCore                      0x102f8bc -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2544
21 QuartzCore                     0x15e424 -[CALayer layoutSublayers] + 288
22 QuartzCore                     0x164bac CA::Layer::layout_if_needed(CA::Transaction*) + 544
23 QuartzCore                     0x17016c CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 140
24 QuartzCore                     0xb8578 CA::Context::commit_transaction(CA::Transaction*, double, double*) + 500
25 QuartzCore                     0xe32c8 CA::Transaction::commit() + 668
26 QuartzCore                     0xe4530 CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*) + 92
27 CoreFoundation                 0x99540 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 32
28 CoreFoundation                 0x93b70 __CFRunLoopDoObservers + 588
29 CoreFoundation                 0x9410c __CFRunLoopRun + 1012
30 CoreFoundation                 0x937d0 CFRunLoopRunSpecific + 572
31 GraphicsServices               0x3570 GSEventRunModal + 160
32 UIKitCore                      0xb302d0 -[UIApplication _run] + 1052
33 UIKitCore                      0xb3584c UIApplicationMain + 164
34 XXXXX               0x5cf2064 main + 25 (main.m:25)

设备
型号：iPhone X
屏幕方向：纵向
可用 RAM： 125.84 MB
可用磁盘空间： 34.56 GB
操作系统
版本：14.7.1
屏幕方向：纵向
是否已越狱：否

**Comment by kevingpqi123** [comment]
PAGNormalVideoFinishView 以及 PAGVideoAdView 不是 pag 中类，应该是你们自己封装的类，上面的 crash 堆栈不涉及 pag 内部源码
