### ISSUE TITLE
插件更新后（之前是ok的），渲染动画只支持1:1，其他比例不支持，只能渲染出部分画面，且上下会有空白区域，尺寸也被强行渲染为1:1

### ISSUE THREAD

**Issue by factsdefeatwords** [Tencent/libpag#212]
<canvas class="canvas" id="pag"></canvas>
<script>
    const canvas = document.querySelector('#pag')

    const script = document.createElement('script')
    script.src = 'https://cdn.jsdelivr.net/npm/libpag@latest/lib/libpag.min.js'
    script.async = true
    script.onload = function() {
      window.libpag
      .PAGInit({})
      .then(function(PAG) {
        const url = 'https://filmora.wondershare.com/assets/animations/Home_Banner_filmora11.pag'
        fetch(url)
          .then(function(response) { return response.blob()})
          .then(function(blob) {
            const file = new window.File([blob], url.replace(/(.*\/)*([^.]+)/i, '$2'))
            PAG.PAGFile.load(file).then( pagFile => {
              console.log(pagFile.width())
              console.log(pagFile.height())
              PAG.PAGView.init(pagFile, '#pag').then(pagView => {
                pagView.setRepeatCount(0)
                pagView.play()
                canvas.parentElement.style.backgroundImage = 'none'
              })
            })
          })
      })
    }
    document.body.appendChild(script) 
</script>

渲染出来宽高是 300 * 300 ； 但实际原尺寸是 810 * 599

**Comment by zenoslin** [comment]
从代码上来看，你没有设置canvas的大小，所以300*300是canvas默认大小。

**Comment by factsdefeatwords** [comment]
> 从代码上来看，你没有设置canvas的大小，所以300*300是canvas默认大小。

我的问题不是渲染大小，而是渲染的比例，我已经打印出pagFile 的宽高，可以在控制台看到是810 和 599 ，所以我预期应该会按照 810 / 599 这个比例渲染，但目前看来是1:1，但之前这个比例是ok的

**Comment by zenoslin** [comment]
非常感谢你的反馈，我们已经定位到了问题，可以尝试使用 libpag@0.1.2-alpha.2 版本。很快我们会推送最新的NPM latest 版本。
