### ISSUE TITLE
iOS 使用PAG 存在内存泄漏，希望尽快解决，有Demo源码

### ISSUE THREAD

**Issue by jate** [Tencent/libpag#2167]
## 【版本信息】

4.3.48

## 【平台信息】

iOS 原生

## 【预期的表现】

iOS 平台使用PAG 不能内存泄漏，目前生产项目在使用，希望尽快能解决。

## 【实际的情况】

基本使用，单次播放和 循环播放都存在 内存泄漏问题。
<img width="1685" alt="截屏2024-02-29 15 49 21" src="https://github.com/Tencent/libpag/assets/3424780/c1cd47b8-bbcf-42c8-92e7-d23ebf7f6569">
<img width="1875" alt="截屏2024-02-29 15 48 19" src="https://github.com/Tencent/libpag/assets/3424780/f353ac9c-ff3d-434f-a5fe-78e31329a063">

## 【Demo及附件】
[PAGTester-源码.zip](https://github.com/Tencent/libpag/files/14444697/PAGTester-.zip)

**Comment by kevingpqi123** [comment]
感谢反馈，该问题已修复，可以升级至 4.3.49，通过 cocoapods 可以拉取到
另外，如果使用的是 PAGImageView， 建议直接直接通过 setPath 的接口而不是 setComposition
