### ISSUE TITLE
是否支持加载pag格式的网络资源, 类似于iOS的SDWebImage, 可以缓存网络资源. 

### ISSUE THREAD

**Issue by gaoyuexit** [Tencent/libpag#2189]
支持PAG格式的网络资源下载, 缓存, 播放

**Comment by kevingpqi123** [comment]
<img width="862" alt="image" src="https://github.com/Tencent/libpag/assets/16609221/aa4b187d-d70b-4b39-9c48-289fcafa8c28">
可以升级至 4.3 的最新版本

**Comment by kevingpqi123** [comment]
最新的版本是 4.3.49，可以通过 maven 或 cocoapods 拉取到

**Comment by TML007** [comment]
@kevingpqi123 请问下，已经升级到了libpag (4.3.57)，要怎么使用加载网络资源url呢
