### ISSUE TITLE
Android编译CmakeList无法找到thirty_party对应地址，是否能够编译通过？

### ISSUE THREAD

**Issue by cangwang** [Tencent/libpag#2223]
Android编译CmakeList无法找到thirty_party对应地址

[CXX1429] error when building with cmake using /Users/cangwang/StudioProjects/libpag-main/CMakeLists.txt: -- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Users/cangwang/Library/Android/sdk/ndk/19.2.5345600/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Users/cangwang/Library/Android/sdk/ndk/19.2.5345600/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring incomplete, errors occurred!
See also "/Users/cangwang/StudioProjects/libpag-main/android/libpag/.cxx/Debug/32y71a53/arm64-v8a/CMakeFiles/CMakeOutput.log".

C++ build system [configure] failed while executing:
    /Users/cangwang/Library/Android/sdk/cmake/3.22.1/bin/cmake \
      -H/Users/cangwang/StudioProjects/libpag-main \
      -DCMAKE_SYSTEM_NAME=Android \
      -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
      -DCMAKE_SYSTEM_VERSION=19 \
      -DANDROID_PLATFORM=android-19 \
      -DANDROID_ABI=arm64-v8a \
      -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \
      -DANDROID_NDK=/Users/cangwang/Library/Android/sdk/ndk/19.2.5345600 \
      -DCMAKE_ANDROID_NDK=/Users/cangwang/Library/Android/sdk/ndk/19.2.5345600 \
      -DCMAKE_TOOLCHAIN_FILE=/Users/cangwang/Library/Android/sdk/ndk/19.2.5345600/build/cmake/android.toolchain.cmake \
      -DCMAKE_MAKE_PROGRAM=/Users/cangwang/Library/Android/sdk/cmake/3.22.1/bin/ninja \
      -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/cangwang/StudioProjects/libpag-main/android/libpag/build/intermediates/cxx/Debug/32y71a53/obj/arm64-v8a \
      -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/Users/cangwang/StudioProjects/libpag-main/android/libpag/build/intermediates/cxx/Debug/32y71a53/obj/arm64-v8a \
      -DCMAKE_BUILD_TYPE=Debug \
      -B/Users/cangwang/StudioProjects/libpag-main/android/libpag/.cxx/Debug/32y71a53/arm64-v8a \
      -GNinja \
      -DANDROID_STL=c++_static \
      -DPAG_USE_LIBAVC=OFF \
      -DPAG_USE_FFAVC=ON
  from /Users/cangwang/StudioProjects/libpag-main/android/libpag
CMake Error at CMakeLists.txt:15 (include):
  include could not find requested file:

    ./third_party/vendor_tools/vendor.cmake

PAG_USE_LIBAVC: OFF
PAG_USE_RTTR: OFF
PAG_USE_HARFBUZZ: OFF
PAG_USE_C: OFF
PAG_BUILD_SHARED: ON
PAG_BUILD_FRAMEWORK: OFF
PAG_BUILD_TESTS: 
PAG_VERSION: 4.0.0
TGFX_DIR: /Users/cangwang/StudioProjects/libpag-main/third_party/tgfx
CMake Error at CMakeLists.txt:431 (add_subdirectory):
  add_subdirectory given source
  "/Users/cangwang/StudioProjects/libpag-main/third_party/tgfx" which is not
  an existing directory.

CMake Error at CMakeLists.txt:436 (add_vendor_target):
  Unknown CMake command "add_vendor_target".

**Comment by kevingpqi123** [comment]
如果你想编译源码，建议认真看开源仓库中的 ReadMe，不要省去一些步骤
<img width="896" alt="企业微信截图_34215255-250b-4675-b017-ea7ed147034c" src="https://github.com/Tencent/libpag/assets/16609221/bba2bb57-69e7-4365-9f81-7784a145fc08">
你应该少执行了这个
