### ISSUE TITLE
iOS:excluded architecture是否有移除arm64选项的计划

### ISSUE THREAD

**Issue by MrYu4** [Tencent/libpag#2238]
### Discussed in https://github.com/Tencent/libpag/discussions/2177

<div type='discussions-op-text'>

<sup>Originally posted by **MrYu4** March  6, 2024</sup>
目前库编译依然针对模拟器存在限制arm64的情况
<img width="478" alt="Snipaste_2024-03-06_14-09-44" src="https://github.com/Tencent/libpag/assets/22674880/0da9d230-3627-467f-b25e-adc24b1164fe">
但是根据苹果的[相关文档](https://developer.apple.com/documentation/technotes/tn3117-resolving-build-errors-for-apple-silicon/#Update-pre-compiled-libraries-from-vendors)，这并不是一个长久的处理办法，能否根据文章中的建议将库重建为 XCFramework，并支持 Apple 芯片上的模拟器呢？
</div>

**Comment by domchen** [comment]
关闭重复发帖。
