### ISSUE TITLE
微信安卓webview无法自动播放pag动画

### ISSUE THREAD

**Issue by AlbertEjiestein** [Tencent/libpag#2261]
微信安卓webview无法自动播放 pag 动画，通过setTimeout延迟调用play方法也不行，但是微信原生浏览器可以播放，另外微信ios webview 可以播放 pag 动画

## 【版本信息】

8.0.48

## 【平台信息】

微信 Android

## 【预期的表现】

预期加载页面后自动播放动画

## 【实际的情况】

安卓微信打开页面，无法自动播放动画

**Comment by kevingpqi123** [comment]
这里和微信相关，不是 pag 可以处理的，微信安卓webview 针对视频解码需要交互后才能触发
