### ISSUE TITLE
libpag sdk，怎么修改libpag sdk的名称、修改对外API的名称操作？

### ISSUE THREAD

**Issue by tgitpushping** [Tencent/libpag#2263]
## 【版本信息】

4.3.51版本

## 【平台信息】

iOS原生

## 【预期的表现】
理论上应该有prefix这种预编译头文件 

## 【实际的情况】
暂未看到

**Comment by kevingpqi123** [comment]
你具体遇到的问题是啥，没有类似的修改操作
