### ISSUE TITLE
4.3.51版本对比Lottie、SVGA，内存占比比较高

### ISSUE THREAD

**Issue by tgitpushping** [Tencent/libpag#2267]
## 【版本信息】

4.3.51版本

## 【平台信息】

iOS 原生 

## 【预期的表现】
对比Lottie、SVGA 预期在CPU、内存性能上比较优秀

## 【实际的情况】
实际情况：多个小图动画上，除内存、FPS较优秀外，CPU上比较啦夸

## 【Demo及附件】
<img width="1191" alt="企业微信截图_e123929c-7120-48d1-976f-6c97c78e063b" src="https://github.com/Tencent/libpag/assets/104554146/f7ea830d-b84d-4737-8034-784af074e26c">

**Comment by tgitpushping** [comment]
使用的素材都是同一个视频素材，只是不同的测试对象 后缀、格式不同而已，但从结果来看，确实pag的确是高

**Comment by kevingpqi123** [comment]
你要找纯矢量的素材测试，比如 Lottie 根本就不支持视频，视频和图片解码性能上压根就不一样
另外对比这些没有啥意义，由于实现方式的不同，不同实现方案在性能上会有些差异，但这些差异还没有影响使用和抉择的程度，首先应该看的这些解决方案能力上的差异、适用场景以及配套工具等
