### ISSUE TITLE
libpag.framework is missing its bundle executable. Please check your build settings to make sure that a bundle executable is produced at the path 

### ISSUE THREAD

**Issue by Ssunnyday** [Tencent/libpag#2269]
Xcode15.2   iOS17 使用cocoapods集成

**Comment by kevingpqi123** [comment]
信息提供不全，使用 pag 的哪个版本，复现条件是啥，建议先完善信息

**Comment by Ssunnyday** [comment]
> 信息提供不全，使用 pag 的哪个版本，复现条件是啥，真机还是模拟器，建议先完善信息

使用最新的版本4.3.51，每次真机必现，xcode15.2  xcode15.3都会

**Comment by kevingpqi123** [comment]
我这边运行没有任何问题，后续反馈问题建议把相关情况都备注清楚，具体遇到的问题是啥，复现 demo 是啥，操作步骤是啥，不然都是在浪费彼此的时间，另外 iOS 的兼容性很好，不会有你说的那些问题，和 XCode 版本没啥关系
<img width="586" alt="截屏2024-05-04 16 14 47" src="https://github.com/Tencent/libpag/assets/16609221/73c6a5a5-b421-4e9d-b18c-9b2f60980667">
<img width="561" alt="截屏2024-05-04 16 26 27" src="https://github.com/Tencent/libpag/assets/16609221/fa3c555a-672b-4f51-9181-45adebe3cde4">


你这边的报错像是 XCFramework 没有被正确拉取下来
