### ISSUE TITLE
官网下载链接失效

### ISSUE THREAD

**Issue by Jizhuaaaaaa** [Tencent/libpag#229]
#### 问题

> 请告诉我们你遇到了什么问题。预期是什么？实际表现是什么？

#### 重现

> 请说明重现步骤。加载的是什么文件，你的代码是怎么写的，等等。
> PAG 素材可以在压缩之后，随这个 Bug 上传。

#### 环境

libpag 版本：libpag-ios（v3.2.4.37），libpag-android（v3.2.5.1），PAGViewer（2.1.33 beta）  
设备：iPhone 7（iOS 12），OnePlus 7（Android 10），iMac 5K（macOS 10.15.3）

#### Demo（可选）

> 请给一个 Demo 项目，我们可以运行并重现这个问题。

#### 其他（可选）

> 如果还有其他信息可以帮助我们定位问题，请添加其他内容。

**Comment by domchen** [comment]
哪个链接？

**Comment by Jizhuaaaaaa** [comment]
> 哪个链接？

https://dldir1.qq.com/qqmi/libpag/PAGViewer.dmg

**Comment by domchen** [comment]
这个cdn不太可能会出问题，看看是不是本地配了什么host或者拦截了域名。

**Comment by Jizhuaaaaaa** [comment]
> 这个cdn可能会出问题，看看是不是本地可能配会主机或者不是域名。

发现了。。。。好像是公司it网络策略的问题。。。。。。谢谢
