### ISSUE TITLE
PAGView.flush crash

### ISSUE THREAD

**Issue by iGao101** [Tencent/libpag#2299]
## Which Version of libpag are you using?

libpag 4.2.100

## What Platform are you on? 

目前只在Android 14上出现

## Expected Behavior 
期待修复该问题

## Actual Behavior
谷歌后台崩溃信息录入，暂无法复现，但是该崩溃触发次数较多，排名靠前，期望能给下可能得原因来排查一下。

## Code Example
无

**Comment by kevingpqi123** [comment]
这个是 Android 14 ValueAnimator 内部实现变更引起的， 内部缺少了部分容错，可以升级至 4.3.56，这个版本移除了对于 ValueAnimator setCurrentPlayTime方法的调用

**Comment by iGao101** [comment]
> 这个是 Android 14 ValueAnimator 内部实现变更引起的， 内部缺少了部分容错，可以升级至 4.3.56，这个版本移除了对于 ValueAnimator setCurrentPlayTime方法的调用

好的，感谢
