### ISSUE TITLE
使用AudioTrack播放composition.audioBytes()无法正常播放

### ISSUE THREAD

**Issue by susirsusir** [Tencent/libpag#2320]
使用AudioTrack直接播放composition.audioBytes()获取到的buffer无法正常播放，只有白噪音

**Comment by kevingpqi123** [comment]
这类问题建议认真看下 API 文档：
public ByteBuffer audioBytes ()
The audio data of this composition, which is an AAC audio in an MPEG-4 container.

AudioTrack 需要的数据格式是 PCM，你需要将 audioBytes 解容器，然后解码才能获取到 PCM 数据

**Comment by susirsusir** [comment]
> 这类问题建议认真看下 API 文档： public ByteBuffer audioBytes () The audio data of this composition, which is an AAC audio in an MPEG-4 container.
> 
> AudioTrack 需要的数据格式是 PCM，你需要将 audioBytes 解容器，然后解码才能获取到 PCM 数据

有ADTS头么？
