### ISSUE TITLE
iOS端支持加载网络资源url形式的pag吗？具体怎么用呢？

### ISSUE THREAD

**Issue by TML007** [Tencent/libpag#2347]
## 【版本信息】

4.2.88

## 【平台信息】

Android 原生 | iOS 原生 | Web 浏览器 | 微信小程序 | Linux | Flutter | 其他

**Comment by kevingpqi123** [comment]
需要升级至 PAG 4.3 版本，具体可以看下 API 文档，有提供异步加载的接口
