### ISSUE TITLE
PAG so 崩溃

### ISSUE THREAD

**Issue by DXBbeginner** [Tencent/libpag#2350]
## 【版本信息】

4.3.33

## 【平台信息】

Android 原生 

## 【预期的表现】
正常运行

## 【实际的情况】
signal 11 code 1 at address 0x0
 backtrace:
#0 pc 0x1c798 /vendor/lib64/libsrv_um.so (PVRSRVDevVarGet 8)
 #1 pc 0xe312c /vendor/lib64/egl/libGLESv2_mtk.so
 #2 pc 0x53a44 /vendor/lib64/egl/libGLESv2_mtk.so
 #3 pc 0x51c00 /vendor/lib64/egl/libGLESv2_mtk.so
 #4 pc 0x33834 /vendor/lib64/egl/libGLESv2_mtk.so
#5 pc 0x333a0 /vendor/lib64/egl/libGLESv2_mtk.so (glBindFramebuffer 408)
 #6 pc 0x1c677c /data/app/com.XXX.XXXXXX-FDAK15JA70zy3NDBFw0Hjw==/lib/arm64/libpag.so
 #7 pc 0x13b9e4 /data/app/com.XXX.XXXXXX-FDAK15JA70zy3NDBFw0Hjw==/lib/arm64/libpag.so
 #8 pc 0x121960 /data/app/com.XXX.XXXXXX-FDAK15JA70zy3NDBFw0Hjw==/lib/arm64/libpag.so
 #9 pc 0x131e20 /data/app/com.XXX.XXXXXX-FDAK15JA70zy3NDBFw0Hjw==/lib/arm64/libpag.so
 #10 pc 0x11ad90 /data/app/com.XXX.XXXXXX-FDAK15JA70zy3NDBFw0Hjw==/lib/arm64/libpag.so
 #11 pc 0x142568 /data/app/com.XXX.XXXXXX-FDAK15JA70zy3NDBFw0Hjw==/lib/arm64/libpag.so
#12 pc 0xa2f58 /data/app/com.XXX.XXXXXX-FDAK15JA70zy3NDBFw0Hjw==/lib/arm64/libpag.so (pag::PAGSurface::draw(pag::RenderCache*, std::__ndk1::shared_ptr<pag::Graphic>, pag::BackendSemaphore*, boolean) 656)
#13 pc 0xa1270 /data/app/com.XXX.XXXXXX-FDAK15JA70zy3NDBFw0Hjw==/lib/arm64/libpag.so (pag::PAGPlayer::flushInternal(pag::BackendSemaphore*) 196)
#14 pc 0xa1178 /data/app/com.XXX.XXXXXX-FDAK15JA70zy3NDBFw0Hjw==/lib/arm64/libpag.so (pag::PAGPlayer::flush() 92)
#15 pc 0x10c078 /data/app/com.XXX.XXXXXX-FDAK15JA70zy3NDBFw0Hjw==/lib/arm64/libpag.so (Java_org_libpag_PAGPlayer_flushAndFenceSync 208)
 basic:
 ABI: arm64 pid: 22031  tid: 32630

有什么可行的修复方案么

**Comment by DXBbeginner** [comment]
有相关负责人跟进一下么，目前线上大部分都是vivo 8.1 系统的机型在崩

**Comment by kevingpqi123** [comment]
后续遇到此类问题先搜索 github discussion， https://github.com/Tencent/libpag/discussions/2316
