### ISSUE TITLE
鸿蒙系统兼容

### ISSUE THREAD

**Issue by JBP-1994** [Tencent/libpag#2389]
## 【版本信息】

4.2.88

## 【平台信息】

鸿蒙

## 【预期的表现】
正常播放

## 【实际的情况】
可以执行到onAnimationPlay回调，动画没显示出来，空白

**Comment by wangyatong** [comment]
兄台支持api12的libpag还没有发布呢, 等他们8月中旬发布吧

**Comment by wangyatong** [comment]
https://github.com/Tencent/libpag/discussions/2085
