### ISSUE TITLE
[split_config.arm64_v8a.apk] pag::PAGSurface::freeCache ANR

### ISSUE THREAD

**Issue by iGao101** [Tencent/libpag#2393]
## Which Version of libpag are you using?

libpag 4.3.57

## What Platform are you on? 

Android12 Android13

**Comment by iGao101** [comment]
不好意思，之前描述的内容提交之后好像找不到了。
问题：
1. 如果pagView定义在xml中，动画播放完毕之后，占用的编解码资源是否会自动释放？需不需要注意移除pagView；
2. 目前我们应用使用是代码中动态添加的，播放完毕之后手动移除掉，但是出现了PAGSurface::freeCache的anr，想问一下这样使用是否合理？如何避免出现这样的anr，还是说不应该在播放结束后移除？

**Comment by domchen** [comment]
Java对象被GC的时候都会自动释放所有资源。freeCache不是必须调用的。增加这个接口的唯一目的是在资源占用过高时提前降低压力。比如你有多个页面切换，有个PAgView已经明确要进入后台了，但是待会还会再显示出来。那么调用这个接口可以保留这个PAGView的当前画面内容前提下释放所有缓存。这样待会从后台再切换回来时也不会像重新创建的PAGView会闪一下。正常使用没必要调用。或者建议在子线程进行调用。

**Comment by iGao101** [comment]
> Java对象被GC的时候都会自动释放所有资源。freeCache不是必须调用的。增加这个接口的唯一目的是在资源占用过高时提前降低压力。比如你有多个页面切换，有个PAgView已经明确要进入后台了，但是待会还会再显示出来。那么调用这个接口可以保留这个PAGView的当前画面内容前提下释放所有缓存。这样待会从后台再切换回来时也不会像重新创建的PAGView会闪一下。正常使用没必要调用。或者建议在子线程进行调用。

1. 进入当前页面的时候pag动画会播放一次，播放结束应该是没有到gc的时机？此时pagView占用的资源会释放吗？
2. 当前页面，pag播放结束之后，不会再展示了，这种情况下要怎么处理，手动remove掉pagView，会自动触发freeCache，有可能触发anr

**Comment by domchen** [comment]
1.GC之前资源不会释放，跟随Java对象管理的。要提前释放可以调用freeCache或者更彻底的调用release方法。
2.有可能触发ANR的一般是跟视频解码器的释放有关，那部分系统对象概率性的会要耗时很久才能销毁。有效规避方法是避免PAG文件里有用到BMP预合成的图层就行，尽可能用矢量的素材。

**Comment by iceAnson** [comment]
请问如何检测一个素材有没有问题呢，目前很难规避投放的素材
