### ISSUE TITLE
org.libpag.PAGPlayer.setSurface发生native Crash

### ISSUE THREAD

**Issue by huichengtan** [Tencent/libpag#2405]
## 【版本信息】

4.1.13

## 【平台信息】

Android 原生 
## 【实际的情况】

0
SIGABRT:
1
#00 pc 00000000000191a4 /apex/com.android.runtime/lib64/bionic/libc.so (abort+164) [arm64-v8a::e2d9c5ba32145bb6e11e59494ee68593]
2
#01 pc 000000000056fd50 /apex/com.android.art/lib64/libart.so (_ZN3art7Runtime5AbortEPKc+904) [arm64-v8a::2452917c4ff69cbb6e75e5512260946b]
3
#02 pc 00000000000217d0 /apex/com.android.art/lib64/libbase.so [arm64-v8a::6f67f69ff36b970d0b831cfdab3b578d]
4
#03 pc 0000000000020d58 /apex/com.android.art/lib64/libbase.so (_ZN7android4base10LogMessageD2Ev+352) [arm64-v8a::6f67f69ff36b970d0b831cfdab3b578d]
5
#04 pc 00000000001eaa4c /apex/com.android.art/lib64/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+3540) [arm64-v8a::2452917c4ff69cbb6e75e5512260946b]
6
#05 pc 00000000004a303c /apex/com.android.art/lib64/libart.so (_ZN3art11ClassLinker30VisitClassesWithoutClassesLockEPNS_12ClassVisitorE+144) [arm64-v8a::2452917c4ff69cbb6e75e5512260946b]
7
#06 pc 00000000000e7e28 /data/app/~~VpQDh-fCJ-zPavb8IS1NZw==/com.tencent.wesing--2tiwVDhYTK3k9lOCAbcKA==/lib/arm64/libpag.so [arm64-v8a::715e90d31e137cca71dd67985a70506b] (Java_org_libpag_PAGPlayer_nativeSetSurface +52) (jni.h:709)
8
#07 pc 00000000001807e4 /data/app/~~wM-SJLz93x3BSPujLxJm8g==/com.tencent.wesing-l3DCWHgXUdo1asDVEZcovw==/oat/arm64/base.odex
9
java:
10
org.libpag.PAGPlayer.setSurface(Unknown Source:9)
11
org.libpag.PAGView.onSurfaceTextureAvailable(Unknown Source:20)
12
android.view.TextureView.getTextureLayer(TextureView.java:501)
13
android.view.TextureView.draw(TextureView.java:431)
14
android.view.View.updateDisplayListIfDirty(View.java:22848)
15
android.view.View.draw(View.java:23738)
16
android.view.ViewGroup.drawChild(ViewGroup.java:4648)
17
android.view.ViewGroup.dispatchDraw(ViewGroup.java:4409)
18
com.tencent.wesing.giftanimation.animation.resAnimation.ResAnimationView.dispatchDraw(Unknown Source:31)
19
android.view.View.updateDisplayListIfDirty(View.java:22839)
20
android.view.View.draw(View.java:23738)
21
android.view.ViewGroup.drawChild(ViewGroup.java:4648)
22
android.view.ViewGroup.dispatchDraw(ViewGroup.java:4409)
23
android.view.View.updateDisplayListIfDirty(View.java:22839)
24
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4632)
25
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4605)
26
android.view.View.updateDisplayListIfDirty(View.java:22795)
27
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4632)
28
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4605)
29
android.view.View.updateDisplayListIfDirty(View.java:22795)
30
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4632)
31
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4605)
32
android.view.View.updateDisplayListIfDirty(View.java:22795)
33
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4632)
34
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4605)
35
android.view.View.updateDisplayListIfDirty(View.java:22795)
36
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4632)
37
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4605)
38
android.view.View.updateDisplayListIfDirty(View.java:22795)
39
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4632)
40
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4605)
41
android.view.View.updateDisplayListIfDirty(View.java:22795)
42
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4632)
43
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4605)
44
android.view.View.updateDisplayListIfDirty(View.java:22795)
45
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4632)
46
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4605)
47
android.view.View.updateDisplayListIfDirty(View.java:22795)
48
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4632)
49
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4605)
50
android.view.View.updateDisplayListIfDirty(View.java:22795)
51
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4632)
52
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4605)
53
android.view.View.updateDisplayListIfDirty(View.java:22795)
54
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4632)
55
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4605)
56
android.view.View.updateDisplayListIfDirty(View.java:22795)
57
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4632)
58
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4605)
59
android.view.View.updateDisplayListIfDirty(View.java:22795)
60
android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:707)
61
android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:713)
62
android.view.ThreadedRenderer.draw(ThreadedRenderer.java:811)
63
android.view.ViewRootImpl.draw(ViewRootImpl.java:5183)
64
android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4875)
65
android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4025)
66
android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2634)
67
android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9745)
68
android.view.Choreographer$CallbackRecord.run(Choreographer.java:1478)
69
android.view.Choreographer$CallbackRecord.run(Choreographer.java:1487)
70
android.view.Choreographer.doCallbacks(Choreographer.java:1061)
71
android.view.Choreographer.doFrame(Choreographer.java:957)
72
android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1461)
73
android.os.Handler.handleCallback(Handler.java:958)
74
android.os.Handler.dispatchMessage(Handler.java:99)
75
android.os.Looper.loopOnce(Looper.java:243)
76
android.os.Looper.loop(Looper.java:338)
77
android.app.ActivityThread.main(ActivityThread.java:8399)
78
java.lang.reflect.Method.invoke(Native Method)
79
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
80
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

**Comment by domchen** [comment]
这个版本好几年前的了，已经不在维护，即使定位出问题也不会单独发版本更新，可能后续的版本也已经修复了相关问题，先升级一下最新的版本吧。
