### ISSUE TITLE
鸿蒙版pag的sdk大概什么时候有

### ISSUE THREAD

**Issue by wangjiaxi10086** [Tencent/libpag#2411]
## 【版本信息】

4.2.88

## 【平台信息】

Android 原生 | iOS 原生 | Web 浏览器 | 微信小程序 | Linux | Flutter | 其他

**Comment by kevingpqi123** [comment]
本周会发布一个 alpha 版本

**Comment by wangjiaxi10086** [comment]
好的，太给力了
感谢回答，谢谢！
