### ISSUE TITLE
HarmonyOS NEXT 系统集成SDK后编译报错

### ISSUE THREAD

**Issue by pepsikirk** [Tencent/libpag#2415]
## 【版本信息】

1.0.0

## 【平台信息】

HarmonyOS NEXT

## 【预期的表现】

可以正常编译

## 【实际的情况】

通过ohpm install @tencent/libpag添加SDK后，编译就会报错

> 08/09 15:38:28:862: Install Failed: error: failed to install bundle.
> code:9568305
> error: Failed to install the HAP or HSP because the dependent module does not exist.
> entry's dependent module: libpag does not exist.
> 08/09 15:38:28:862: View detailed instructions.
> 

## 【Demo及附件】

无

**Comment by heroszcy** [comment]
我也遇到同样的问题了，应该是编译har包出问题了吧

**Comment by Hparty** [comment]
1.0.1修复了这个问题

**Comment by pepsikirk** [comment]
> 1.0.1修复了这个问题

1.0.1确实已经可以编译成功
