### ISSUE TITLE
鸿蒙NEXT系统pag闪退

### ISSUE THREAD

**Issue by tracyis** [Tencent/libpag#2418]
## 【版本信息】

1.0.1

## 【平台信息】

HarmonyOS NEXT

## 【预期的表现】
正常显示

## 【实际的情况】
把Demo中的Index.ets作为二级页面，打开后关闭再打开大概率闪退

## 【Demo及附件】
Module name:org.libpag.PAGViewer
Version:1.0.0
VersionCode:1000000
PreInstalled:No
Foreground:Yes
Timestamp:2024-08-12 20:11:59.462
Pid:34067
Uid:20020054
Process name:org.libpag.PAGViewer
Process life time:2s
Reason:Signal:SIGSEGV(SEGV_ACCERR)@0x0000005b3bf09500 
Fault thread info:
Tid:34136, Name:ibpag.PAGViewer
#00 pc 000000000117c500 [anon:native_heap:jemalloc]
#01 pc 00000000000601a8 /system/lib64/platformsdk/libace_napi.z.so(napi_call_threadsafe_function+28)(b6e1f7201887fd380757eb122af83fe1)
#02 pc 00000000006c5f60 /data/storage/el1/bundle/libs/arm64/libpag.so(pag::JPAGView::onAnimationUpdate(pag::PAGAnimator*)+84)(1be52dbc9f3f248d9d4d813239957b33b591b4bc)
Registers:
x0:0000005b27d2eb08 x1:0000005b3e805190 x2:0000000000000000 x3:0000005b3e8051d8
x4:0000000000000000 x5:000000000000000a x6:0000005c45161f10 x7:0000005c45161f18
x8:0000005b3bf09500 x9:8651a31b9f750078 x10:0000000000000000 x11:0000005b3bfe4210
x12:0000000000000000 x13:0000005b3c007058 x14:0000005b3e617540 x15:0000000000000000
x16:0000005c44ac94d8 x17:0000005b27b6018c x18:0000000000000005 x19:0000005c45162990
x20:0000005c45162980 x21:0000000000008513 x22:0000000000000000 x23:0000005c451629c0
x24:0000005aa346c000 x25:0000005c451629a0 x26:0000005c45162990 x27:0000005c45162980
x28:0000005aa3b8a270 x29:0000005c45162630
lr:0000005b27b601ac sp:0000005c45162610 pc:0000005b3bf09500
Other thread info:
Tid:34067, Name:ibpag.PAGViewer
#00 pc 00000000001b6f40 /system/lib/ld-musl-aarch64.so.1(__timedwait_cp+192)(8a1c8fdb77a87447175a6a93ae26dea2)
#01 pc 00000000001bcf64 /system/lib/ld-musl-aarch64.so.1(__pthread_mutex_timedlock_inner+592)(8a1c8fdb77a87447175a6a93ae26dea2)
#02 pc 00000000001e1174 /system/lib/ld-musl-aarch64.so.1(PauseMainThreadHandler+76)(8a1c8fdb77a87447175a6a93ae26dea2)
#03 pc 000000000000197c shmm
#04 pc 00000000000013e8 shmm
#05 pc 00000000001bd300 /system/lib/ld-musl-aarch64.so.1(__pthread_mutex_trylock+8)(8a1c8fdb77a87447175a6a93ae26dea2)
#06 pc 00000000000f33a4 /system/lib/ld-musl-aarch64.so.1(je_tcache_bin_flush_small+384)(8a1c8fdb77a87447175a6a93ae26dea2)
#07 pc 00000000000b1ef4 /system/lib/ld-musl-aarch64.so.1(free_default+1376)(8a1c8fdb77a87447175a6a93ae26dea2)
#08 pc 0000000000147988 /system/lib64/lib2d_graphics.z.so(std::__h::allocator<OHOS::Rosen::TextEngine::FallbackGroup>::destroy[abi:v15004](OHOS::Rosen::TextEngine::FallbackGroup*)+84)(6ebba56ec6dc9b7f220e6f9de8552124)
#09 pc 0000000000147898 /system/lib64/lib2d_graphics.z.so(OHOS::Rosen::TextEngine::FontConfigJsonInfo::~FontConfigJsonInfo()+60)(6ebba56ec6dc9b7f220e6f9de8552124)
#10 pc 000000000111a270 /system/lib64/platformsdk/libace_compatible.z.so(OHOS::Rosen::TextEngine::FontConfigJson::~FontConfigJson()+236)(584ab839672b254c7f7c7c664d16c435)
#11 pc 0000000001119d70 /system/lib64/platformsdk/libace_compatible.z.so(OHOS::Ace::FontManager::GetUIFontConfig(OHOS::Ace::FontConfigJsonInfo&)+588)(584ab839672b254c7f7c7c664d16c435)
#12 pc 0000000000007b28 /system/lib64/module/libfont.z.so(OHOS::Ace::Napi::JsGetUIFontConfig(napi_env__*, napi_callback_info__*)+104)(3aba4c09300c79ccb8396625adfa6849)
#13 pc 00000000000359ac /system/lib64/platformsdk/libace_napi.z.so(panda::JSValueRef ArkNativeFunctionCallBack<true>(panda::JsiRuntimeCallInfo*)+220)(b6e1f7201887fd380757eb122af83fe1)
#14 pc 0000000000302054 /system/lib64/module/arkcompiler/stub.an(RTStub_PushCallArgsAndDispatchNative+40)
#15 at InitFontFallback (libpag/src/main/ets/PAGInit.ets:34:22)
#16 at Init (libpag/src/main/ets/PAGInit.ets:27:5)
#17 at initView (libpag/src/main/ets/PAGView.ets:196:5)
#18 at anonymous (libpag/src/main/ets/PAGView.ets:131:9)

**Comment by wangjiaxi10086** [comment]
遇到同样问题，重复点开页面播放pag或者首次点开，大概率出现这样的崩溃

**Comment by pepsikirk** [comment]
我也同样如此，大概率会崩溃

**Comment by sunflower-good-time** [comment]
我也是

**Comment by Hparty** [comment]
已经复现，正在修复中。预计下个版本会修复

**Comment by wangjiaxi10086** [comment]
下个版本预计什么时候哈

**Comment by tracyis** [comment]
> 已经复现，正在修复中。预计下个版本会修复

你好，想问下预计什么时候发鸿蒙新版本呢

**Comment by kevingpqi123** [comment]
预计今天会发布一个新版本

**Comment by kevingpqi123** [comment]
可以升级至 4.4.2

**Comment by tracyis** [comment]
> 可以升级至 4.4.2

好的，感谢❤️
