### ISSUE TITLE
setPath返回NO，加载失败，偶现的

### ISSUE THREAD

**Issue by KK177** [Tencent/libpag#2428]
## 【版本信息】

4.2.110

## 【平台信息】

iOS 原生

## 【预期的表现】
从沙盒里读取pag文件，通过setPath加载

## 【实际的情况】
发现setPath方法return的是NO，我尝试去沙盒里share出要读取的pag文件，在电脑打开是可以正常播放的，而且这个问题不是必现的

## 【Demo及附件】
if (self.pagView == nil)
        {
            PAGView *pagView = [[PAGView alloc] initWithFrame:CGRectMake(0,
                                                                     0,
                                                                     40,
                                                                     40)];
            pagView.center = CGPointMake(self.playProgressView.curProgress, CGRectGetMidY(self.playProgressView.frame));
            pagView.userInteractionEnabled = NO;
            [pagView setRepeatCount:0];
            [self addSubview:pagView];
            self.pagView = pagView;
        }
        if ([[self.pagView getPath] isEqualToString:pagFile] == NO)
        {
            if ([self.pagView setPath:pagFile] == NO)
            {
                NSLog(@"pag文件加载有问题：%@", pagFile);
            }
        }

**Comment by kevingpqi123** [comment]
这里没有什么特别的，如果设置的 path 可以获取到 pag 文件，且解码成功，setPath 返回为 true
如果文件加载这里出现问题，都是必现的，不可能是偶现的，建议多排查下业务自身传入的路径是否可以正确解码
