### ISSUE TITLE
iOS pag 卡死

### ISSUE THREAD

**Issue by asterpang** [Tencent/libpag#2435]
我们app，libpag在低端机（<iphone8)上出现很多metric watchdog卡死，非必现；
今天，在我自己一台iphone 6sp上遇到一例卡死，具体堆栈信息看附件
[libpag-lock-thread.log](https://github.com/user-attachments/files/16686116/libpag-lock-thread.log)

## 【版本信息】

4.2.110

## 【平台信息】

 iOS 原生 

## 【Demo及附件】

目前未定位到相关联的pag素材，demo无法稳定复现

**Comment by asterpang** [comment]
补充另外一个堆栈
<img width="871" alt="image" src="https://github.com/user-attachments/assets/7b53e92e-46a8-4139-a3be-0cf05f9d1ccc">

**Comment by kevingpqi123** [comment]
分析 crash 不要孤立的看单个线程，通过堆栈可以看到主线程 PAGView 正在被移除掉。对于 pag 而言，内部是线程安全的，即不同线程执行 PAGPlayer 的方法内部会存在锁等待，如果当前 PAGView 正在销毁，如果正在执行 flush 方法，需要等待 flush 方法执行完才能执行其它操作（渲染的 suface 是主线程提供的，渲染中直接销毁可能会导致 crash）

再具体到当前堆栈，主要出现在中低端机型，对于 pag 的方法，相对耗时的是 flush方法，该方法执行渲染操作，一般情况下执行会在 几 ms 到几十 ms 不等，和素材的复杂度强相关，出现 ANR 的时候，当前手机的资源可能出现了不足的情况，导致 flush 方法执行耗时过长，从而出现等待

问题的规避建议：
1）排查出现 ANR 的场景的手机资源消耗情况，看能否在这个层面做一些优化，避免资源不足时导致 pag 的 flush 的方法执行耗时过长；
2）优化 pag 素材：pag 渲染是 flush 方法的耗时和素材的复杂度强相关，在中低端机型上，尽量使用纯矢量的素材，避免使用含有 BMP 预合成的素材（这类素材相当于含有视频序列，视频解码相当耗资源）

**Comment by asterpang** [comment]
CFURLCreateStringByAddingPercentEscapes instead?
