### ISSUE TITLE
HarmonyOS NEXT 系统 4.4.2版本 设置 repeatCount 无效，还是只播放一次

### ISSUE THREAD

**Issue by pepsikirk** [Tencent/libpag#2436]
## 【版本信息】

4.4.2

## 【平台信息】

HarmonyOS NEXT

## 【预期的表现】
设置repeatCount后可以按设置播放对应次数

## 【实际的情况】
设置repeatCount后无效，还是只播放一次

## 【Demo及附件】
无

**Comment by wangjiaxi10086** [comment]
发现超过100kb的pag动画，设置无限播放就只播放一次，一次播放后就报如下log，请分析下原因～
E   (native_avbuffer.cpp, 146): magic error!
E     ImageDecoderTask::onMakeResource() Failed to decode the image!

**Comment by Hparty** [comment]
如果可以，建议把出问题的pag文件发一下

**Comment by wangjiaxi10086** [comment]
好的哈，附件如下：
[PAG问题汇总.zip](https://github.com/user-attachments/files/16703124/PAG.zip)
1、ble_key_init.pag-----无法循环播放
2、vehicle_atomic_loading_p.pag------一次播放都不行
3、atomic_seat_vent.pag--------一闪而过

文件已上传～

**Comment by kevingpqi123** [comment]
4.4.4 版本已修复该问题
