### ISSUE TITLE
缺少C++ pag so库

### ISSUE THREAD

**Issue by Yang-Libing** [Tencent/libpag#2439]
## 【版本信息】

4.2.88

## 【平台信息】

Android 原生 | iOS 原生 | Web 浏览器 | 微信小程序 | Linux | Flutter | 其他

## 【Demo及附件】
![Uploading image.png…]()

**Comment by kevingpqi123** [comment]
提供的信息不全

**Comment by Yang-Libing** [comment]
您好，我已收到您的邮件。-----自动回复
