### ISSUE TITLE
HarmonyOS NEXT 系统 4.4.2版本 个别PAG不能正常展示

### ISSUE THREAD

**Issue by 810wu** [Tencent/libpag#2440]
[
[img_loading_car_3d.pag.zip](https://github.com/user-attachments/files/16720951/img_loading_car_3d.pag.zip)

## 【版本信息】

4.4.2

## 【平台信息】

DevEco Studio NEXT Developer Beta3

**Comment by kevingpqi123** [comment]
可以升级至 4.4.4 版本
