### ISSUE TITLE
使用PAGImageView时出现ANR

### ISSUE THREAD

**Issue by afra0823** [Tencent/libpag#2450]
org.libpag.PAGImageView
ANR Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago. waitqueue length = 2, head.seq = 64951, Wait queue head age: 6087.8ms.)

org.libpag.PAGImageView in $r8$lambda$i9qNusto1bUthfs1SXZYFuASnA4
org.libpag.PAGImageView in setComposition

## 【版本信息】

4.3.33

## 【平台信息】

Android 原生 

## 【预期的表现】
动画正常展示

## 【实际的情况】
使用setComposition或首次初始化PAGImageView时均会出现ANR

## 【Demo及附件】

**Comment by kevingpqi123** [comment]
看下这个帖子 https://github.com/Tencent/libpag/issues/2435
