### ISSUE TITLE
HarmonyOS NEXT 系统 4.4.4版本,请问当前pag sdk支持网络加载吗

### ISSUE THREAD

**Issue by wangjiaxi10086** [Tencent/libpag#2451]
## 【版本信息】

4.4.4

## 【平台信息】

HarmonyOS NEXT

## 【预期的表现】
期望支持网络加载

**Comment by kevingpqi123** [comment]
4.4.5 版本已支持

**Comment by OvenCroc** [comment]
大佬们网络图片应该怎么使用呢 直接PAGFile.LoadFromPath('pag网络地址') 这样吗?
