### ISSUE TITLE
PAGImageView播放失败，Failed to write frame to SequenceFile

### ISSUE THREAD

**Issue by Wangsisi23** [Tencent/libpag#2468]
## 【版本信息】

4.3.57

## 【平台信息】

Android 原生

## 【预期的表现】
两个PAGImageView使用同一个pag文件，播放其中一个view时能够正常播放pag动效

## 【实际的情况】
两个PAGImageView使用同一个pag文件，播放其中一个view时偶现动效无法播放的问题；非必现

## 【Demo及附件】
【使用方法】

private var mLoadingView1: PAGImageView
private var mLoadingView2: PAGImageView

private fun initViews() {
    mLoadingView1?.setRepeatCount(-1)
    mLoadingView1?.setCacheAllFramesInMemory(false)
    mLoadingView2?.setRepeatCount(-1)
    mLoadingView2?.setCacheAllFramesInMemory(false)

    val composition = PAGFile.Load(resources.getAssets(), "pag/loading.pag");
    mLoadingView1?.pause()
    mLoadingView1?.composition = composition
    mLoadingView2?.pause()
    mLoadingView2?.composition = composition
}

private fun startPlay1() {
    mLoadingView1?.visibility = View.VISIBLE
    mLoadingView1?.play()
    mLoadingView2?.visibility = View.GONE
    mLoadingView2?.pause()
}

private fun startPlay2() {
    mLoadingView1?.visibility = View.GONE
    mLoadingView1?.pause()
    mLoadingView2?.visibility = View.VISIBLE
    mLoadingView2?.play()
}

【报错信息】

09-12 15:47:00.148092  2198 12282 E tgfx    : SequenceFile::writeFrame() failed to write the compressed frame to disk
09-12 15:47:00.148187  2198 12282 E tgfx    : PAGDecoder::readFrame() Failed to write frame to SequenceFile!
09-12 15:47:00.148617  2198 12283 E tgfx    : SequenceFile::writeFrame() failed to write the compressed frame to disk
09-12 15:47:00.148663  2198 12283 E tgfx    : PAGDecoder::readFrame() Failed to write frame to SequenceFile!

**Comment by kevingpqi123** [comment]
1、渲染的过程中 PAGFile 是会携带一些播放进度信息在里面的，同一个 PAGComposition 对象不能共用于多个 PAGView 或 PAGImageView
2、PAGImageView 不建议使用 setComposition 的方式，具体看下官方文档：
https://pag.io/docs/use-pagimageview.html
3、如果你这边切换播放两个 pag 文件，看下这个帖子
https://github.com/Tencent/libpag/discussions/2453

**Comment by Wangsisi23** [comment]
> 1、渲染的过程中 PAGFile 是会携带一些播放进度信息在里面的，同一个 PAGComposition 对象不能共用于多个 PAGView 或 PAGImageView 2、PAGImageView 不建议使用 setComposition 的方式，具体看下官方文档： https://pag.io/docs/use-pagimageview.html 3、如果你这边切换播放两个 pag 文件，看下这个帖子 #2453

好的多谢啦，我们调整下使用方式试一下
