### ISSUE TITLE
replacement.pag Latest version of iOS library

### ISSUE THREAD

**Issue by zhigang1992** [Tencent/libpag#249]
## Which Version of libpag are you using?

libpag 3.2.7.44

## What Platform are you on? 

iOS 15

## Expected Behavior 
<img width="526" alt="image" src="https://user-images.githubusercontent.com/1057756/161560010-49a30dfa-e0c8-47d9-98a2-619c54987e3a.png">

## Actual Behavior
<img width="530" alt="image" src="https://user-images.githubusercontent.com/1057756/161560058-ea5f0763-a7ca-4818-b273-4ace0f5dac85.png">

## Code Example

https://github.com/libpag/pag-ios
With the only change of bump this library to latest version

## PAG File
`replacement.pag` included in the sample repo

[replacement.pag.zip](https://github.com/Tencent/libpag/files/8410293/replacement.pag.zip)

**Comment by domchen** [comment]
这是M1模拟器的问题，不是框架有什么问题。M1模拟器在iOS 14开始绘制OpenGL内容会有bug，模板器的系统回退到13.7及以下就行。建议还在真机上进行调试。
