### ISSUE TITLE
libpag鸿蒙库,在5.0.3.810 DevEco Studio版本上作为依赖引入,必现引入编译失败

### ISSUE THREAD

**Issue by Yang-Libing** [Tencent/libpag#2492]
## 【版本信息】

4.4.4;4.4.5;4.4.8均存在该问题

## 【平台信息】

鸿蒙5.0.3.810 DevEco Studio

## 【预期的表现】

在项目中引入鸿蒙libpag库使用

## 【实际的情况】

libpag鸿蒙库,在5.0.3.810 DevEco Studio版本上作为依赖引入,必现引入编译失败.报错信息如下:
<img width="748" alt="810报错" src="https://github.com/user-attachments/assets/113e1ab8-076c-4740-ba38-b4447431eeda">

目前定位到问题出在这里:
<img width="485" alt="定位点" src="https://github.com/user-attachments/assets/f2cde3f8-42fc-4edb-bff0-2e36596c27a7">
通过把Index.js删除,把Index.d.ets改为Index.ets,并且再按下图修改:
<img width="933" alt="修改方式" src="https://github.com/user-attachments/assets/0ec220b8-501a-49c3-8385-46826c415075">
之后能正常运行.

可能新的IDE版本做了一些规则加强,所以之前的IDE版本引入libpag没事,810 IDE版本就不行了.
麻烦看看怎么改下提供个新包呢

## 【Demo及附件】

快速复现的简易demo如下:
[TestLibPagIn810IDE.zip](https://github.com/user-attachments/files/17111564/TestLibPagIn810IDE.zip)

**Comment by Yang-Libing** [comment]
您好，我已收到您的邮件。-----自动回复

**Comment by Yang-Libing** [comment]
这个有排期后面在远程鸿蒙库里修改吗,在自己项目中一直通过本地依赖har的方式还是不够好,希望还是远程依赖的方式

**Comment by Yang-Libing** [comment]
这个本地编包无法远程依赖了,而且每次你们代码更新后,我都要编个包来更新,不太合理,也不规范,请问有针对最新鸿蒙IDE做编译报错的修复的排期吗

**Comment by kevingpqi123** [comment]
4.4.9 版本已规避该问题，具体 IDE 的问题鸿蒙正在修复中
