### ISSUE TITLE
AE 启动时提示 Couldn't find main entry point for PAGExporter.plugin (48::72)

### ISSUE THREAD

**Issue by yarkey09** [Tencent/libpag#25]
![image](https://user-images.githubusercontent.com/7758864/149491839-b46cc595-d55f-45bc-bae5-0906cd020eb2.png)

环境：
macOS Catalina 版本 10.15.7
Adobe After Effects 版本 22.1.1 (Build 74)
PAGViewer 2.1.92.360 (beta)

**Comment by domchen** [comment]
通常是因为更新了AE 出现这个问题。麻烦尝试一下这几个步骤：1.参考这个文档：https://pag.io/docs/beta.html  开启一下 PAGViewer的 beta模式，更新到最新的beta版本。2.在 PAGViewer 的菜单里点击一下 安装AE插件 选项重新安装插件。
如果操作后问题依然存在，请加入 QQ 群893379574，我们会有同学专门跟你对接排查问题。

**Comment by domchen** [comment]
这个bug已经确认并在修复中，可以先通过手动重新安装AE插件解决，等正式发布修复的版本后关闭这个 issue。

**Comment by kataCai** [comment]
麻烦遇到这个问题的同学，更新 PAGViewer 到 2.1.94.5 或者以上版本。并在退出 AE 的情况下，重新安装 AE 插件。
