### ISSUE TITLE
鸿蒙端pag sdk, PAGFile replaceText时, 数字及一些特殊字符文案替换后出现样式发生不合预期的变化

### ISSUE THREAD

**Issue by Yang-Libing** [Tencent/libpag#2514]
## 【版本信息】

v4.4.4

## 【平台信息】

鸿蒙平台

## 【预期的表现】

<img width="909" alt="image" src="https://github.com/user-attachments/assets/dcc3a855-98db-4b8d-994a-6751ad3bd9b9">

如上图所示,调用PAGFile的replaceText方法替换文本文案,只替换文字内容,文字的格式,位置等信息均不修改.预期的样式类似于下图所示:

<img width="690" alt="image" src="https://github.com/user-attachments/assets/1dedbffd-5507-49a4-89bb-58fcdb908734">

## 【实际的情况】

实际替换效果如下:
<img width="478" alt="image" src="https://github.com/user-attachments/assets/81499b93-743e-4724-a063-4cf534f681f7">

可以看到,中文文案内容和展示样式符合预期,但数字的颜色和字体发生了变化(而替换text时并未修改文案的展示样式).
经测试,还有一些其他的特殊字符,如‘#’等也会出现类似样式变化的问题.
这个问题在鸿蒙测试机上测试必现,应该可以快速复现(用数字测试replaceText),辛苦看下是什么原因.

**Comment by Yang-Libing** [comment]
这里快一个月了,请问是否有人在跟进呢? 这个问题是另一个业务方接入这个鸿蒙版libpag后测试反馈的,到时候快上线时还没解决会阻塞发版

**Comment by LYongLiang** [comment]
一摸一样的问题，数字展示的特别分散，并且颜色发生了变化。什么时间可以修复一下呢？

**Comment by joun233** [comment]
[补充pag 文件](https://video-pay-page-1258344701.shiply-cdn.qq.com/reshub/qqvideo/vip_pay_unlock_ticket/20231207113257/production/vip_pay_unlock_ticket.zip)

**Comment by Hparty** [comment]
已经验证，具体是因为文本使用了“苹方”字体，触发鸿蒙字体回退逻辑，同时优先使用了鸿蒙的"emoji"字体导致。
周内libpag会更新新版本修复这类问题，具体libpag对应修复pr为：https://github.com/Tencent/libpag/pull/2564。如果需要紧急上线，可以在AE制作pag文件时使用非“苹方”字体。

**Comment by domchen** [comment]
fixed in #2564
