### ISSUE TITLE
在鸿蒙环境下，使用new NavPathStack()路由跳转，返回时pag卡顿

### ISSUE THREAD

**Issue by xiaolieask** [Tencent/libpag#2587]
在鸿蒙环境下，使用new NavPathStack()路由跳转，返回时pag卡顿
暂停播放后操作正常

## 【版本信息】

4.4.12

## 【平台信息】

 Flutter | ohos

## 【预期的表现】
[]

## 【Demo及附件】

https://gitee.com/asklie/pag-demo

**Comment by Hparty** [comment]
demo内部没有对应pag，如果可以建议把对应pag放在demo中。
看demo像是通过flutter调用pag的，建议可以通过pag自带PAGView播放试试

**Comment by Hparty** [comment]
Flutter相关的问题建议提到：https://github.com/libpag/pag-flutter 中，这边目前是另外的一个团队在维护。

**Comment by xiaolieask** [comment]
close
