### ISSUE TITLE
iOS 18 Crash：set maskview to nil before adding it as a subview of

### ISSUE THREAD

**Issue by Arwen7777** [Tencent/libpag#2591]
## Which Version of libpag are you using?

libpag 4.3.33

## What Platform are you on? 

iOS 18.1

![image](https://github.com/user-attachments/assets/bab6ab6b-be1d-4d48-bb9c-5fdf7978e19e)
![image](https://github.com/user-attachments/assets/1477e321-ce20-470b-ad00-35de43249c0c)

**Comment by domchen** [comment]
这个报错的全都是你们自己的业务代码，没有pag的内容。
