### ISSUE TITLE
建议在微信小程序中内置

### ISSUE THREAD

**Issue by PonyCui** [Tencent/libpag#26]
非常感谢 pag 团队分享这么棒的开源项目，建议 pag 团队可以考虑添加微信小程序支持。
微信小程序目前已经支持 wasm 的引入和执行，也支持 W3C 标准的 Canvas 2D WebGL API，在技术上应该没什么障碍。
对于 wasm 包大小等问题，目前看在 br 压缩后大约占 500K，可以考虑作为微信小程序内置库引入，避免增加小程序的包大小，这需要与微信团队合作推进。

**Comment by domchen** [comment]
首先感谢 Pony 对 PAG 的肯定，我们其实去年有在推动微信小程序植入的事情，微信已经内置了C++版本的PAG库，如果小程序能绑定接口暴露出来，从性能和体验上肯定是最好的方式，会比wasm的还更好不少。这从技术方案上都是行得通的，但这又并不单纯的一个技术问题。小程序作为一个开放平台也有他们的公平性考虑，目前只愿意暴露在行业里足够普及的方案。我们当时还没开源，只以在公司内的影响力不足以推动作为标准接口暴露出来的这个形式。这也算是导致 PAG 正式开始推动对外开源的一个触发点吧。目前 PAG 正在适配小程序，第一步起码先让用户可以基于 wasm 方案在小程序用起来，逐渐有更多 PAG 在小程序应用场景出来，再去推动微信内置可能会更加容易被平台接受。另外可能跟认知不太相符的点是，在这件事的推动上，其实外部用户的真实诉求和发声反而是比我们内部团队的说服力大很多的，我们也在努力推动这个事情，但眼下可能是扎实的服务好行业里的用户群体，这个才更容易实现。
