### ISSUE TITLE
react下PAGInit()报错

### ISSUE THREAD

**Issue by AaronW-BE** [Tencent/libpag#261]
报错内容如下：
```
libpag.js:398 Uncaught (in promise) RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0). Build with -s ASSERTIONS=1 for more info.
    at abort (libpag.js:398:1)
    at libpag.js:465:1
```

**Comment by AaronW-BE** [comment]
> 该报错为wasm文件加载错误，建议查看示例demo。https://github.com/libpag/pag-web

感谢回答，已手动加载wasm文件，可正常播放PAG文件

**Comment by songxiaoliang** [comment]
@AaronW-BE 请问是怎么解决的，遇到同样的 问题

**Comment by zenoslin** [comment]
@songxiaoliang 参考demo项目，主要是webpack需要打包wasm文件

**Comment by MyButifullyLife** [comment]
> @AaronW-BE 请问是怎么解决的，遇到同样的 问题

#312 这里

**Comment by AaronW-BE** [comment]
> @AaronW-BE 请问是怎么解决的，遇到同样的 问题

手动加载wasm文件即可使用 @MyButifullyLife @songxiaoliang

**Comment by 1ds6f1afd** [comment]
react已经添加了config-overrides.js 还是报RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0). Build with -s ASSERTIONS=1 for more info.

**Comment by zenoslin** [comment]
@1ds6f1afd 是否参考 https://github.com/libpag/pag-web/tree/main/react 中进行配置，可以观察 DevTools 中 Network 标签中加载 libpag.wasm 文件的 URL，确认网络加载成功

**Comment by 1ds6f1afd** [comment]
@zenoslin  libpag.wasm  加载成功  但是没有加载需要的pag文件  是参考 https://github.com/libpag/pag-web/tree/main/react 中进行配置

**Comment by 1ds6f1afd** [comment]
只有放在App.js页面才有效果其它页面都没有效果

**Comment by zenoslin** [comment]
@1ds6f1afd 加载你需要的pag文件，用 HTTP 请求获取 ArrayBuffer 或者 blob 就可以了，跟请求一个文件的逻辑是一样的，跟在哪个页面应该是没有关系的

**Comment by 1ds6f1afd** [comment]
其它页面所有文件都加载成功 就是不播放动画

**Comment by zenoslin** [comment]
@1ds6f1afd 可以提供一个在线demo或者demo包，给我调试看看吗
或者加入我们的Q群893379574与我联系

**Comment by 1ds6f1afd** [comment]
已加群提问
