### ISSUE TITLE
使用bitmap填充图层宽度展示问题

### ISSUE THREAD

**Issue by fanyafeng** [Tencent/libpag#2624]
## 【版本信息】

4.3.68

## 【平台信息】

Android compose调用，将其封装为androidview

## 【预期的表现】
我有带有一个图层的PAG，这个PAG是个全屏的动效，在动效之前需要截取当前屏幕，截取的当前屏幕的bitmap作为替换图层的bitmap，动效从上到下滑动的过程中会漏出下面真实的页面，实际打印了屏幕宽高和截取的bitmap宽高是完全符合的，但是使用后上下能对其，左右没有对其，填充模式为scaleMode = PAGScaleMode.Stretch，附件中有两个视频以及使用的PAG文件，一个有问题的视频一个无问题的视频
下面是两个录屏，上面是正常的，下面是有问题的，暂时已知有问题的机型：华为Pure70 pro，华为nova 12i
视频见附件

## 【Demo及附件】

[附件.zip](https://github.com/user-attachments/files/18151989/default.zip)

**Comment by kevingpqi123** [comment]
没太明白你的问题是啥，反馈的问题的时候建议先将清楚你这边要实现的功能是啥，怎么实现的，哪里不符合预期，并通过截图或语言描述具体不符合预期的地方，上述问题讲清楚了如果你们实现不太简洁的地方我们也可以帮你们指出，现在不太清楚你们遇到的问题是啥，具体是实现层面的问题还是 pag 的问题无法判断

**Comment by fanyafeng** [comment]
无问题手机正常录屏：

https://github.com/user-attachments/assets/ebcb4831-4c51-46e7-9045-ff59299a3492


有问题手机录屏：

https://github.com/user-attachments/assets/61332835-60de-4067-99f3-bb4154981235

**Comment by fanyafeng** [comment]
> 没太明白你的问题是啥，反馈的问题的时候建议先描述清楚你这边要实现的功能是啥，怎么实现的，哪里不符合预期，并通过截图或语言描述具体不符合预期的地方，上述问题讲清楚了如果你们实现不太简洁的地方我们也可以帮你们指出，现在不太清楚你们遇到的问题是啥，具体是实现层面的问题还是 pag 的问题无法判断

关了吧，换了另一种模式可以了

**Comment by laohezi** [comment]
Hello,@fanyafeng ,方便简单贴一下在compose 中使用的代码吗？ 我在compose 中使用没办法显示

**Comment by fanyafeng** [comment]
> Hello,[@fanyafeng](https://github.com/fanyafeng) ,方便简单贴一下在compose 中使用的代码吗？ 我在compose 中使用没办法显示

`
data class PAGReplaceItem(val count: Int, val bitmap: Bitmap)

@Composable
fun PAGViewCommonUI(
    modifier: Modifier = Modifier,
    manager: AssetManager? = LocalContext.current.assets,
    pagFile: PAGFile? =null,
    pagPath: String?= null,
    repeatCount: Int = 1,
    scaleMode: Int = PAGScaleMode.LetterBox,
    @DrawableRes placeholder: Int = 0,
    playEvent: Int = PAGPlayEVent.EVENT_PLAY,
    pagReplaceList: List<PAGReplaceItem>? = null,
    onAnimationStart: (() -> Unit)? = null,
    onAnimationRepeat: (() -> Unit)? = null,
    onAnimationEnd: (() -> Unit)? = null,
    onAnimationCancel: (() -> Unit)? = null,
    onAnimationUpdate: ((process: Float) -> Unit)? = null,
) : PAGPlayController{
    val context = LocalContext.current

    val controller = remember { PAGPlayController(context) }

    //当播放进度回调大于0时为true
    var realPlay by remember { mutableStateOf(false) }

    // 通过 produceState 确保资源只加载一次
    val loadState = produceState(initialValue = false, pagPath ?: pagFile) {
      val controllerNew =  if (pagPath == null) controller.load(pagFile) else controller.load(manager, pagPath)
        controllerNew.apply {
            if (!pagReplaceList.isNullOrEmpty()) {
                pagReplaceList.forEach { item ->
                    replace(item.count, item.bitmap)
                }
            }
        }.setRepeatCount(repeatCount).addListener(object : SimplePAGViewListener() {
            override fun onAnimationStart(p0: PAGView?) {
                super.onAnimationStart(p0)
                onAnimationStart?.invoke()
            }

            override fun onAnimationRepeat(p0: PAGView?) {
                super.onAnimationRepeat(p0)
                onAnimationRepeat?.invoke()
            }

            override fun onAnimationEnd(p0: PAGView?) {
                super.onAnimationEnd(p0)
                onAnimationEnd?.invoke()
            }

            override fun onAnimationUpdate(p0: PAGView?) {
                super.onAnimationUpdate(p0)
                if ((p0?.progress ?: 0.0) > 0.0) {
                    realPlay = true
                }
                onAnimationUpdate?.invoke(p0?.progress?.toFloat() ?: 0f)
            }

            override fun onAnimationCancel(p0: PAGView?) {
                super.onAnimationCancel(p0)
                onAnimationCancel?.invoke()
            }

        })

        //如果没有placeholder并且不是播放状态，默认在第一帧
        if (placeholder == 0 && playEvent == PAGPlayEVent.EVENT_PREPARE_NOT_PLAY) {
            delay(25)
            controller.setProgress(0.0)
        }
        value = true
    }


    LaunchedEffect(key1 = playEvent, key2 = loadState.value) {
        if (!loadState.value) return@LaunchedEffect
        when (playEvent) {
            PAGPlayEVent.EVENT_PLAY -> {
                controller.play()
            }

            PAGPlayEVent.EVENT_STOP -> {
                if (controller.isPlaying()) {
                    controller.stop()
                }
            }

            PAGPlayEVent.EVENT_PAUSE -> {
                if (controller.isPlaying()) {
                    controller.pause()
                }
            }

            PAGPlayEVent.EVENT_RESUME -> {
                controller.resume()
            }
        }
    }

    DisposableEffect(Unit) {
        onDispose {
            controller.stop()
            controller.release()
        }
    }

    if (placeholder != 0 && !realPlay) {
        Image(painter = painterResource(id = placeholder), contentDescription = "", modifier = modifier)
    }

    AndroidView(modifier = modifier, factory = {
        controller.getView()?.apply {
            setScaleMode(scaleMode)
        } ?: View(context)
    })

    return controller
}


fun loadPAGFile(manager: AssetManager?, resourcePath: String): PAGFile?{
    return try {
        if (manager != null) PAGFile.Load(manager, resourcePath) else PAGFile.Load(resourcePath)
    } catch (e: Exception) {
        null
    }
}

`
