### ISSUE TITLE
Web 端调用 PAGImage.fromSource，如果image.src是dataurl的时候，无法工作

### ISSUE THREAD

**Issue by alsotang** [Tencent/libpag#274]
### Bug 描述

Web 端调用 PAGImage.fromSource，如果image.src是dataurl的时候，无法工作

#### 问题

预期：image.src 为 dataurl 和 普通http url 时，均能正常工作。
实际表现：只有普通http url能工作。

#### 环境

npm libpag: 0.1.6
Chrome: 版本 100.0.4896.127（正式版本） (x86_64)
os: macos 12.3.1

**Comment by zenoslin** [comment]
我这边测试了 libpag@0.1.6 版本发现dataurl的imageElement是可以正常使用的。
这个是测试demo：https://codesandbox.io/s/dataurl-image-replace-ju6uix

**Comment by alsotang** [comment]
我的锅，我这边实现的错误在于，忘记监听 `HTMLImageElement.onload` ，我没想到 src 是 dataURL的情况下也需要监听。

**Comment by Changdao** [comment]
在Safari下还是出错。
