### ISSUE TITLE
PagView在页面跳转后，返回回来后不显示；

### ISSUE THREAD

**Issue by ihesen** [Tencent/libpag#276]
### Bug 描述
PagView在页面跳转后，返回回来后不显示；

#### 问题
我用了一台华为手机和一台华为matepad pro设备，使用pag版本v3.2.4.45，android系统10，我在AActivity中两处使用PAG一次是在LinearLayout动态添加PagView后只播放一次动画，另一处使用地方是在xml中直接使用PagView，默认不播放，只有在触发事件的时候播放一次。在进入AActivity后首次两处都没有问题能够正常显示，但是在AActivity跳转到BActivity后，在回来AActivity后PagView就不显示了。发现按home后回来PagView能够正常显示。

**Comment by kevingpqi123** [comment]
3.2.4.45版本有点老，建议升级至3.2.7.45，如果还存在该问题，建议基于官方Demo工程构造出你这边的使用场景并附上，我们来分析

**Comment by ihesen** [comment]
抱歉在问题描述的时候写错了版本。用的pag版本是最新版本v3.2.7.45。今天尝试写了demo，不知道是介于demo工程功能过于简单的情况还是什么原因，在demo中没有复现出来，真实项目中在android10上复现概率很高，几乎每次可以复现。相同的代码在android11设备上没有出现过。目前不确定是什么原因导致，自己也还在跟进这个问题，不知道其他人有没有遇到这样的问题。

**Comment by kevingpqi123** [comment]
可以从下面两个方面尝试下：
（1）更新下libpag的版本，看是哪个版本引起的，下面是pag的版本列表：
https://github.com/Tencent/libpag/releases
如果定位出是从哪个版本开始的，也有助于分析问题
（2）还是基于demo复现问题，重点还原你这边前后台切换、页面返回这些场景

**Comment by IMBV001** [comment]
我这边也是使用 3.2.7.45 也有一样的问题。

**Comment by kevingpqi123** [comment]
如果可以复现，建议提供下demo工程，我们来分析

**Comment by luojt** [comment]
我也遇到了这个问题，回到有pag的页面有概率显示不出来

**Comment by kevingpqi123** [comment]
麻烦大家提供下复现场景及demo，有场景我们才好去分析问题
我们这边也同步验证下

**Comment by luojt** [comment]
在源代码上发现锁屏和解锁屏幕控制pagview是否显示的逻辑
`@Override
    public void onScreenOff() {
        if (this.getVisibility() == View.VISIBLE) {
            this.mSaveVisibleState = true;
            // workaround 在有些手机上，如果不置成不可见，解锁以后画面会不可见
            // 在VIVO IQOO Pro表现为必现的不可见，在一加6t上表现为偶现不可见
            setVisibility(View.INVISIBLE);
        }
    }

    @Override
    public void onScreenOn() {
        if (this.mSaveVisibleState) {
            this.setVisibility(View.VISIBLE);
        }
        this.mSaveVisibleState = false;
    }`
我认为可以在调用pagview动画的界面放以下代码临时解决
` override fun onResume() {
        super.onResume()
        mViewBind.pagView.visibility = View.VISIBLE
    }`

**Comment by ThinkAgains** [comment]
同问，锁屏或跳转有一定概率会出现不显示问题

**Comment by kevingpqi123** [comment]
我们在4.0版本里面完善这部分逻辑，建议升级到4.0版本，版本号：4.0.5.5

**Comment by domchen** [comment]
最新的 https://github.com/Tencent/libpag/releases/tag/v3.2.7.49 版本已经修复了此问题。
