### ISSUE TITLE
官网首页有个链接 404 

### ISSUE THREAD

**Issue by xiaohp** [Tencent/libpag#284]
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/23056320/164700740-1f5ded45-43bc-487a-ba7a-da54dd573ef4.png">

<img width="916" alt="image" src="https://user-images.githubusercontent.com/23056320/164700765-8053f53d-9fa8-41bc-bcd7-fce49cbdaed2.png">

https://pag.io/docs/pag-depth-3.html

**Comment by kevingpqi123** [comment]
多谢反馈，该问题已修复
