### ISSUE TITLE
Uncaught (in promise) RuntimeError: memory access out of bounds

### ISSUE THREAD

**Issue by FFFangYu** [Tencent/libpag#285]
#### 问题

> 
<img width="820" alt="image" src="https://user-images.githubusercontent.com/46952655/164702203-e3661545-01b4-4d73-a08f-e98a83fe142b.png">

#### 重现

> web端接入vue+vite
在html中script引入js。其他步骤和官方例子一样。之前都是好的，但是今天突然就报错了

**Comment by zenoslin** [comment]
非常感谢反馈，请把版本回退锁定到0.1.6使用

**Comment by FFFangYu** [comment]
<script src="https://unpkg.com/libpag@latest/lib/libpag.min.js"></script>
这个是加载最新的  固定版本的写法是？
