### ISSUE TITLE
web版本的libpag 手机端浏览器兼容性好吗 

### ISSUE THREAD

**Issue by a6965921** [Tencent/libpag#29]
web版本的libpag 手机端浏览器兼容性好吗   我用的是bmp预合成生成的pag文件

**Comment by zenoslin** [comment]
你好，现在的 PAG Web 的版本为 Alpha 版本，移动端的兼容性测试还在进行中。等兼容性测试完，bmp预合成的功能是能有一个很好的支持。
非常感谢你的提问。
