### ISSUE TITLE
pag-web 在ios15.x 中出现动画 卡顿

### ISSUE THREAD

**Issue by FFFangYu** [Tencent/libpag#306]
#### 问题

> pag-web的使用 在ios15.x 中出现动画 卡顿

#### 重现

> 可使用pag-web的demo进行复现。vue3+vite。没有使用模块引入，直接在html中script引入
> 刚开始用四个动画一起展示 ，第一个动画卡顿十分明显，猜测是不是动画开多了。后面只用第一个动画，但还是有卡顿。
附上动画：
shakeUrl: 'https://file.c-ctrip.com/files/6/portal/0AS56120009ewalve3723.pag',
greetUrl: 'https://file.c-ctrip.com/files/6/portal/0AS3b120009ewab6585EA.pag',
 jumpUrl : 'https://file.c-ctrip.com/files/6/portal/0AS49120009ewaluh1481.pag',
roateUrl: 'https://file.c-ctrip.com/files/6/portal/0AS4m120009ewaluuC835.pag',

#### 环境
版本：  <script src="https://unpkg.com/libpag@0.1.6/lib/libpag.min.js"></script>
设备：模拟器 iPhone 12 pro（iOS 15.14

#### 其他（可选）

> 附件
[4个.zip](https://github.com/Tencent/libpag/files/8579203/4.zip)
[1个.zip](https://github.com/Tencent/libpag/files/8579204/1.zip)

**Comment by zenoslin** [comment]
@FFFangYu 因为PAG Web版是单线程，所以不建议在移动端同屏加载多个PAG动画。
移动端中同屏多个动画播放，确实存在卡顿感，这个会在后续版本中持续优化。
对于单个PAG动画，我进行了测试，在 iPhone 11 iOS 15.4.1上并无卡顿感。
如果还有更多疑问，欢迎加入Q群893379574继续交流。
非常感谢你的反馈！

**Comment by FFFangYu** [comment]
那如果我需要做几个动画的切换，应该怎么实现比较好。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tencent/libpag"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月7日(星期六) 下午4:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Tencent/libpag] pag-web 在ios15.x 中出现动画 卡顿 (Issue #306)





 
@FFFangYu 因为PAG Web版是单线程，所以不建议在移动端同屏加载多个PAG动画。
 移动端中同屏多个动画播放，确实存在卡顿感，这个会在后续版本中持续优化。
 对于单个PAG动画，我进行了测试，在 iPhone 11 iOS 15.4.1上并无卡顿感。
 如果还有更多疑问，欢迎加入Q群893379574继续交流。
 非常感谢你的反馈！

**Comment by domchen** [comment]
@FFFangYu 我看了你的视频，你是在模拟器上测试的吗？请看一下FAQ：https://pag.io/docs/faq.html 模拟器不是真实用户环境，测试性能请在真机上运行，不然得不到任何有意义的测试数据。模拟器缺少GPU环境，性能本来就很差，只是保障基本的预览。

**Comment by domchen** [comment]
请在真机上测试一下是否还卡顿，如果还有疑问或者咨询素材优化建议欢迎在QQ群进行提问。这里主要记录Bug性质的问题。我先关闭了这个issue。
