### ISSUE TITLE
Aborted(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0). Build with -s ASSERTIONS=1 for more info

### ISSUE THREAD

**Issue by MyButifullyLife** [Tencent/libpag#312]
vue 使用 $ npm i libpag

import { PAGInit } from "libpag";

PAGInit({
  locateFile: (file) => "./node_modules/libpag/lib/" + file,
}).then((PAG) => {
  // Do Something.
});

报以下错误

Uncaught (in promise) RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0). Build with -s ASSERTIONS=1 for more info.
    at abort (libpag.umd.js?4b2e:2358:1)
    at eval (libpag.umd.js?4b2e:2423:1)

![image](https://user-images.githubusercontent.com/16436933/166660560-fc038399-1807-4edd-a4fe-e46f3d982d53.png)

**Comment by zenoslin** [comment]
Vue工程引入的话，可以参考demo[pag-web](https://github.com/libpag/pag-web)工程下的Vue目录，配置好Webpack。

**Comment by MyButifullyLife** [comment]
我运行了你们的pag-web的项目，一样的问题。  
你说的webpack配置要配置什么？

**Comment by zenoslin** [comment]
需要配置webpack将wasm文件引入到工程目录中，确保网络加载能够正常加载到wasm文件

**Comment by MyButifullyLife** [comment]
> 需要配置webpack将wasm文件引入到工程目录中，确保网络加载能够正常加载到wasm文件

怎么配，没找到配置的方案，你们的工程里面也没见有配的。  可否给一个解决方案

**Comment by MyButifullyLife** [comment]
> 需要配置webpack将wasm文件引入到工程目录中，确保网络加载能够正常加载到wasm文件

几个前端同事一样运行不了，感觉这个问题在vue上几乎必出现。 应该重视起来哥们

**Comment by zenoslin** [comment]
在[pag-web](https://github.com/libpag/pag-web)示例项目下，vue/vue2/vue.config.js和vue/vue3/vite.config.js分别写了webpack和rollup的打包配置。请细心查示例 demo，感谢你对PAG的支持

**Comment by MyButifullyLife** [comment]
> 在[pag-web](https://github.com/libpag/pag-web)示例项目下，vue/vue2/vue.config.js和vue/vue3/vite.config.js分别写了webpack和rollup的打包配置。请细心查示例 demo，感谢你对PAG的支持

别阴阳怪气，我就是运行你们的demo报的错。 能不能检查一下自己的demo？ 
npm install
npm run serve
报错  ！！！！！！

**Comment by zenoslin** [comment]
可以 `git pull` [pag-web](https://github.com/libpag/pag-web) 的代码重新尝试。之前 vue 的 示例 demo 中，有一个素材资源跨域报错。
Webpack对于 wasm 文件的打包配置是没有错误的，可以将vue.config.js的配置同步配置到业务项目中运行。

**Comment by MyButifullyLife** [comment]
> 可以 `git pull` [pag-web](https://github.com/libpag/pag-web) 的代码重新尝试。之前 vue 的 示例 demo 中，有一个素材资源跨域报错。 Webpack对于 wasm 文件的打包配置是没有错误的，可以将vue.config.js的配置同步配置到业务项目中运行。

https://unpkg.com/libpag@latest/lib/libpag.min.js

这个地址的代码拉下来放在本地引入，报的一样错误。

**Comment by MyButifullyLife** [comment]
> 可以 `git pull` [pag-web](https://github.com/libpag/pag-web) 的代码重新尝试。之前 vue 的 示例 demo 中，有一个素材资源跨域报错。 Webpack对于 wasm 文件的打包配置是没有错误的，可以将vue.config.js的配置同步配置到业务项目中运行。

还是报错，兄弟。  不是资源问题，我有本地pag资源

**Comment by zenoslin** [comment]
https://unpkg.com/libpag@latest/lib/libpag.min.js 需要依赖于 https://unpkg.com/libpag@latest/lib/libpag.wasm
如果需要把SDK下载到本地或者存放到CDN上，需要同步libpag.wasm文件也下载下来。

**Comment by MyButifullyLife** [comment]
> https://unpkg.com/libpag@latest/lib/libpag.min.js 需要依赖于 https://unpkg.com/libpag@latest/lib/libpag.wasm 如果需要把SDK下载到本地或者存放到CDN上，需要同步libpag.wasm文件也下载下来。

看着没问题了。

**Comment by domchen** [comment]
> > 在[pag-web](https://github.com/libpag/pag-web)示例项目下，vue/vue2/vue.config.js和vue/vue3/vite.config.js分别写了webpack和rollup的打包配置。请细心查示例 demo，感谢你对PAG的支持
> 
> 别阴阳怪气，我就是运行你们的demo报的错。 能不能检查一下自己的demo？ npm install npm run serve 报错 ！！！！！！

@MyButifullyLife 我们理解你着急解决问题的心情，很高兴你的问题已经得到了解决，但也希望你下次能尽量友善地提问，大家一起维护好技术社区的氛围。PAG是一个跨平台的动画渲染方案，涉及的平台非常之多，在SDK维护上需要有一个清晰的边界，否则团队精力上也不允许。严格意义上说你提的这个问题并不在我们对接的范围内，就像我们不会额外教iOS开发者如何使用cocoapods这种包管理工具一样，默认大家已经具有平台相关的常用开发技能，对于这块我们没法大量去覆盖或教学，在可能的范围内我们会尽可能指出一些关键字或者方向，但PAG以外的通用知识还是需要大家自行去学习掌握。我们核心还是聚焦在解决PAG SDK本身的问题上。

**Comment by MyButifullyLife** [comment]
> > > 在[pag-web](https://github.com/libpag/pag-web)示例项目下，vue/vue2/vue.config.js和vue/vue3/vite.config.js分别写了webpack和rollup的打包配置。请细心查示例 demo，感谢你对PAG的支持
> > 
> > 
> > 别阴阳怪气，我就是运行你们的demo报的错。 能不能检查一下自己的demo？ npm install npm run serve 报错 ！！！！！！
> 
> @MyButifullyLife 我们理解你着急解决问题的心情，很高兴你的问题已经得到了解决，但也希望你下次能尽量友善地提问，大家一起维护好技术社区的氛围。PAG是一个跨平台的动画渲染方案，涉及的平台非常之多，在SDK维护上需要有一个清晰的边界，否则团队精力上也不允许。严格意义上说你提的这个问题并不在我们对接的范围内，就像我们不会额外教iOS开发者如何使用cocoapods这种包管理工具一样，默认大家已经具有平台相关的常用开发技能，对于这块我们没法大量去覆盖或教学，在可能的范围内我们会尽可能指出一些关键字或者方向，但PAG以外的通用知识还是需要大家自行去学习掌握。我们核心还是聚焦在解决PAG SDK本身的问题上。

阴阳怪气， 是demo出了问题，我来提问题还错了？
你理解事情起因没有？

**Comment by MyButifullyLife** [comment]
> > > 在[pag-web](https://github.com/libpag/pag-web)示例项目下，vue/vue2/vue.config.js和vue/vue3/vite.config.js分别写了webpack和rollup的打包配置。请细心查示例 demo，感谢你对PAG的支持
> > 
> > 
> > 别阴阳怪气，我就是运行你们的demo报的错。 能不能检查一下自己的demo？ npm install npm run serve 报错 ！！！！！！
> 
> @MyButifullyLife 我们理解你着急解决问题的心情，很高兴你的问题已经得到了解决，但也希望你下次能尽量友善地提问，大家一起维护好技术社区的氛围。PAG是一个跨平台的动画渲染方案，涉及的平台非常之多，在SDK维护上需要有一个清晰的边界，否则团队精力上也不允许。严格意义上说你提的这个问题并不在我们对接的范围内，就像我们不会额外教iOS开发者如何使用cocoapods这种包管理工具一样，默认大家已经具有平台相关的常用开发技能，对于这块我们没法大量去覆盖或教学，在可能的范围内我们会尽可能指出一些关键字或者方向，但PAG以外的通用知识还是需要大家自行去学习掌握。我们核心还是聚焦在解决PAG SDK本身的问题上。

你们腾讯对外宣传的demo运行起来都是报错的话，别人怎么看待你们的技术？
还阴阳怪气的说通用知识。
提出问题让你们解决是为你们的门面好， 你可以继续保持原来问题不解决也可以，既然你说了没义务
