### ISSUE TITLE
web 版本通过 pixi.js 的 pagResource 接入执行时序问题

### ISSUE THREAD

**Issue by ringcrl** [Tencent/libpag#326]
#### 问题

pagResource 接入的时候，当前表现是 pagResource.ts 的 upload 方法依赖 `pagPlayer.flush()` 的异步执行，实际上当前 render 后并没有能拿到正确的画面，而需要`第二次render`，会造成非帧精确的render结果

期望结果是和 pixi.js 表现一致在调用 `app.renderer.render(app.stage)` 后能展现最新画面

#### 重现

1、基于`https://github.com/Tencent/libpag`最新代码添加同步方法 flushSync，并构建新的 wasm，在 https://github.com/libpag/pag-web 项目中使用这个 wasm
![image](https://user-images.githubusercontent.com/16740021/167796872-5f4ed2fd-3a46-45bb-9f9f-4666b290dfbe.png)

2、基于 `https://github.com/libpag/pag-web/blob/main/pixijs/src/main.ts` 修改，禁用掉自动刷新，手动触发 render
![image](https://user-images.githubusercontent.com/16740021/167797130-4b14f6bd-390a-4cea-a118-43eb548780ed.png)

3、基于 `https://github.com/libpag/pag-web/blob/main/pixijs/src/PAGResource.ts` 修改，upload 方法使用 flushSync 同步刷新方法
![image](https://user-images.githubusercontent.com/16740021/167797641-e9d6f1bc-d20b-45de-aa1b-b85fbe13f93a.png)

预期结果能够渲染符合时序的结果，而不是需要二次 `app.renderer.render(app.stage)` 才能显示出来对应内容

![image](https://user-images.githubusercontent.com/16740021/167798079-0ef9e173-8a14-4c17-b41e-ab10314c4ebe.png)

![image](https://user-images.githubusercontent.com/16740021/167798153-79ce3957-2bfb-47cf-a68d-4ae26355ca13.png)

**Comment by zenoslin** [comment]
感谢你的反馈，对于你的疑问我来做一些解答。

1. 对于 PAG 的 `flush` 函数是无法做到同步的。因为 PAG 进行 `flush` 的过程会因为素材的改变而发生变化，在存在视频序列帧、图片解码等情况下，wasm 会通过 JS 对 Web DOM 进行调度，从而实现解码的能力，而这个过程会因为通讯而带来异步副作用。所以上文提到的 `flushSync` 是错误的写法，当出现异步副作用时，`flush` 返回的是一个 `Promise` 而非 `Boolean`。
2. 在 [pag-web](https://github.com/libpag/pag-web) 的 pixijs/src/PAGResource.ts 中，使用二次 `update` 来实现首帧画面上屏时有意而为之。基于以上第1点以及在不修改 PixiJS 的 `autoStart` （其他业务需要这个默认开启的 `autoStart` 选项）的前提下，`Resource` 在实例化的时候会调用 `upload` 来进行首帧渲染，而在 PixiJS 中 `upload` 钩子返回值是 `Boolean`，无法接收一个 `Promise` ，所以只能开始 `flush` 时返回 `false`，在 `flush` 完成后调用 `update` 再次触发 `upload` 返回 `true` 来实现功能。

PixiJS 并不是我们专注的点，PixiJS 的 Demo 也是给用户提出建议后在业务上验证收集而来的。如果有更好的 Demo 示例，欢迎向 [pag-web](https://github.com/libpag/pag-web) 提交PR。

**Comment by ringcrl** [comment]
> 感谢你的反馈，对于你的疑问我来做一些解答。
> 
> 1. 对于 PAG 的 `flush` 函数是无法做到同步的。因为 PAG 进行 `flush` 的过程会因为素材的改变而发生变化，在存在视频序列帧、图片解码等情况下，wasm 会通过 JS 对 Web DOM 进行调度，从而实现解码的能力，而这个过程会因为通讯而带来异步副作用。所以上文提到的 `flushSync` 是错误的写法，当出现异步副作用时，`flush` 返回的是一个 `Promise` 而非 `Boolean`。
> 2. 在 [pag-web](https://github.com/libpag/pag-web) 的 pixijs/src/PAGResource.ts 中，使用二次 `update` 来实现首帧画面上屏时有意而为之。基于以上第1点以及在不修改 PixiJS 的 `autoStart` （其他业务需要这个默认开启的 `autoStart` 选项）的前提下，`Resource` 在实例化的时候会调用 `upload` 来进行首帧渲染，而在 PixiJS 中 `upload` 钩子返回值是 `Boolean`，无法接收一个 `Promise` ，所以只能开始 `flush` 时返回 `false`，在 `flush` 完成后调用 `update` 再次触发 `upload` 返回 `true` 来实现功能。
> 
> PixiJS 并不是我们专注的点，PixiJS 的 Demo 也是给用户提出建议后在业务上验证收集而来的。如果有更好的 Demo 示例，欢迎向 [pag-web](https://github.com/libpag/pag-web) 提交PR。

感谢分析~
