### ISSUE TITLE
动画内有办法全屏

### ISSUE THREAD

**Issue by 935155084** [Tencent/libpag#329]
使用com.tencent.tav:libpag:4.0.5.5版本，动画效果在大屏幕手机上没有办法全屏，代码已经设置了全屏，实际效果仍然为固定大小
mPagView.setLayoutParams(new RelativeLayout.LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT));

**Comment by kevingpqi123** [comment]
看下这篇文章：https://pag.io/docs/pag-fillmode.html
当pag文件尺寸和PAGView尺寸不一致时，会应用填充模式，PAGView有一个setScaleMode的方法，如果上述四种填充模式不满足需求时，支持setMatrix
