### ISSUE TITLE
web端使用libpag的时候，经常会出现Error: The play() request was interrupted by a call to pause()的报错

### ISSUE THREAD

**Issue by OYJ-Yvonne** [Tencent/libpag#337]
#### 问题

> web端使用libpag的时候渲染pag特效时，经常会出现Error: The play() request was interrupted by a call to pause().的报错
实际表现见下图
<img width="562" alt="image" src="https://user-images.githubusercontent.com/39328005/169036069-7cd59e05-b47f-4f3a-b2e0-65e0ccc33c62.png">

#### 重现

> 请说明重现步骤。加载的是什么文件，你的代码是怎么写的，等等。
使用的是正常的pag文件例如：https://gametalktest-1258344700.cos.ap-shanghai.myqcloud.com/public/09a914e88d7d86f2ecbcac1cd8954576.pag
代码文件是参照了libpag web api写的
<img width="873" alt="image" src="https://user-images.githubusercontent.com/39328005/169037254-3072113f-05f2-4fbf-ac35-a9bff2624948.png">

#### 环境

libpag 版本：https://unpkg.com/libpag@latest/lib/libpag.min.js
设备：macOS 10.15.7

**Comment by zenoslin** [comment]
收到你的反馈，已经在 debug 修复中，有进度会在这个 issue 中进行同步。感谢你的支持

**Comment by zenoslin** [comment]
@OYJ-Yvonne 你好，我观察到你粘贴打代码截图中，是把替换视频的逻辑封装成一个函数，不知道是否是在重复调用这个方法出现的。
能否加入 QQ群：893379574 协助一起复现和解决这个问题。

**Comment by zenoslin** [comment]
@OYJ-Yvonne 由于长时间没有回复，我先将这个issue关闭。
如果后续还出现这个问题，欢迎重新提issue或者加入QQ群反馈，协助我们一起复现并解决问题。
感谢你对PAG的支持！
