### ISSUE TITLE
能增加androidx camera 录制libpag视频的demo吗？

### ISSUE THREAD

**Issue by onexuan** [Tencent/libpag#35]
能增加androidx camera 录制libpag视频的demo吗？
毕竟camera特效用得比较多

**Comment by domchen** [comment]
这些是更大的音视频编辑拍摄范畴的问题，PAG只是处理动画渲染的方案，负责画到纹理上这个跟opengl交互的操作已经有demo了。camera只是输入源的区别，跟视频解码完的渲染流程是一样的，你可以搜索一下简单的camera加opengl特效的demo，这块只要搞明白了，结合导出视频的demo看就很容易用起来了。如果对opengl知识一点没有了解，基本也很难开发音视频相关的需求的，拍摄相关的问题建议谷歌一下有大量教程。
