### ISSUE TITLE
描边粗细和 AE 中表现不一致

### ISSUE THREAD

**Issue by Nobit93** [Tencent/libpag#358]
#### 问题

描边粗细和 AE 中表现不一致

#### 重现

在 AE 中设置的描边宽度是 10，在 PAG Viewer 中看到的动画明显比 AE 里的细。
![image](https://user-images.githubusercontent.com/22189438/171585244-f84479dc-e20e-4de8-b90b-74e427db5fe1.png)
![image](https://user-images.githubusercontent.com/22189438/171585466-c5effb68-22f5-4361-9a6c-d188ab5852ae.png)

#### 其他（可选）

[pag_stroke_test.aep.zip](https://github.com/Tencent/libpag/files/8821996/pag_stroke_test.aep.zip)

**Comment by FusionXu** [comment]
<img width="641" alt="企业微信截图_0814b800-63f5-4a31-be5b-9736907a6fc8" src="https://user-images.githubusercontent.com/4111863/171589479-932d8a18-a315-42c6-b795-8c9eaa6e048f.png">

目前可以通过把scale的值放在外部Transform里来规避这个问题，我们这边会继续修复这个问题
