### ISSUE TITLE
iOS通过pod 'libpag'的方式接入报错'tgfx/gpu/Window.h' file not found

### ISSUE THREAD

**Issue by shoguncao** [Tencent/libpag#365]
### Bug 描述
iOS通过pod 'libpag'的方式接入报错，报了一堆'tgfx/gpu/Window.h' file not found等错误

#### 重现
通过cocoaPods方式接入：
 pod 'libpag', :git => 'https://github.com/Tencent/libpag.git', :tag => 'v4.0.5.11'
[Build target libpag_2022-06-09T11-12-38.txt](https://github.com/Tencent/libpag/files/8866491/Build.target.libpag_2022-06-09T11-12-38.txt)
<img width="1598" alt="截屏2022-06-09 11 12 49" src="https://user-images.githubusercontent.com/1991364/172756628-ba85df8d-78ab-4731-9985-5df1bb34c2d3.png">

**Comment by domchen** [comment]
你好，libpag不是一个纯ios库项目，依赖了大量第三方编译工具和环境，目前不支持以git地址方式在cocopods引用，请参考接入文档直接用cocopods官方源方式引用，或者下载预编译的库使用。
