### ISSUE TITLE
Web 端预览 PAG 文件卡顿

### ISSUE THREAD

**Issue by MickeyMiao7** [Tencent/libpag#404]
### Bug 描述

Web 端预览 PAG 文件，动画非常卡；同样的动画文件用 Mac 的 PAG 播放器播放非常流畅

#### 问题

> 动画卡顿

#### 重现

> https://pag.io/player.html 上上传文件

> 文件：https://github.com/libpag/libpag.github.io/blob/master/demos/web/assets/particle_video.pag

#### 环境

Web

**Comment by zenoslin** [comment]
你好，方便提供一下你的机器平台吗？我在我的机器上用这个文件测试，fps是能保持在60。

**Comment by MickeyMiao7** [comment]
> 你好，方便提供一下你的机器平台吗？我在我的机器上用这个文件测试，fps是能保持在60。

MacBook Pro (15-inch, 2018)，浏览器是 102.0.5005.115（正式版本） (x86_64)  

奇怪，我试了几个 pag 文件，帧率都非常低

**Comment by domchen** [comment]
看看有没可能是浏览器手动关闭了视频硬件解码支持？

**Comment by zenoslin** [comment]
可以尝试在Chrome浏览器中访问 chrome://gpu/ ，查看 Video Decode 是否为 Hardware accelerated 状态。

**Comment by MickeyMiao7** [comment]
> 看看有没可能是浏览器手动关闭了视频硬件解码支持？

看了一下，Chrome 设置里是已经开了的

![image](https://user-images.githubusercontent.com/13026247/177238562-acb96567-5696-4ccd-98db-f111347fd1c1.png)

比如用这个资源试试? 

[test.pag.zip](https://github.com/Tencent/libpag/files/9042854/test.pag.zip)

**Comment by zenoslin** [comment]
> > 看看有没可能是浏览器手动关闭了视频硬件解码支持？
> 
> 看了一下，Chrome 设置里是已经开了的
> 
> ![image](https://user-images.githubusercontent.com/13026247/177238562-acb96567-5696-4ccd-98db-f111347fd1c1.png)
> 
> 比如用这个资源试试?
> 
> [test.pag.zip](https://github.com/Tencent/libpag/files/9042854/test.pag.zip)

这个资源是一个矢量+位图的资源，卡顿情况确实存在这个需要 debug 优化一下。但是与上文提到的 particle_video.pag 卡顿情况不是一个原因，particle_video.pag 是一个纯 bmp 序列帧素材，播放卡顿与否主要影响因素是浏览器的视频解码速度。

**Comment by MickeyMiao7** [comment]
> > > 看看有没可能是浏览器手动关闭了视频硬件解码支持？
> > 
> > 
> > 看了一下，Chrome 设置里是已经开了的
> > ![image](https://user-images.githubusercontent.com/13026247/177238562-acb96567-5696-4ccd-98db-f111347fd1c1.png)
> > 比如用这个资源试试?
> > [test.pag.zip](https://github.com/Tencent/libpag/files/9042854/test.pag.zip)
> 
> 这个资源是一个矢量+位图的资源，卡顿情况确实存在这个需要 debug 优化一下。但是与上文提到的 particle_video.pag 卡顿情况不是一个原因，particle_video.pag 是一个纯 bmp 序列帧素材，播放卡顿与否主要影响因素是浏览器的视频解码速度。

OK，我重新看了一下，particle_video 帧率基本正常的,我之前 issue 描述里贴错资源链接了，应该是这个 https://github.com/libpag/libpag.github.io/blob/master/demos/web/assets/like.pag  这个也是矢量+位图资源？

**Comment by zenoslin** [comment]
> > > > 看看有没可能是浏览器手动关闭了视频硬件解码支持？
> > > 
> > > 
> > > 看了一下，Chrome 设置里是已经开了的
> > > ![image](https://user-images.githubusercontent.com/13026247/177238562-acb96567-5696-4ccd-98db-f111347fd1c1.png)
> > > 比如用这个资源试试?
> > > [test.pag.zip](https://github.com/Tencent/libpag/files/9042854/test.pag.zip)
> > 
> > 
> > 这个资源是一个矢量+位图的资源，卡顿情况确实存在这个需要 debug 优化一下。但是与上文提到的 particle_video.pag 卡顿情况不是一个原因，particle_video.pag 是一个纯 bmp 序列帧素材，播放卡顿与否主要影响因素是浏览器的视频解码速度。
> 
> OK，我重新看了一下，particle_video 帧率基本正常的,我之前 issue 描述里贴错资源链接了，应该是这个 https://github.com/libpag/libpag.github.io/blob/master/demos/web/assets/like.pag 这个也是矢量+位图资源？

非常感谢你的反馈，因为预览页面会以一个非常大的尺寸打开矢量素材，这对GPU渲染造成了负担，恰巧我们的feature中优化了这一点。现在【在线预览】页面已经更新了feature优化，可以再体验一下。

**Comment by MickeyMiao7** [comment]
x

> > > > > 看看有没可能是浏览器手动关闭了视频硬件解码支持？
> > > > 
> > > > 
> > > > 看了一下，Chrome 设置里是已经开了的
> > > > ![image](https://user-images.githubusercontent.com/13026247/177238562-acb96567-5696-4ccd-98db-f111347fd1c1.png)
> > > > 比如用这个资源试试?
> > > > [test.pag.zip](https://github.com/Tencent/libpag/files/9042854/test.pag.zip)
> > > 
> > > 
> > > 这个资源是一个矢量+位图的资源，卡顿情况确实存在这个需要 debug 优化一下。但是与上文提到的 particle_video.pag 卡顿情况不是一个原因，particle_video.pag 是一个纯 bmp 序列帧素材，播放卡顿与否主要影响因素是浏览器的视频解码速度。
> > 
> > 
> > OK，我重新看了一下，particle_video 帧率基本正常的,我之前 issue 描述里贴错资源链接了，应该是这个 https://github.com/libpag/libpag.github.io/blob/master/demos/web/assets/like.pag 这个也是矢量+位图资源？
> 
> 非常感谢你的反馈，因为预览页面会以一个非常大的尺寸打开矢量素材，这对GPU渲染造成了负担，恰巧我们的feature中优化了这一点。现在【在线预览】页面已经更新了feature优化，可以再体验一下。

现在正常了~
