### ISSUE TITLE
关于Pag在长列表下的使用问题

### ISSUE THREAD

**Issue by githublsy** [Tencent/libpag#420]
#### 问题

> 请告诉我们你遇到了什么问题。预期是什么？实际表现是什么？

遇到了什么问题 ：我们在类似于QQ的聊天列表的场景下，每个cell都加入了一个PagView,结果cpu和内存的持续占用都非常高，设置为循环播放[setRepeatCount:0]的情况下，app的内存还会不断上涨。 
预期是什么：能不能和apng格式文件一样， 加载完后不会持续占用cpu？是我们使用方式有误，  还是说pag暂时不适用与长列表的场景？ 谢谢

#### 环境

libpag 版本：libpag-ios（v3.2.7.45
设备：Android，iPhone

**Comment by kevingpqi123** [comment]
我们也在考虑增加一个接口，可以缓存所有的渲染纹理，下次播放只需要加载缓存纹理就可以，这种情况下第二次播放 CPU 不会连续占用但内存会增加一些，适用于pag 文件帧数较少的场景。
建议提供一个 demo ，我们分析下你这边的场景，具体需求可以通过 QQ联系我：670623291

**Comment by kevingpqi123** [comment]
经讨论，排期增加一个接口，可以缓存所有的渲染纹理，下次播放只需要加载缓存纹理就可以
