### ISSUE TITLE
npm 包  libpag@4.0.5-release.18  版本的声明文件路径写错，导致 typescript 编译报错

### ISSUE THREAD

**Issue by wsp971** [Tencent/libpag#425]
### Bug 描述

npm 包  libpag@4.0.5-release.18  版本的声明文件路径写错，导致编译报错，查看package.json 的 typing 属性值为`types/src/pag.d.ts`, 实际路径应该为 `types/pag.d.ts`

#### 问题

 npm 安装 libpag  latest 版本  libpag@4.0.5-release.18 ts 环境报找不到类型声明文件，报错如下图：

![image](https://user-images.githubusercontent.com/9082502/179342979-f0e42efa-5418-4c73-bfe5-537a7a617e3f.png)

>  

#### 重现

``` sh

mkdir  pag-test
cd pag-test
npm init -y
npm install libpag
npx tsc --init
echo "import { PAGInit} from 'libpag';  \n\r PAGInit()" > index.ts
npx tsc

```

#### 环境

npm libpag@4.0.5-release.18 

#### Demo（可选）

> 请给一个 Demo 项目，我们可以运行并重现这个问题。

#### 其他（可选）

> 如果还有其他信息可以帮助我们定位问题，请添加其他内容。

**Comment by zenoslin** [comment]
感谢您的反馈，这个错误已经在[#417](https://github.com/Tencent/libpag/pull/417)中修复，会在下个版本发出。
