### ISSUE TITLE
素材迁移PAGConvertor linux版本图片图层转换失败

### ISSUE THREAD

**Issue by yukio5470** [Tencent/libpag#430]
### Bug 描述
Could not find codec parameters for stream 0 (Video: png, none(pc)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Assertion desc failed at libswscale/swscale_internal.h:677
#### 问题
使用PAGConvertor迁移存量素材中，linux版本不支持图片图层转换。相同的素材在mac版本中是可以支持的
#### 重现
1、lottie存量脱敏素材随副本上传
2、mac成功转换版本上传
3、linux版本失败
#### 环境
PAGConvertor版本：官网版本
设备：mac(12.3.1)  linux(Linux version 4.19.95-27 )
#### Demo（可选）
[convert.zip](https://github.com/Tencent/libpag/files/9138958/convert.zip)
#### 其他（可选）

> 如果还有其他信息可以帮助我们定位问题，请添加其他内容。

**Comment by Hparty** [comment]
It is currently suspected to be a problem with the decoder and is trying to solve it

**Comment by yukio5470** [comment]
> 

好的，期待解决

**Comment by Hparty** [comment]
ok，已经修复了。可以直接用这个版本测试一下，后续我们也会更新到官网上
[linux.zip](https://github.com/Tencent/libpag/files/9179155/linux.zip)
