### ISSUE TITLE
多个动画同时播放是，会出现动画卡住的

### ISSUE THREAD

**Issue by yz-qc** [Tencent/libpag#435]
#### 问题

> 在预研做了一个根据下拉选择播放不同动画的功能，允许同时播放。但是出现如：有动画在播放的时候，多次下拉选择不同的动画同时播放， 有几率所有动画会卡住不动的问题。请务必多次选择下拉框播放动画，必现的问题

#### 重现

>  [重现的demo：](https://sr.xy556.com/upload/pag动画demo.rar)

**Comment by zenoslin** [comment]
切换动画时，建议将之前的动画销毁或者暂停。因为JS时单线程的，所以多个同时渲染会出现抢占线程的情况。如果需要同屏显示多个PAG，建议使用组合的方式用一个PAGView进行播放。

**Comment by backrunner** [comment]
> 切换动画时，建议将之前的动画销毁或者暂停。因为JS时单线程的，所以多个同时渲染会出现抢占线程的情况。如果需要同屏显示多个PAG，建议使用组合的方式用一个PAGView进行播放。

最近也遇到了这个问题，尝试使用了Composition，但是发现有的能力（比如repeatCount）还是只能在PAGView的层级上去控制，相较于拆分成多个PAGView播放更没有那么独立、灵活。另外组装Composition本身也相对于创建多个canvas用css调整位置、大小甚至添加一些其他简单的进出场来说更耗时耗力，这里有没有更优的解法呢？
