### ISSUE TITLE
使用PAGConvertor-Linux将lottie json转换为pag出错

### ISSUE THREAD

**Issue by rebornfz** [Tencent/libpag#464]
#### 问题

使用PAGConvertor-Linux将lottie json转换为pag出错，得到的pag文件所有的layername为空
![image](https://user-images.githubusercontent.com/27042311/182336358-e28be6df-fc62-4f05-9b17-fabe1dc010f8.png)

#### 重现

lottie json和得到pag文件：
[20220608233107528.zip](https://github.com/Tencent/libpag/files/9240625/20220608233107528.zip)

#### 环境

官网里里最新linux版本的PAGConvertor

[PAGConvertor.zip](https://github.com/Tencent/libpag/files/9240662/PAGConvertor.zip)

**Comment by Hparty** [comment]
[已修复，附件中为修复后的版本。后续会更新到官网
[linux.zip](https://github.com/Tencent/libpag/files/9257203/linux.zip)
