### ISSUE TITLE
Could not get unknown property 'transformNativeLibsWithStripDebugSymbolForRelease' for project ':app' of type org.gradle.api.Project.

### ISSUE THREAD

**Issue by wangchao0837** [Tencent/libpag#48]
#### 问题

> 请告诉我们你遇到了什么问题。预期是什么？实际表现是什么？

#### 重现

> 请说明重现步骤。加载的是什么文件，你的代码是怎么写的，等等。
> PAG 素材可以在压缩之后，随这个 Bug 上传。

#### 环境

libpag 版本：libpag-ios（v3.2.4.37），libpag-android（v3.2.5.1），PAGViewer（2.1.33 beta）  
设备：iPhone 7（iOS 12），OnePlus 7（Android 10），iMac 5K（macOS 10.15.3）

#### Demo（可选）

> 请给一个 Demo 项目，我们可以运行并重现这个问题。

#### 其他（可选）

> 如果还有其他信息可以帮助我们定位问题，请添加其他内容。

**Comment by Javine1987** [comment]
@wangchao0837 请问下，你这个报错是如何解决的？

**Comment by domchen** [comment]
> 

如果是在源码编译libpag遇到问题。先确保按照readme开发指南一节配置好环境并拉取所有依赖后。然后重置一下android目录或者重新检出，不要去点gradle的升级正常编译就行。
