### ISSUE TITLE
严格模式下，PagFile.load 警告报错

### ISSUE THREAD

**Issue by peter100u** [Tencent/libpag#502]
#### 问题

使用pagFile.load资源的时候，有警告，但是不影响使用
#### 重现

> 请说明重现步骤。加载的是什么文件，你的代码是怎么写的，等等。
> PAG 素材可以在压缩之后，随这个 Bug 上传。

#### 环境

libpag-android（v4.0.5.51）

![9A015FFA584B3C7EF26146DF434782EB](https://user-images.githubusercontent.com/14010579/187360664-af813266-e3bd-4514-8b26-6249161ed277.png)

RegisterFallbackFonts中io操作，好像需要优化

![AAC6FE313A341D4E754A46283C2FD06A](https://user-images.githubusercontent.com/14010579/187360684-a36298db-4717-4279-8980-d46c80fe0ec4.png)

**Comment by kevingpqi123** [comment]
该问题已修复，请升级至4.0.5.66

**Comment by peter100u** [comment]
威武！威武！
