### ISSUE TITLE
vue2 SSR 情况下 import { PAGInit } from 'libpag'  报错

### ISSUE THREAD

**Issue by W1ping** [Tencent/libpag#504]
### Bug 描述
vue2.6 SSR 情况下 import { PAGInit } from 'libpag'  报错 ReferenceError: navigator is not defined

#### 问题
vue2.6 使用服务端渲染的情况下
npm i libpag
import { PAGInit } from "libpag";
PAGInit().then((PAG) => {
  // 实例化 PAG
})
报错 ReferenceError: navigator is not defined

#### 环境

libpag 版本：libpag-web "libpag": "^4.0.5-release.55"  
设备：window10 chrome(104.0.5112.102（正式版本） （64 位）)

**Comment by zenoslin** [comment]
SSR是在服务器端渲染一个页面，不支持类似 `navigator ` 的浏览器 API ，你可以把这些行为挪动到可用浏览器 API 的生命周期钩子中，例如 `mounted `。
