### ISSUE TITLE
PAG View 中文本的垂直对齐方式和 AE 当中的不一致

### ISSUE THREAD

**Issue by Nobit93** [Tencent/libpag#513]
#### 问题

按照文档中「如果只需要换行不需要缩小，则用框文本制作，且将框的宽度设置成你想要的宽度，框的高度设置尽量大一些，这样就不会缩小字号，只会增加行数。」的操作，生成的 PAG 文件会默认垂直居中于文本框，但是在 AE 中默认是顶部对齐的。
<img width="922" alt="image" src="https://user-images.githubusercontent.com/22189438/187854715-78c34496-85c3-49a0-b744-1ca7d331e43a.png">

[PAG 多样式测试.zip](https://github.com/Tencent/libpag/files/9467674/PAG.zip)

**Comment by kevingpqi123** [comment]
这里的原因是 AE 中有顶部对齐但是没有居中对齐，只能二选一，对于大部分的业务而言，更多需要的是居中对齐而不是顶部对齐，因此 AE 中设置顶部对齐时 SDK 层面实现为居中对齐
关于这部分，后续 PAG 会在导出插件层面进行扩充，支持通过 AE 设置居中对齐，但目前人力有限，这个需求的优先级不是太高

**Comment by domchen** [comment]
这里确实是没有跟AE对齐，但是设计如此。AE里没有垂直居中能力，但是绝大部分业务默认都需要这个，所以一开始SDK就实现成了垂直居中的方式。可以描述一下你需要顶部对齐的具体使用场景么？
