### ISSUE TITLE
setStartTime、setDuration 问题

### ISSUE THREAD

**Issue by xiaobaDev** [Tencent/libpag#515]
#### 问题

> 官方安卓demo里设置开始时间和duration 比较奇怪
  pagFile.setStartTime(-1000000);
  pagFile.setDuration(3000000);

开始时间是负数？

随后我修改duration 3000000->1000000 期望从1秒开始播放1秒动画，结果没反应
  pagFile.setStartTime(-1000000);
  pagFile.setDuration(1000000);

#### 重现

> 请说明重现步骤。加载的是什么文件，你的代码是怎么写的，等等。
> PAG 素材可以在压缩之后，随这个 Bug 上传。

#### 环境

libpag 版本：libpag-ios（v3.2.4.37），libpag-android（v3.2.5.1），PAGViewer（2.1.33 beta）  
设备：iPhone 7（iOS 12），OnePlus 7（Android 10），iMac 5K（macOS 10.15.3）

#### Demo（可选）

> 请给一个 Demo 项目，我们可以运行并重现这个问题。

#### 其他（可选）

> 如果还有其他信息可以帮助我们定位问题，请添加其他内容。

**Comment by kevingpqi123** [comment]
首选需要了解的是 AE的图层时间组织结构
![image](https://user-images.githubusercontent.com/16609221/188095514-42f755fb-8376-45d1-8e64-0b8ebe2daeba.png)
图层效果可以从时间0点开始，也可以从某个时间点开始，这个时间点可以是正数，同样也可以是负数，但动效播放始终是从第0s开始的
具体到你这边的问题，期望一个 pag 文件从第 1 s开始，就相当于在渲染树上，这个文件的起始时间是 -1s，希望动画文件播放1s，相当于需要截取这个 pag 文件的总时长为 2s

**Comment by xiaobaDev** [comment]
明白了，感谢回馈，非常棒的动画Lib
