### ISSUE TITLE
permission denied: ./convert.sh 和 sudo: ./convert.sh: command not found

### ISSUE THREAD

**Issue by zhisenyang** [Tencent/libpag#52]
正常情况下：./convert.sh
permission denied: ./convert.sh

sudo情况下：sudo ./convert.sh
sudo: ./convert.sh: command not found

不好意思，可能我比较菜，改了权限依旧不行。

**Comment by zhisenyang** [comment]
input 文件夹下有 中文名的帧图文件夹

**Comment by Hparty** [comment]
可以试试下面的操作

在目录下执行下
`chmod +x ./* `
再执行
` ./convert.sh`

如果执行过程中系统提示

**无法打开“PAGConvertor”，因为无法验证开发者。**

就在系统偏好设置 - 安全性与隐私 这边允许一下PAGConvertor的运行

**Comment by zhisenyang** [comment]
搞定了，感谢！！
