### ISSUE TITLE
调用mPagView.setMaxFrameRate()接口后，实际动画刷新帧率和设置的帧率不一致。Whether mPagView.setMaxFrameRate() is called or not, the frame rate is uncontrollable

### ISSUE THREAD

**Issue by dec31lh** [Tencent/libpag#540]
## Which Version of libpag are you using?

libpag 4.0.5.79

## What Platform are you on? 

Android 11

## Expected Behavior 

After calling mPagView.setMaxFrameRate(), the frame rate is controllable
调用mPagView.setMaxFrameRate()接口后，实际动画刷新帧率和设置的帧率一致。

## Actual Behavior

After calling mPagView.setMaxFrameRate(), the frame rate is uncontrollable
Whether mPagView.setMaxFrameRate() is called or not, onFlush will be called back 50+ times per second.
调用mPagView.setMaxFrameRate()接口后，实际动画刷新帧率和设置的帧率不一致。
在如下代码中将帧率设置为10帧，实际刷新帧率>50帧。
判断刷新帧率>50帧的依据是：
1.onFlush依然会每秒回调50+次;
2.监控GPU消耗，无论设置10帧或设置60帧，GPU消耗无明显差异。

## Code Example
mPagView = new PAGView(this);
mRelativeLayout.addView(mPagView);
PAGComposition pagComposition= PAGFile.Load(getContext().getAssets(), "test.pag");
mPagView.setComposition(pagComposition);
mPagView.setRepeatCount(0);
mPagView.setMaxFrameRate(10);
mPagView.setCacheEnabled(true);
mPagView.addPAGFlushListener(() -> Log.i(TAG, "onFlush"));
mPagView.play();

**Comment by kevingpqi123** [comment]
判断刷新帧率不应该通过 onFlush 方法，这个方法是和 ValueAnimator 的 onAnimationUpdate 回调保持一致的，不会因为 PAGView 设置帧率而变化。
在 PAG 内部，根据传入的播放进度，结合帧率，计算出渲染的当前帧，设置了帧率，相当于总帧数发生了变化，会出现一段时间渲染的都是同一帧，实际渲染的帧数会减少。

**Comment by dec31lh** [comment]
我对此仍然存在疑问。
1.我又尝试通过监听PAGVIew的基类TextureView的onSurfaceTextureUpdated，也是会回调50+次，onSurfaceTextureUpdated应该只有在每帧描绘时才会被调用，当前描绘次数明显多于设置的帧率。
甚至setMaxFrameRate设置为1时，也是会回调50+次。因此判断即使完全相同的帧，也会调用描绘函数，这样应该是过渡描绘了。
mPagView.setSurfaceTextureListener(new TextureView.SurfaceTextureListener() {
            @Override
            public void onSurfaceTextureUpdated(@NonNull SurfaceTexture surface) {
                Log.i(TAG, "onSurfaceTextureUpdated");
        });
        ……
}
2.另外通过检测GPU消耗也可以印证我的观点，设置每秒1帧或每秒10帧或每秒60帧，GPU消耗本应会有明显差异，而实际情况是无论setMaxFrameRate()设置为多少，GPU消耗无变化。

**Comment by kevingpqi123** [comment]
1、当帧率设置较低时，即多个时钟脉冲呈现的是同一帧，对于 pag 而言，渲染绘制是在 C++ 层处理的，pag 内部如果检测到渲染的是同一帧，将会使用缓存而不是再次绘制，平台侧仅仅是上屏，这个耗时很低；
2、同一个 pag 文件，如果渲染帧率降低，GPU 的利用率会下降，iOS 侧的工具比较健全，建议在 iOS 平台测试
