### ISSUE TITLE
  4.0.5.51安卓pagFile.replaceImage(it.key, pagImg) 偶遇并发问题 

### ISSUE THREAD

**Issue by xiaobaDev** [Tencent/libpag#551]
当前安卓版本4.0.5.51
我看PAGFile底层是

    public void replaceImage(int editableImageIndex, PAGImage image) {
        if (image == null) {
            nativeReplaceImage(editableImageIndex, 0);
        } else {
            nativeReplaceImage(editableImageIndex, image.nativeContext);
        }
    }

看了更新日志
[v4.0.5.79](https://github.com/Tencent/libpag/releases/tag/v4.0.5.79)
（2）修复 Android 端多线程操作crash；

请问能解决我这个问题吗？
还是我业务端加锁
synchronized(PagView对象) {
                            pagFile.replaceImage(it.key, pagImg)
                        }

非常棒的Lib库，感谢团队

## Which Version of libpag are you using?

libpag 4.1.8

## What Platform are you on? 

iOS 12, Android 10, macOS 10.15.3, Chrome 87.0  ...

**Comment by kevingpqi123** [comment]
对于 PAG 而言，替换占位图是线程安全的，不需要外部加锁, 4.0.5.79 修改的是其它问题，需要你这边升级到最新版本重新定位下原因，或者提供可以复现的 demo 工程
![image](https://user-images.githubusercontent.com/16609221/194986734-94386832-c34a-464c-a1f1-8056ed1c8ecc.png)
