### ISSUE TITLE
从79升级到82之后，activity主线程会变得繁忙，引起activity销毁延迟

### ISSUE THREAD

**Issue by xiaobaDev** [Tencent/libpag#566]
请问79~82有升级什么控件库，或者绘制方面做了重大改变吗？
我们activity销毁过长（超过4秒）会报崩溃提示
79版本比较稳定，82版本销毁时间频繁超过4秒。
同样的代码，区别就是pag79和82版本区别

## Which Version of libpag are you using?

libpag 4.1.8

## What Platform are you on? 

iOS 12, Android 10, macOS 10.15.3, Chrome 87.0  ...

**Comment by sauchye** [comment]
参考一些说明，调试iOS播放完一个动画后再从这个动画setProgress 0.7开始循环播放，这里设置依旧从开始循环播放。

```
[self .pagView setProgress:0.7];

[self .pagView setRepeatCount:0];

[self .pagView play];
```

这里如何使用播放指定时间段或progress的pag呢，非常感谢！
https://bbs.pag.art/thread/167

**Comment by kevingpqi123** [comment]
> 1018暂时用这种方法处理循环播放部分动效onAnimationUpdate
> 
> ```
> - (void)onAnimationUpdate:(PAGView*)pagView {
>     double getProgress = pagView.getProgress;
>     if (getProgress >= 0.7) {
>         [pagView setProgress:0.5];
>         [pagView flush];
>     }
> }
> ```
> 
> 参考一些说明，调试iOS播放完一个动画后再从这个动画setProgress 0.7开始循环播放，这里设置依旧从开始循环播放。
> 
> ```
> [self .pagView setProgress:0.7];
> 
> [self .pagView setRepeatCount:0];
> 
> [self .pagView play];
> ```
> 
> 这里如何使用播放指定时间段或progress的pag呢，非常感谢！ https://bbs.pag.art/thread/167

不要在这里回复与 issue无关 的内容

**Comment by kevingpqi123** [comment]
79 ~ 82 版本之间主要是修复 crash 问题，不涉及功能层面，可以看下修改记录，分支：release/4.0.5, 两个版本都有 tag
如果需要我们这边定位，请提供复现的 demo 工程

**Comment by xiaobaDev** [comment]
> 

demo是正常的，我们生成环境app才出现，所以我确认下，有升级引入的第三方框架吗

**Comment by kevingpqi123** [comment]
没有，两个版本之间修改的内容很少，主要是 crash问题
