### ISSUE TITLE
Android和IOS播放特效没有声音

### ISSUE THREAD

**Issue by DizzyDuan** [Tencent/libpag#568]
Android 和 IOS 特效正常播放，但是没有声音。
![WX20221017-173250@2x](https://user-images.githubusercontent.com/8134160/196143718-7f04f2f0-4a3f-45d6-83d2-e7f8fe69c5ac.png)

## Which Version of libpag are you using?

libpag [4.1.12](https://github.com/Tencent/libpag/releases/tag/v4.1.12)

## What Platform are you on? 

iOS 12, Android 10, macOS 10.15.3, Chrome 87.0  ...

**Comment by kevingpqi123** [comment]
<img width="747" alt="WeChatWorkScreenshot_a121ee01-f64c-4352-abd2-7ec0c49f34fc" src="https://user-images.githubusercontent.com/16609221/196320996-15a3881e-2bce-4488-bfc8-6efcda07599a.png">
https://pag.art/docs/faq.html
