### ISSUE TITLE
Generate Xcode(IOS) project via vendor_tools

### ISSUE THREAD

**Issue by alyfreym** [Tencent/libpag#581]
Hi. Is it possible to add a script for generation Xcode (IOS) project?. In order to be able to debug and add mine functionality?
Im try to use this command 

cmake -D IOS=ON -G Xcode.

But I have a error 

CMake Error at tgfx/CMakeLists.txt:208 (find_library):
  Could not find UIKit_LIBS using the following names: UIKit.

Because script default path for Cocoa library is MacOS folder. => /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/ 

find_library() -> Try to find relative  /MacOSX.platform/  folder.

It would be cool if they added a script to generate Xcode projects

**Comment by lvpengwei** [comment]
The iOS project is at [ios](https://github.com/Tencent/libpag/tree/811aa725a3cea2a137c2cfb8e298965ef2b6a5e0/ios), where you can run `pod install`, and then run the `PAGViewer.xcworkspace`.

**Comment by alyfreym** [comment]
If you need just copy source codes from this library and modify then compile in your Xcode project. Try this script to generate Xcode project -> https://github.com/sheldonth/ios-cmake

It will allow you to create the project using libpag CMakeList.txt files.
