### ISSUE TITLE
ios端，没有提供加载服务器端url地址文件的方法吗

### ISSUE THREAD

**Issue by liujieyuu** [Tencent/libpag#587]
## Question
ios端，没有提供加载服务器端url地址文件的方法吗

**Comment by lvpengwei** [comment]
FAQ - [问：PAG SDK是否支持加载网络文件？](https://pag.art/docs/faq.html#%E9%97%AEpag-sdk%E6%98%AF%E5%90%A6%E6%94%AF%E6%8C%81%E5%8A%A0%E8%BD%BD%E7%BD%91%E7%BB%9C%E6%96%87%E4%BB%B6)
