### ISSUE TITLE
鸿蒙2 pag动画 不显示

### ISSUE THREAD

**Issue by i-farmer** [Tencent/libpag#596]
## Which Version of libpag are you using?

libpag 4.0.5.66、4.0.5.82

## What Platform are you on? 

![image](https://user-images.githubusercontent.com/17808903/201033464-e15d823b-8b7d-497b-97a6-ae6e0446b820.png)
上面是不显示的机型

![image](https://user-images.githubusercontent.com/17808903/201033661-3005bb4d-9f4b-4bda-a1bd-479827a5c8ca.png)
这个机型，就可以显示

## Code Example
```xml
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android">

    <FrameLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <org.libpag.PAGView
            android:id="@+id/mAnimView"
            android:layout_width="match_parent"
            android:layout_height="wrap_content" />
    </FrameLayout>
</layout>
```
```java
binding?.mAnimView?.let {
            it.composition = PAGFile.Load(context.assets, "loading.pag")
            it.addListener(object : PAGViewListenerAdapter() {

                override fun onAnimationEnd(view: PAGView) {
                    dismiss()
                }
            })
            it.post { it.play() }
        }
```
## PAG File
[loading.pag.zip](https://github.com/Tencent/libpag/files/9978635/loading.pag.zip)

**Comment by i-farmer** [comment]
现象是这样子的，前面我拿那只手机调试，PAGFile.Load正确加载，也可以正常运行到ValueAnimator.start()，没有抛出任何错误，但是就是不显示；然后刚刚 包没换（还是最开始发现bug的那个包），结果可以显示了。

**Comment by i-farmer** [comment]
请教我要怎么排查问题

**Comment by domchen** [comment]
你可以检查一下有问题的那个手机是不是在系统设置里全局关闭了动画功能。

**Comment by jzqCode** [comment]
无障碍服务里面的动画 关闭了pag就不能用了。

**Comment by kevingpqi123** [comment]
PAG 动画播放基于的是系统的 ValueAnimator，一切会影响到 ValueAnimator 正常使用的设置或操作，同样会影响到 PAGView
