### ISSUE TITLE
Its possible to replace videos like a replace image? 

### ISSUE THREAD

**Issue by alyfreym** [Tencent/libpag#600]
I have template with 1 video. It is possible to dynamic replace video to user selected video? (IOS)

in PAGViewer I can replace image placeholder to video.  How to enable this functionality in mobile iOS sdk?

I attached video file. You can look and understand what I mean

https://user-images.githubusercontent.com/29518174/201521381-44c5438d-08b1-4765-aa70-fb0cbb218aa1.mp4

and AE project with source file 

[AE.zip](https://github.com/Tencent/libpag/files/9997164/AE.zip)

**Comment by alyfreym** [comment]
@domchen Any suggestions please?

**Comment by domchen** [comment]
This functionality is not part of PAG, you should do it by using a third-party video-editing framework,  PAG is not a video-editing framework, it is for animation rendering only. We implement this functionality in PAGViewer by using our own video-editing framework, but it is not open-sourced. You can check the AVFoundation framework on iOS, which should do the work.
