### ISSUE TITLE
Pag 使用高斯模糊弄个简单动效，PAG预览和 AE里的效果不一致

### ISSUE THREAD

**Issue by lemoon** [Tencent/libpag#602]
PagViewer: 4.0.5.22 - macos
AE: 18.4.1(Build 4) -macos

使用高斯模糊定两个关键帧简单做个动画，预览就会错位

<img width="1284" alt="image" src="https://user-images.githubusercontent.com/4155973/201811258-dcea3145-5375-4568-a6b8-7ffdd40f284a.png">

[test文件夹 2.zip](https://github.com/Tencent/libpag/files/10008552/test.2.zip)

**Comment by FusionXu** [comment]
可以尝试更新一下导出插件，我用最新的版本暂时没有出现这个问题
另外直接导出的话，表现是否正常？

**Comment by lemoon** [comment]
<img width="1707" alt="image" src="https://user-images.githubusercontent.com/4155973/202378712-572a6e60-5c4b-48d7-9506-e1d672a3b32b.png">
PagViewer 提示已经是最新，直接导出是一样的问题。
我重新添加了导出的.pag文件。可以分析一下是导出.pag有问题还是viewer有问题。
[出错文件.zip](https://github.com/Tencent/libpag/files/10028818/default.zip)

另外你那边如果不会复现的话，可否提供下导出的.pag 、 AE/PAGViewer的版本号？

**Comment by FusionXu** [comment]
<img width="525" alt="截屏2022-11-17 15 34 35" src="https://user-images.githubusercontent.com/4111863/202384405-34ce25ce-59f1-4a53-930a-786a56c80e5c.png">

可以在pagviewer的设置里，勾选使用beta版本，再更新一下试试
你的mac是否是m1的？

**Comment by lemoon** [comment]
> <img alt="截屏2022-11-17 15 34 35" width="525" src="https://user-images.githubusercontent.com/4111863/202384405-34ce25ce-59f1-4a53-930a-786a56c80e5c.png">
> 
> 可以在pagviewer的设置里，勾选使用beta版本，再更新一下试试 你的mac是否是m1的？

1.是M1
2.勾选beta后更新AE插件正常了

<img width="512" alt="image" src="https://user-images.githubusercontent.com/4155973/202389241-fab45017-74a9-4098-ae97-19c348b986fd.png">

请问如果是beta的话，对应的sdk该如何选择？
