### ISSUE TITLE
Does it support x86_64 for Android platform?

### ISSUE THREAD

**Issue by guohai** [Tencent/libpag#620]
We wanna to run Android app with this function on Android emulator for Windows/Intel platform.
From the docs that it only support armeabi, armeabi-v7a, arm64-v8a.

## ⭐ Suggestion

Can we build it for x86_64 arch?

**Comment by kevingpqi123** [comment]
x86_64 arch can use armeabi on the Android platform. 
https://blog.51cto.com/u_15307523/3133852
You can also build an x86_64 arch based on open-source code.
