### ISSUE TITLE
pag 动画(蒙版拓展)导出和AE不一致

### ISSUE THREAD

**Issue by lemoon** [Tencent/libpag#625]
AE版本：macOS 18.4.1
pag版本：4.1.0.7(beta)

现象：AE里面前20帧应该是完全透明的，但是pag变成一个反向蒙版消失的动画。把第一个关键帧“蒙版拓展”的值改为-512后就正常了。

<img width="1722" alt="image" src="https://user-images.githubusercontent.com/4155973/204957760-af37ff25-9203-44e5-a433-cf356114a889.png">

AE工程文件和导出的pag

[光圈 2000ms文件夹.zip](https://github.com/Tencent/libpag/files/10128969/2000ms.zip)

**Comment by FusionXu** [comment]
确实存在这个问题，我们这边再检查一下类似的边界场景
目前先使用正常表现的值来还原效果吧

**Comment by FusionXu** [comment]
负的expend值，对于不规则的path，难以确定超出哪个值后就不显示，所以目前代码上这个问题不好解决
只能在设计素材时确保参数都是有效的，这样可以保证效果与AE一致
