### ISSUE TITLE
web下无法播放视频时，如何捕获异常？

### ISSUE THREAD

**Issue by chaserstrong** [Tencent/libpag#627]
## Question
ios低电量模式下，调用
```
const pagView = await PAG.PAGView.init(pagFile, canvas)
```
会抛出如下异常
```
throw new Error("Failed to decode video, please play PAG after user gesture. Or your can load a software decoder to decode the video.");
```
但是在javascript环境下，无法功过try，catch捕获这个错误，请问有别的捕获方法吗？

**Comment by zenoslin** [comment]
感谢你的反馈，这个问题我们正在修复中，有任何进展会在这个 issue 同步。

**Comment by 5icoder** [comment]
> Question

我在桌面版的火狐浏览器中也出现了这个问题，请问还有别的情况也会抛出这个错误吗？

**Comment by chaserstrong** [comment]
> 感谢你的反馈，这个问题我们正在修复中，有任何进展会在这个 issue 同步。

感谢，请问预计什么时候能修复？我这边其实主要是关心，能捕获到这个错误就行。

**Comment by chaserstrong** [comment]
> > Question
> 
> 我在桌面版的火狐浏览器中也出现了这个问题，请问还有别的情况也会抛出这个错误吗？

我是ios，低电量模式下会触发。

**Comment by zenoslin** [comment]
> > 感谢你的反馈，这个问题我们正在修复中，有任何进展会在这个 issue 同步。
> 
> 感谢，请问预计什么时候能修复？我这边其实主要是关心，能捕获到这个错误就行。

这个问题会在下一个版本更新，我们已经有修复的方案，开始 coding 了。

**Comment by chaserstrong** [comment]
> > > 感谢你的反馈，这个问题我们正在修复中，有任何进展会在这个 issue 同步。
> > 
> > 
> > 感谢，请问预计什么时候能修复？我这边其实主要是关心，能捕获到这个错误就行。
> 
> 这个问题会在下一个版本更新，我们已经有修复的方案，开始 coding 了。

哇！大赞。 下个版本大约什么时候，我这边也在开发，要做对应的兼容处理，不知道时间上来不来得及。 我这边最晚大约下周末得用到

**Comment by zenoslin** [comment]
预计可能来不及，下个版本预计会有几个比较重要的修复和优化项一起发布。所以需要一周以上的时间，还请谅解。

**Comment by zenoslin** [comment]
> > > > 感谢你的反馈，这个问题我们正在修复中，有任何进展会在这个 issue 同步。
> > > 
> > > 
> > > 感谢，请问预计什么时候能修复？我这边其实主要是关心，能捕获到这个错误就行。
> > 
> > 
> > 这个问题会在下一个版本更新，我们已经有修复的方案，开始 coding 了。
> 
> 哇！大赞。 下个版本大约什么时候，我这边也在开发，要做对应的兼容处理，不知道时间上来不来得及。 我这边最晚大约下周末得用到


预计可能来不及，下个版本预计会有几个比较重要的修复和优化项一起发布。所以需要一周以上的时间，还请谅解。

**Comment by chaserstrong** [comment]
@zenoslin 大佬还想请问下，这个兼容性修复的方向和思路是什么？能简单描述下吗？ 如果来不及，我是否可以自行按照你们的思路先解决下？

**Comment by chaserstrong** [comment]
> 哦哦，所以修复完之后，对不能自动播放的设备，还是需要接入方自己处理的是吧？

**Comment by chaserstrong** [comment]
> @chaserstrong 改动主要思路是让 PAGView 和 VideoReader 产生关联，才能传递错误。如果你们想临时解决可以尝试从全局的 `unhandledrejection` 捕获到这个错误。

哦哦，所以修复完之后，对不能自动播放的设备，还是需要接入方自己处理的是吧？

**Comment by zenoslin** [comment]
@chaserstrong 是的，引导用户点击屏幕是具体业务的工作，SDK 只注重于渲染方面。

**Comment by chaserstrong** [comment]
> @chaserstrong 是的，引导用户点击屏幕是具体业务的工作，SDK 只注重于渲染方面。
我在测试过程中发现，当调用pagView.init()触发无法自动播放时，如果在后续的其他click事件中，再次调用pagView.init(). 此时后续的pag视频也会无法播放。
