### ISSUE TITLE
使用xcode打开demo工程不能build

### ISSUE THREAD

**Issue by yiwangwuqian** [Tencent/libpag#631]
![image](https://user-images.githubusercontent.com/1974716/205422828-ae419447-2fde-4279-a35e-77924beb7222.png)
如图所示，麻烦把缺的文件补一下呗

**Comment by kevingpqi123** [comment]
确认下在 ios 目录下是否执行了 pod install，打开的是否是 PAGViewer.xcworkspace

**Comment by yiwangwuqian** [comment]
> 



> 确认下在 ios 目录下是否执行了 pod install，打开的是否是 PAGViewer.xcworkspace

你好，经过pod install并且打开workspace，现在报这个：
![image](https://user-images.githubusercontent.com/1974716/205537965-de155c9d-01a0-4df7-ab07-f51f7ec35720.png)

**Comment by kevingpqi123** [comment]
这是因为依赖的第三方库拉取下来
看下 README，里面有依赖拉取方式
<img width="896" alt="image" src="https://user-images.githubusercontent.com/16609221/205573839-8194b2f6-9264-4065-a2b0-2b3396d0815c.png">

**Comment by yiwangwuqian** [comment]
卡在harfbuzz这个库，今天试了16遍😂

**Comment by kevingpqi123** [comment]
这是环境的问题，你通过其它下载到third_party 路径下也可以
