### ISSUE TITLE
web 下播放此 pag 非常卡顿，请问是否有优化空间？

### ISSUE THREAD

**Issue by jiangyijie27** [Tencent/libpag#633]
web 下播放此 pag 非常卡顿，请问是否有优化空间？
谢谢，企业微信: yijiejiang

## Which Version of libpag are you using?

libpag 4.1.8

## What Platform are you on? 

iOS 16 Safari/微信 webview 都卡

## Actual Behavior

https://user-images.githubusercontent.com/7429808/206350974-3bde23d1-2a86-4829-a446-c611733f45b0.mp4

## PAG File
http://adsmind.gdtimg.com/ads_svp_video__0b53aqaaaaaaryao5imoszrrubaeaacaaaca.f0.pag?dis_k=44c5e96be915b3e61c327e32d6b48ad7&dis_t=1670311563&m=4a0b63688a58b510500c26f0a617f75f

**Comment by zenoslin** [comment]
我在 iPhone 11 下播放了你的 PAG 文件，并没有发现卡顿现象。需要联系你提供进一步的 Demo 工程进行排查。

**Comment by zenoslin** [comment]
@jiangyijie27 你好，我们在 #640 中修复了播放卡顿的问题，请升级 SDK 到 4.1.33 体验，非常感谢你对 PAG 的支持！
