### ISSUE TITLE
libpag.wasm资源文件会加载两次

### ISSUE THREAD

**Issue by chaserstrong** [Tencent/libpag#638]
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/18061322/206854578-c63b465d-fb06-4398-987c-c95bd7d75093.png">
开发过程中，发现wasm文件会加载两次，不知道是否正常。 
是vue3项目，通过import方式引入的，确认过初始化代码只会执行一次，代码如下：

```
import { PAGInit, types } from 'libpag';

....

pag.data = await PAGInit({
    locateFile: () => 'https://xxxx/xxx.wasm',
  });
```

两个资源的引入路径如下：
<img width="996" alt="image" src="https://user-images.githubusercontent.com/18061322/206854902-855e7d5d-d43a-454b-aa78-17cea4fa5434.png">
<img width="996" alt="image" src="https://user-images.githubusercontent.com/18061322/206854938-59d574f1-b677-4324-aa05-438c6e687a37.png">

**Comment by zenoslin** [comment]
@chaserstrong 使用 https://github.com/libpag/pag-web/tree/main/vue/vue3 验证并不会出先加载两次 wasm 文件的情况，需要检查一下是否加入了 vConsole 之类会重写 fetch 的第三方库。PAGInit 中用了 fetch 加载 wasm 文件。
