### ISSUE TITLE
iOS support Swift package manager

### ISSUE THREAD

**Issue by LuoPengFei** [Tencent/libpag#660]

**Comment by kevingpqi123** [comment]
We will include this demand in the demand pool, then schedule according to the priority of the demand.

**Comment by quentinfasquel** [comment]
Here : https://github.com/quentinfasquel/libpag-ios

**Comment by quentinfasquel** [comment]
Also @kevingpqi123 I would highly recommend to avoid versioning binaries (xcframework) on your sample repo.

**Comment by domchen** [comment]
> Also @kevingpqi123 I would highly recommend to avoid versioning binaries (xcframework) on your sample repo.

We need to version the prebuilt binaries as Cocoapods depends on them. A storage location is necessary to store the binaries so that Cocoapods can access them.

**Comment by kevingpqi123** [comment]
Swift package manager is now supported, Location: https://github.com/libpag/pag-ios, Minimum supported version: 4.2.97.
