### ISSUE TITLE
微信小程序set width out of range

### ISSUE THREAD

**Issue by 95y** [Tencent/libpag#679]
## Which Version of libpag are you using?

libpag 4.1.35

## What Platform are you on? 

iOS 15.7.1

## Expected Behavior 

正常渲染

## Actual Behavior

来回切换弹框，能看到实际报错

## Code Example
小程序代码片段: https://developers.weixin.qq.com/s/2ztb2bmW79F1

**Comment by 95y** [comment]
已经解决

**Comment by Hugohui** [comment]
怎么解决的

**Comment by Hugohui** [comment]
> 已经解决

求助，什么问题导致的呢？同样问题
