### ISSUE TITLE
MIME Type errors

### ISSUE THREAD

**Issue by YuanXMjoy** [Tencent/libpag#680]
wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'
falling back to ArrayBuffer instantiation

## Which Version of libpag are you using?

libpag 4.1.8

## What Platform are you on? 

iOS 12, Android 10, macOS 10.15.3, Chrome 87.0  ...

## Expected Behavior 

no warning and don't go to my promise cacth
## Actual Behavior
Actually,indeed,   the-wasm problem will go to my promise-catch every running; make Sure you will fix this problem; Now it seems that the libpag-web is just a toy;

wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'
falling back to ArrayBuffer instantiation
## Code Example
const { PAGInit } = require('libpag');
        const isDev = process.env.NODE_ENV === 'development';
        const pathPrefix = isDev ? `http://${window.location.host}/static/js/` : 'blabla';
        PAGInit({ locateFile: (file) => `${pathPrefix}${file}` }).then((PAG) => {
          const url = currentTheme === 'day' ? 'https://xqdoc.imedao.com/185813c54863628f3fce75d5.pag' : 'https://xqdoc.imedao.com/1858139f0af360403fc7eb34.pag';
          fetch(url)
            .then((response) => response.arrayBuffer())
            .then(async (buffer) => {
              const pagFile = await PAG.PAGFile.load(buffer);
              const canvas = canvasRef.current;
              // canvas.width = parseInt(pagFile.width()/window.devicePixelRatio);
              // canvas.height = parseInt(pagFile.height()/window.devicePixelRatio);
              canvas.width = '54';
              canvas.height = '66.6';
              const pagView = await PAG.PAGView.init(pagFile, canvas);
              pagView.setRepeatCount(0);
              pagView.play().then(() => {
                setLoadingFinish(true);
                setLoading(false);
                setTimeout(() => {
                  pagView.pause();
                }, 2500);
              });
            }).catch((err0) => {
          });
        }).catch((err1) => {
        });

**Comment by zenoslin** [comment]
The warning message means the wasm file MIME type error. 
You can set "application/wasm" in Apache/Nginx on Your server to resolve this warning in your project.

**Comment by zenoslin** [comment]
If you load other scripts that proxy the fetch API, like `vConsole`. 
it will fail the parameter type checker of `WebAssembly.instantiateStreaming` with a warning message.
