### ISSUE TITLE
如何像rlottie那样移植到嵌入式环境

### ISSUE THREAD

**Issue by qdk0901** [Tencent/libpag#681]
你好，我对比了pag、lottie和svga，发现pag相对于lottie有很多好特性，但是在pag上没找到类似于三星rlottie那样的实现，rlottie仅依靠cpu和neon加速，易于移植到嵌入式环境，实测性能也不错

对于移植pag到无gpu的嵌入式环境，你们有没有什么建议和文档，谢谢

**Comment by kevingpqi123** [comment]
pag 在 Linux 平台支持 CPU 环境和 GPU 环境，具体如何编译可以看下这篇文章：https://pag.art/docs/sdk-desktop.html
默认编译出来的就是 CPU 环境的版本，通过 swiftshader 提供一个 CPU 模拟 GPU 的环境
这部分使用已经很成熟了，微信和手 Q 中的游戏战报使用的都是服务端 CPU 渲染的方案，GPU 服务器的成本太高了
