### ISSUE TITLE
部分Android 9的TV机顶盒出现pag闪烁问题

### ISSUE THREAD

**Issue by hjzlzh123** [Tencent/libpag#687]
使用了Android 9的机顶盒，pag循环执行播放，每执行一次完成动画就会闪烁，虽然不排除硬件问题，但还是麻烦帮忙看抓取的日志。
`01-18 11:35:57.786 E/GLConsumer(13286): [SurfaceTexture-0-13286-3] updateAndRelease: GLConsumer is not attached to an OpenGL ES context
01-18 11:35:57.787 W/System.err(13286): java.lang.IllegalStateException: Unable to update texture contents (see logcat for details)
01-18 11:35:57.789 W/System.err(13286): 	at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
01-18 11:35:57.789 W/System.err(13286): 	at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:243)
01-18 11:35:57.789 W/System.err(13286): 	at org.libpag.VideoSurface.updateTexImage(VideoSurface.java:146)
01-18 11:35:57.789 W/System.err(13286): 	at org.libpag.PAGPlayer.flushAndFenceSync(Native Method)
01-18 11:35:57.789 W/System.err(13286): 	at org.libpag.PAGPlayer.flush(PAGPlayer.java:163)
01-18 11:35:57.789 W/System.err(13286): 	at org.libpag.PAGView.flush(PAGView.java:779)
01-18 11:35:57.790 W/System.err(13286): 	at org.libpag.PAGView.updateView(PAGView.java:344)
01-18 11:35:57.790 W/System.err(13286): 	at org.libpag.PAGView.access$000(PAGView.java:31)
01-18 11:35:57.790 W/System.err(13286): 	at org.libpag.PAGView$PAGViewHandler.handleMessage(PAGView.java:166)
01-18 11:35:57.790 W/System.err(13286): 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-18 11:35:57.790 W/System.err(13286): 	at android.os.Looper.loop(Looper.java:193)
01-18 11:35:57.790 W/System.err(13286): 	at android.os.HandlerThread.run(HandlerThread.java:65)`
[_mut_2023-01-18_11-37-39_logcat.log](https://github.com/Tencent/libpag/files/10441917/_mut_2023-01-18_11-37-39_logcat.log)

**Comment by kevingpqi123** [comment]
这里的 log 信息比较有限，执行完成成动画就会闪烁是啥意思，动画播放完闪烁吗？此外，其它平台是否也存在该问题，先确认是单机问题还是普遍的问题？

**Comment by hjzlzh123** [comment]
目前看只有单个机顶盒有兼容性问题，提供了demo和日志，视频，麻烦看看能不能帮忙定位下问题呢
[_mut_2023-01-18_14-06-16_logcat.log](https://github.com/Tencent/libpag/files/10442641/_mut_2023-01-18_14-06-16_logcat.log)
[PagViewDemo.zip](https://github.com/Tencent/libpag/files/10442647/PagViewDemo.zip)

https://user-images.githubusercontent.com/30074082/213097393-513cee00-992e-4c28-bc82-9876ab8c29a0.mp4

**Comment by peerless2012** [comment]
看着像中间有只清屏，未绘制的样子。

**Comment by kevingpqi123** [comment]
建议先使用 pag 的 demo 加载你这边的 pag 文件进行测试，如果 demo 工程渲染正常，就排查你这边的实现
如果 demo 工程出现问题，你们可能要基于 pag 的源码自己排查，我们这边没有机顶盒，并且你这边还是单机问题
排查的过程中遇到问题，我们可以协助分析

**Comment by hjzlzh123** [comment]
好的我先试试pag的demo在盒子上运行看看
