### ISSUE TITLE
使用崩溃问题

### ISSUE THREAD

**Issue by lyqaiym** [Tencent/libpag#695]
## Which Version of libpag are you using?

libpag 4.0.5.17

## What Platform are you on? 

Android

## Code Example
https://juejin.cn/post/7194269790389665851

**Comment by kevingpqi123** [comment]
4.0.5.17 是 4.0版本系列很早期的版本了，pag 不断在进行迭代，建议升级至最新版本
如果存在 crash，建议提供完整的堆栈信息，如果可以复现，建议提供 demo 工程提升解决问题的效率

**Comment by kevingpqi123** [comment]
我试了下在 onAnimationEnd 中 removeView，使用 4.0.5.17 还是最新版本没有复现你所说的 crash，建议提供复现 demo

**Comment by lyqaiym** [comment]
https://github.com/lyqaiym/pagdemo。ViewGroup需要多个View才能复现。因为会影响子view循环

**Comment by kevingpqi123** [comment]
这里和 pag 有啥关系，你先移除了父容器，然后再父容器移除它的子View，所以触发的是系统的 crash
看下类似问题的分析：https://blog.csdn.net/a1018875550/article/details/106213565

**Comment by lyqaiym** [comment]
主要是对比了lottie的动画设计。lottie 在 Visibility 不可见的时候，只是会暂停动画，可见恢复动画，不会多次调用 onAnimationStart。pag 在显示以后还是会调用 onAnimationStart。这只是个复现demo，真正的removeView不是我调的。

**Comment by kevingpqi123** [comment]
onAnimationStart这是另外的逻辑问题
你这边出现 crash 的原因是，先移除了父容器：
ViewGroup group = (ViewGroup) constraintLayout.getParent();
if (group != null) {
       group.removeView(constraintLayout);
 }
然后又通过父用器移除子 View
public void onAnimationEnd(PAGView view) {
     Log.d(TAG, "onAnimationEnd", new Exception());
      constraintlayout.removeView(view);
 }

顺序反了，父容器已经移除，对它的操作的意义是啥？为啥不在移除前操作
