### ISSUE TITLE
希望提供linux静态库文件libpag.a

### ISSUE THREAD

**Issue by wzqgepoge** [Tencent/libpag#700]
目前只支持移动端最新版sdk的提供，后续是否能提供下linux对应的静态库文件libpag.a， 这样对linux用户能友好一些，多谢。因为初期的编译环境搭建问题较多，容易任务阻塞。

**Comment by kevingpqi123** [comment]
C++ 开发就是需要跟各种编译器工具和环境打交道，不同的编译工具、不同的环境编译出来的版本是不一样的，这里没有办法回避，需要自己解决，这也是我们 Linux 平台没有提供制品库的原因。
关于 Linux 平台 C++ 版本的编译，可以参考这里：https://github.com/Tencent/libpag/blob/main/linux/README.md
另外，我们的每一次 MR，都会基于 github 的构建机在 Linux 平台编译测试，还可以参考这里：
https://github.com/Tencent/libpag/actions/runs/4060234615/jobs/6989120497
