### ISSUE TITLE
could not find Version 4.1.43

### ISSUE THREAD

**Issue by stkv3i** [Tencent/libpag#708]
Could not find libpag-4.1.43.jar (com.tencent.tav:libpag:4.1.43) , please help

**Comment by kevingpqi123** [comment]
https://search.maven.org/artifact/com.tencent.tav/libpag
<img width="1826" alt="WeChatWorkScreenshot_6aa53b63-a259-4606-aa25-1a08c14df8cb" src="https://user-images.githubusercontent.com/16609221/216497923-7eee9069-d326-45cf-86f2-868611f7ddc4.png">

我这边加载是正常的
<img width="1107" alt="WeChatWorkScreenshot_6e05f1e2-d33e-4ed2-9938-5d8d833175a4" src="https://user-images.githubusercontent.com/16609221/216497985-3ca37801-ffa9-4897-be40-521363b39e9f.png">

**Comment by stkv3i** [comment]
> https://search.maven.org/artifact/com.tencent.tav/libpag <img alt="WeChatWorkScreenshot_6aa53b63-a259-4606-aa25-1a08c14df8cb" width="1826" src="https://user-images.githubusercontent.com/16609221/216497923-7eee9069-d326-45cf-86f2-868611f7ddc4.png">
> 
> 我这边加载是正常的 <img alt="WeChatWorkScreenshot_6e05f1e2-d33e-4ed2-9938-5d8d833175a4" width="1107" src="https://user-images.githubusercontent.com/16609221/216497985-3ca37801-ffa9-4897-be40-521363b39e9f.png">

但是为什么我在相同的网络下4.1.42可以下载，但是4.1.43就不行，而且我看issues里面其他人也反馈不能下载4.1.43唉

![Uploading image.png…]()

**Comment by kevingpqi123** [comment]
另外一个同学是昨天反馈的，aar 上传 Maven Central  后过一会儿才能拉取到，我们上传成功后就立即同步了版本，他这边应该是还没有同步陈工

**Comment by kevingpqi123** [comment]
你可以到 maven 上查询，4.1.43版本都是存在的，拉取不到的问题你自己再排查下
<img width="1587" alt="WeChatWorkScreenshot_9b95214d-3d91-4777-8bc6-1908426e3383" src="https://user-images.githubusercontent.com/16609221/216506969-3564f1d3-053f-4cf8-88c5-d21930c5c0df.png">

**Comment by xiaobaDev** [comment]
com.tencent.tav:libpag:4.1.43@aar 后面加@aar就行了 @stkv3i @kevingpqi123
