### ISSUE TITLE
What's the path field

### ISSUE THREAD

**Issue by PPTing** [Tencent/libpag#710]
## Question

In Android SDK there is a function PAGFile.Load(String path)

So what should developer pass a value to it?

Is "/data/user/0/com.xxx.xxx/files/gift/download/xxx.pag" right?

**Comment by kevingpqi123** [comment]
PAGFile can load absolute paths. You can read this article about path acquisition in the android platform.
https://blog.csdn.net/qq_29428215/article/details/89337034

If loading fails,  you can check the file existence through the appropriate method in the class of File.
