### ISSUE TITLE
PAG播放动画监听回调有问题

### ISSUE THREAD

**Issue by pichsy** [Tencent/libpag#712]
使用的是pag最新版本库 4.1.41

// 首次加载并播放，回调有问题。走到cancel，及两次start
2023-02-04 10:53:36.813 8146-8146/? D/PagPlayerView: onAnimationStart:==> pagPath  like.pag 
2023-02-04 10:53:36.845 8146-8146/? D/PagPlayerView: onAnimationCancel:==> pagPath  like.pag 
2023-02-04 10:53:36.867 8146-8146/? D/PagPlayerView: onAnimationStart:==> pagPath  like.pag 
2023-02-04 10:53:38.040 8146-8146/? D/PagPlayerView: onAnimationEnd:==> pagPath  like.pag 
// 第二次播放
2023-02-04 10:53:41.541 8146-8146/? D/PagPlayerView: onAnimationStart:==> pagPath  like.pag 
2023-02-04 10:53:42.755 8146-8146/? D/PagPlayerView: onAnimationEnd:==> pagPath  like.pag 
// 第二次以后其他次数正常回调。
2023-02-04 10:53:46.752 8146-8146/? D/PagPlayerView: onAnimationStart:==> pagPath  like.pag 
2023-02-04 10:53:47.969 8146-8146/? D/PagPlayerView: onAnimationEnd:==> pagPath  like.pag 
2023-02-04 10:53:50.765 8146-8146/? D/PagPlayerView: onAnimationStart:==> pagPath  like.pag 
2023-02-04 10:53:51.984 8146-8146/? D/PagPlayerView: onAnimationEnd:==> pagPath  like.pag 
2023-02-04 10:53:54.137 8146-8146/? D/PagPlayerView: onAnimationStart:==> pagPath  like.pag 
2023-02-04 10:53:55.350 8146-8146/? D/PagPlayerView: onAnimationEnd:==> pagPath  like.pag

**Comment by pichsy** [comment]
import android.content.Context
import android.widget.RelativeLayout
import android.view.ViewGroup
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.opengl.*
import android.util.Log
import org.libpag.*
import java.io.IOException
import java.io.InputStream

/**
 * 这个类文件，是官方demo中的，我添加动画播放监听。
 */
class PagPlayerView {
    private var mPagView: PAGView? = null
    private var repeatCount = 1
    private var composition: PAGComposition? = null
    private var factory: Long = 0
    private var maxHardwareDecoderCount = 0
    private var eglDisplay: EGLDisplay? = null
    private var eglSurface: EGLSurface? = null
    private var eglContext: EGLContext? = null
    private var textureID = 0

    private var pagCreateListener: PagCreateListener? = null
    private var pagAnimListener: PagAnimationListener? = null

    fun setPagAnimationListener(pagAnimListener: PagAnimationListener?): PagPlayerView {
        this.pagAnimListener = pagAnimListener
        return this
    }


    fun createView(context: Context, pagPath: String?): PAGView {
        eglSetup()
        mPagView = PAGView(context, eglContext)
        if (composition != null) {
            mPagView?.composition = composition
        } else {
            val pagFile = PAGFile.Load(context.assets, pagPath)
            pagCreateListener?.onCreate(pagFile)
            mPagView?.composition = pagFile
        }
        mPagView?.layoutParams = RelativeLayout.LayoutParams(
            ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT
        )
        mPagView?.setRepeatCount(repeatCount)
        mPagView?.addPAGFlushListener { }
        if (factory != 0L) {
            VideoDecoder.RegisterSoftwareDecoderFactory(factory)
            VideoDecoder.SetMaxHardwareDecoderCount(maxHardwareDecoderCount)
        }
        mPagView?.addListener(object : PAGView.PAGViewListener {
            override fun onAnimationStart(view: PAGView?) {
                Log.d("PagPlayerView", "onAnimationStart:==> pagPath  ${pagPath} ")
                pagAnimListener?.onAnimationStart()
            }

            override fun onAnimationEnd(view: PAGView?) {
                Log.d("PagPlayerView", "onAnimationEnd:==> pagPath  ${pagPath} ")
                pagAnimListener?.onAnimationEnd()
            }

            override fun onAnimationCancel(view: PAGView?) {
                Log.d("PagPlayerView", "onAnimationCancel:==> pagPath  ${pagPath} ")
                pagAnimListener?.onAnimationCancel()
            }

            override fun onAnimationRepeat(view: PAGView?) {
                Log.d("PagPlayerView", "onAnimationRepeat:==> pagPath  ${pagPath} ")
                pagAnimListener?.onAnimationRepeat()
            }

            override fun onAnimationUpdate(view: PAGView?) {

            }
        })
        return mPagView!!
    }

    fun createView(context: Context, pagPath: ByteArray?): PAGView {
        eglSetup()
        mPagView = PAGView(context, eglContext)
        if (composition != null) {
            mPagView?.composition = composition
        } else {
            val pagFile = PAGFile.Load(pagPath)
            pagCreateListener?.onCreate(pagFile)
            mPagView?.composition = pagFile
        }
        mPagView?.layoutParams = RelativeLayout.LayoutParams(
            ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT
        )
        mPagView?.setRepeatCount(repeatCount)
        mPagView?.addPAGFlushListener { }
        if (factory != 0L) {
            VideoDecoder.RegisterSoftwareDecoderFactory(factory)
            VideoDecoder.SetMaxHardwareDecoderCount(maxHardwareDecoderCount)
        }
        mPagView?.addListener(object : PAGView.PAGViewListener {
            override fun onAnimationStart(view: PAGView?) {
                pagAnimListener?.onAnimationStart()
            }

            override fun onAnimationEnd(view: PAGView?) {
                pagAnimListener?.onAnimationEnd()
            }

            override fun onAnimationCancel(view: PAGView?) {
                pagAnimListener?.onAnimationCancel()
            }

            override fun onAnimationRepeat(view: PAGView?) {
                pagAnimListener?.onAnimationRepeat()
            }

            override fun onAnimationUpdate(view: PAGView?) {

            }
        })
        return mPagView!!
    }


    fun setPagCreateListener(pagCreateListener: PagCreateListener): PagPlayerView {
        this.pagCreateListener = pagCreateListener
        return this
    }

    private fun eglSetup() {
        eglDisplay = EGL14.eglGetDisplay(EGL14.EGL_DEFAULT_DISPLAY)
        val version = IntArray(2)
        EGL14.eglInitialize(eglDisplay, version, 0, version, 1)
        EGL14.eglBindAPI(EGL14.EGL_OPENGL_ES_API)
        val attributeList = intArrayOf(
            EGL14.EGL_RENDERABLE_TYPE, EGL14.EGL_OPENGL_ES2_BIT,
            EGL14.EGL_RED_SIZE, 8,
            EGL14.EGL_GREEN_SIZE, 8,
            EGL14.EGL_BLUE_SIZE, 8,
            EGL14.EGL_ALPHA_SIZE, 8,
            EGL14.EGL_STENCIL_SIZE, 8,
            EGL14.EGL_SAMPLE_BUFFERS, 1,
            EGL14.EGL_SAMPLES, 4,
            EGL14.EGL_NONE
        )
        val configs = arrayOfNulls<EGLConfig>(1)
        val numConfigs = IntArray(1)
        EGL14.eglChooseConfig(
            eglDisplay, attributeList, 0, configs, 0,
            configs.size, numConfigs, 0
        )
        val attribute_list = intArrayOf(
            EGL14.EGL_CONTEXT_CLIENT_VERSION, 2,
            EGL14.EGL_NONE
        )
        eglContext = EGL14.eglCreateContext(
            eglDisplay, configs[0], EGL14.EGL_NO_CONTEXT,
            attribute_list, 0
        )
        val surfaceAttributes = intArrayOf(
            EGL14.EGL_WIDTH, 1,
            EGL14.EGL_HEIGHT, 1,
            EGL14.EGL_NONE
        )
        eglSurface = EGL14.eglCreatePbufferSurface(
            eglDisplay, configs[0],
            surfaceAttributes, 0
        )
    }

    private fun makePAGImage(context: Context, filePath: String): PAGImage? {
        if (eglContext == null || !EGL14.eglMakeCurrent(
                eglDisplay, eglSurface,
                eglSurface, eglContext
            )
        ) {
            return null
        }
        val assetManager = context.assets
        val stream: InputStream
        var bitmap: Bitmap? = null
        try {
            stream = assetManager.open(filePath)
            bitmap = BitmapFactory.decodeStream(stream)
        } catch (e: IOException) {
            // handle exception
        }
        if (bitmap == null) {
            return null
        }
        val mTexturesBitmap = intArrayOf(0)
        GLES20.glGenTextures(1, mTexturesBitmap, 0)
        textureID = mTexturesBitmap[0]
        GLES20.glBindTexture(GLES20.GL_TEXTURE_2D, textureID)
        GLES20.glTexParameterf(
            GLES20.GL_TEXTURE_2D,
            GLES20.GL_TEXTURE_MAG_FILTER, GLES20.GL_NEAREST.toFloat()
        )
        GLES20.glTexParameterf(
            GLES20.GL_TEXTURE_2D,
            GLES20.GL_TEXTURE_MIN_FILTER, GLES20.GL_NEAREST.toFloat()
        )
        GLES20.glTexParameterf(
            GLES20.GL_TEXTURE_2D,
            GLES20.GL_TEXTURE_WRAP_S, GLES20.GL_CLAMP_TO_EDGE.toFloat()
        )
        GLES20.glTexParameterf(
            GLES20.GL_TEXTURE_2D,
            GLES20.GL_TEXTURE_WRAP_T, GLES20.GL_CLAMP_TO_EDGE.toFloat()
        )
        GLUtils.texImage2D(GLES20.GL_TEXTURE_2D, 0, bitmap, 0)
        GLES20.glBindTexture(GLES20.GL_TEXTURE_2D, 0)
        return PAGImage.FromTexture(
            mTexturesBitmap[0], GLES20.GL_TEXTURE_2D,
            bitmap.width, bitmap.height
        )
    }

    fun release() {
        if (mPagView != null) {
            mPagView?.stop()
            mPagView?.freeCache()
            mPagView = null
        }
        if (eglContext != null && EGL14.eglMakeCurrent(
                eglDisplay,
                eglSurface,
                eglSurface,
                eglContext
            )
        ) {
            if (textureID > 0) {
                val textures = intArrayOf(textureID)
                GLES20.glDeleteTextures(1, textures, 0)
            }
            EGL14.eglMakeCurrent(
                eglDisplay,
                EGL14.EGL_NO_SURFACE,
                EGL14.EGL_NO_SURFACE,
                EGL14.EGL_NO_CONTEXT
            )
            EGL14.eglDestroySurface(eglDisplay, eglSurface)
            EGL14.eglDestroyContext(eglDisplay, eglContext)
            eglSurface = null
            eglContext = null
        }
    }

    fun setProgress(progress: Double): PagPlayerView  {
        if (mPagView != null) {
            mPagView?.progress = progress
        }
        return this
    }

    fun play() {
        if (mPagView != null) {
            mPagView?.play()
        }
    }

    fun stop() {
        if (mPagView != null) {
            mPagView?.stop()
        }
    }

    fun setRepeatCount(count: Int): PagPlayerView  {
        repeatCount = count
        if (mPagView != null) {
            mPagView?.setRepeatCount(count)
        }
        return this
    }

    fun setComposition(composition: PAGComposition?) : PagPlayerView {
        this.composition = composition
        if (mPagView != null) {
            mPagView?.composition = composition
        }
        return this
    }

    fun registerSoftwareDecoderFactory(factory: Long, maxHardwareDecoderCount: Int) {
        this.factory = factory
        this.maxHardwareDecoderCount = maxHardwareDecoderCount
        VideoDecoder.RegisterSoftwareDecoderFactory(factory)
        VideoDecoder.SetMaxHardwareDecoderCount(maxHardwareDecoderCount)
    }


}

**Comment by pichsy** [comment]
```

import org.libpag.PAGFile

fun interface PagCreateListener {
    fun onCreate(pagFile: PAGFile)
}

```

**Comment by pichsy** [comment]
经过多次测试这个bug非常的稳定，必现的。

基于这必现，目前还能过滤限制处理一下。哭死

**Comment by kevingpqi123** [comment]
你这里修改 PAGPlayerView 的原因是啥？这是私有接口
我跑了下 pag 的源码，回调方法的触发是正常。
为了提升对接的效率，反馈此类问题建议备注清楚背景，你这边修改了什么，问题复现的 demo 工程，问题提供的越完善解决的效率也会越高，我们没有时间帮大家一个个去构建场景复现
