### ISSUE TITLE
复杂列表下的展示，会ANR

### ISSUE THREAD

**Issue by peter100u** [Tencent/libpag#734]
## 场景
在复杂列表中展示，排行榜场景， 每个item中展示头像框，勋章，vip,等级等6个特效pag, 无法使用文档中说到的组合pag,只能一个一个
## 最新版本

libpag 4.1.43

## 手机型号

Android8 oppo

## 手机抓到的日志

{
    "APILevel": "27",
    "abi": "arm64",
    "brand": "OPPO",
    "crashTimestamp": "1676630110106",
    "data": {
        "backTrace": "#00 pc 0000000000016fb8  /vendor/lib64/libsrv_um.so\n#01 pc 000000000002b99c  /vendor/lib64/egl/libGLESv2_mtk.so\n#02 pc 0000000000011e3c  /vendor/lib64/libIMGegl.so (IMGeglCreateContext+4696)\n#03 pc 0000000000014c74  /system/lib64/libEGL.so (eglCreateContext+144)\n#04 pc 00000000000f3e30  /data/app/com.ohla.socialapps-LF49cG8iDJ3mLMyR8VT1gA\u003d\u003d/lib/arm64/libpag.so\n#05 pc 00000000000f3f2c  /data/app/com.ohla.socialapps-LF49cG8iDJ3mLMyR8VT1gA\u003d\u003d/lib/arm64/libpag.so\n#06 pc 00000000000f43ec  /data/app/com.ohla.socialapps-LF49cG8iDJ3mLMyR8VT1gA\u003d\u003d/lib/arm64/libpag.so\n#07 pc 00000000000df3a4  /data/app/com.ohla.socialapps-LF49cG8iDJ3mLMyR8VT1gA\u003d\u003d/lib/arm64/libpag.so\n#08 pc 0000000000084234  /data/app/com.ohla.socialapps-LF49cG8iDJ3mLMyR8VT1gA\u003d\u003d/lib/arm64/libpag.so\n#09 pc 0000000000091c08  /data/app/com.ohla.socialapps-LF49cG8iDJ3mLMyR8VT1gA\u003d\u003d/lib/arm64/libpag.so (_ZN3pag10PAGSurface4drawEPNS_11RenderCacheENSt6__ndk110shared_ptrINS_7GraphicEEEPNS_16BackendSemaphoreEb+72)\n#10 pc 00000000000900bc  /data/app/com.ohla.socialapps-LF49cG8iDJ3mLMyR8VT1gA\u003d\u003d/lib/arm64/libpag.so (_ZN3pag9PAGPlayer13flushInternalEPNS_16BackendSemaphoreE+208)\n#11 pc 000000000008ffb4  /data/app/com.ohla.socialapps-LF49cG8iDJ3mLMyR8VT1gA\u003d\u003d/lib/arm64/libpag.so (_ZN3pag9PAGPlayer5flushEv+88)\n#12 pc 00000000000e8b18  /data/app/com.ohla.socialapps-LF49cG8iDJ3mLMyR8VT1gA\u003d\u003d/lib/arm64/libpag.so (Java_org_libpag_PAGPlayer_flushAndFenceSync+204)\n#13 pc 0000000000158a88  /data/app/com.ohla.socialapps-LF49cG8iDJ3mLMyR8VT1gA\u003d\u003d/oat/arm64/base.odex\n",
        "code": "2 (SEGV_ACCERR)",
        "javaStackTrace": "at org.libpag.PAGPlayer.flushAndFenceSync(Native Method)\nat org.libpag.PAGPlayer.flush(PAGPlayer.java:163)\nat org.libpag.PAGView.flush(PAGView.java:814)\nat org.libpag.PAGView.updateView(PAGView.java:364)\nat org.libpag.PAGView.access$000(PAGView.java:32)\nat org.libpag.PAGView$PAGViewHandler.handleMessage(PAGView.java:170)\nat android.os.Handler.dispatchMessage(Handler.java:106)\nat android.os.Looper.loop(Looper.java:214)\nat android.os.HandlerThread.run(HandlerThread.java:65)\n"
    },
    "foreground": "no",
    "imVersion": "5.3.0.1",
    "isDebug": true,
    "model": "CPH1909",
    "packageName": "com.ohla.socialapps"
}

**Comment by peter100u** [comment]
目前看到的文档中只有这个PAGComposition可以作为解决思路，但是本身列表item太复杂了，用这个PAGComposition只有更复杂，而且还有国际化的问题

**Comment by kevingpqi123** [comment]
后续跟进这个问题
https://bbs.pag.art/thread/544

**Comment by peter100u** [comment]
> 后续跟进这个问题 https://bbs.pag.art/thread/544

说月底就优化版本呢， 还有4天，等吧
