### ISSUE TITLE
iOS播放pag文件比安卓占用内存、CPU较高

### ISSUE THREAD

**Issue by aimei111** [Tencent/libpag#759]
我们测试pag文件播放内存占用问题，使用同一个pag文件，iOS播放新增占用20M的内存、15%的CPU，安卓才占用6M的内存、3%的CPU，请问是pag播放对安卓支持比iOS更友好吗

**Comment by domchen** [comment]
一般不是这样的，拉胯的通常会是Android端。检查一下是否基于相同性能水平的机器在对比？另外确认一下iOS不是跑在模拟器，GPU渲染的方案不能通过模拟器测试性能，只能勉强运行。还有就是两端测试内存增量的方法是否一致？如果都检查无误还有疑问，可以到PAG的论坛 https://bbs.pag.art 上传一个可以运行demo，我们有同事会排查跟进。

**Comment by aimei111** [comment]
刚开始跑的确实是模拟器，后来用iPhone真机测试了一下，内存上涨和安卓确实差不多，但CPU不稳定，CPU占用比安卓会高出20%左右，而且我发现同样的动效iOS使用webp格式播放比用pag格式播放性能要好，用webp几乎不占cpu，内存占用也很低，但pag相对来说内存要多30M、cpu高出40%左右。
所以，在iPhone上是不是pag的兼容不如webp?

**Comment by domchen** [comment]
这里面有很多的因素影响以及使用方式的区别都会有不一样的结果。很多时候跟测试的素材也有关系。比如你的PAG文件里是不是用了BMP预合成？用了的话里面会带很多视频解码起来本来就比较耗性能。你拿一个纯矢量的素材再去对比一下，结果可能会差距非常巨大。你测试WebP如果能几乎不占CPU，那大概率是因为它把每帧都全部缓存了。目前PAG采用的是OpenGL的实时渲染的模式，理论上是比Web这种全缓存图片到内存的方式节省很多内存的。如果用在OpenGL渲染的环境中比如直播或者视频剪辑里就是这个预期的结果。但是用在UI动画上会有额外的劣势。就是OpenGL和原生的UI视图桥接需要一个双缓冲的基础内存开销，这个是OpenGL渲染的原理决定的，任何GPU渲染的方案都有这个基础内存开销。但是你说会占据很多的CPU这个应该跟渲染模式没什么关系，这个大概率是跟你的测试素材有关系。PAG支持非常多的原子能力，AE导出的素材，完全一样的效果，不同的制作方式可能会有天差地别的性能差距。如果占用很多的CPU，可以从官网的素材优化指南相关文档入手优化一下。优化一下可能可以看到立竿见影的效果。另外，前面提到的OpenGL渲染的问题，我们在4.2版本中将会发布一个新的针对UI场景优化的播放组件，不走之前的PAGView渲染，可以大幅提升UI动画这种使用场景的性能体验和内存占用情况。可以关注一下后续版本发布的信息。

**Comment by domchen** [comment]
下次遇到这类的性能优化问题，建议把相关的素材也传上来，像WebP这类的不管什么图片格式，性能基本都只跟分辨率有关，你可以理解它几乎是恒定的。但PAG格式的性能并不是一个恒定值，设计师的制作方式占据了很大的优化主动权，不同的制作方式有差距非常巨大的性能表现，所以脱离具体测试的素材谈性能对比并不具有任何意义。优化好的PAG素材可以低到几乎没有开销，比如纯矢量的，开销会远低于同尺寸的WebP，但如果设计师滥用BMP预合成，也可能远高于WebP，这也是我们提供了一系列性能检测工具，和优化指南文档的意义，辅助你高效地优化素材性能。跟WebP这种损耗固定的格式不一样，PAG提供了一个很灵活的优化空间，在素材层面你愿意花时间就可以优化的很好。考虑成本问题比如需要量产也可以降低要求。由业务根据成本灵活取舍。过往我们遇到的所有性能问题的咨询中，绝大部分其实都是素材优化方向的问题，但大家都会先入为主的从代码上找问题。其实不一定是代码或者使用方式上有什么问题。

**Comment by aimei111** [comment]
[▽ 抱抱_bmp(150-150).pag.zip](https://github.com/Tencent/libpag/files/10915828/_bmp.150-150.pag.zip)
[抱抱.webp.zip](https://github.com/Tencent/libpag/files/10915831/webp.zip)
我比较赞同你的说法，有些问题确实可能跟素材有关，所以我把测试的pag、webp格式的动图上传上来了，你可以测一下，另外其实我也用了官网上的pag格式的文件进行测试，结果是不同素材占用的CPU、内存不一样，cpu都基本在10%以上，因为我们的需求是想在首页、二级页面这种常规页面上的动图使用pag文件，意味着这些动图一直循环播放，所以如果动图多了，CPU、内存担心会吃不消，我们目前使用的webp格式对iOS的支持就比较友好，CPU、内存都比较低

**Comment by domchen** [comment]
你这个素材就是一个纯BMP的预合成，相当于一直在解码一个两倍尺寸的视频，从原理上比解码普通图片的开销就是更高的。但你的内容本身其实是矢量可以做出来的，让设计师改成按矢量方式导出性能就会好非常多，现在相当于人为选择了一个低性能的导出方式。你也可以换成 https://pag.art/file/pag_files.zip 这里面的纯矢量素材测试一下，换成纯矢量的会跟这里面的性能相似，比BMP预合成导出方式好非常多。并且相比WebP，虽然 BMP预合成已经很小了，但是纯矢量的还可以更小几个数量级。

另外你如果拿PAG只是用它的BMP预合成功能，其实意义并不是很大。举个例子我们还有个基于 WebP存储的BMP预合成导出方案，在AE插件里设置一下采用位图序列帧导出BMP预合成就行，导出的PAG文件里面就是一个WebP的序列帧，并非必须是视频。但是文件也会跟webp格式一样大。总体上PAG是支持了非常多原子能力的集合格式，用不同的能力会有不一样的性能，根据业务场景灵活选择就行。用 PAG 的优势更多的是提供性能上限更好的矢量导出方式，设计师花时间就可以优化到非常极致的效，以及运行时编辑替换内容的能力。如果这些都是你不需要的，用普通的序列帧方案也可以满足需求，在视频格式和WebP之间PAG也内置提供了选择。 

上面给的矢量文件都是真实业务场景中用在UI上用的动画，如果测试完连这些都不满足你的使用场景，可以等一下 PAG 4.2 的版本，那个版本里针对 UI 这种场景提供了新的播放组件，其实在 PAG 格式层面并没有什么变化，主要是上层的调用方式做了调整，我们提供了一个Decoder的模式，可以像 WebP 解码器一样逐帧解码 PAG 的文件到图片帧，然后剩下的原理WebP是怎么播放的，我们也怎么播放就行，甚至结合磁盘缓存可以做到更好的性能，内存和性能都会有大幅的优化。所以问题的焦点并不是在具体什么格式上在 iOS 上支持的更好，PAG 已经包含了你用到的所有格式类型，而是在调用方式的差异上。UI场景不太合适靠OpenGL实时渲染。这里面的桥接层额外开销太高了。在本来就是OpenGL的环境里就是零的额外开销，在那种场景下使用纯矢量的PAG可以达到远超你现在WebP的性能水平和低内存占用。在 UI 场景下会更加合适用新的Decoder组件模块播放。基于这个方式也可以继续使用所有运行时编辑的能力，文件还更小。

**Comment by aimei111** [comment]
感谢如此详细的解答，点赞。你发的zip压缩包内的pag文件和我之前测试在官网下载的pag文件应该是一样的，我也测试了这些文件的播放内存、CPU占用情况，结果和webp格式相比的话不占优势。
问下你们4.2版本大概什么时候会发布，到时我更新一下再看看。

**Comment by domchen** [comment]
大概两周左右会发布
