### ISSUE TITLE
invalid PAG header!

### ISSUE THREAD

**Issue by haledeng** [Tencent/libpag#761]
![image](https://user-images.githubusercontent.com/3880323/222418721-6ee523a2-f836-40f0-96eb-46329bbd75ea.png)

## Which Version of libpag are you using?

libpag 4.1.8

## What Platform are you on? 

iOS 12, Android 10, macOS 10.15.3, Chrome 87.0  ...

## PAG File

lite 中 demo 报错

**Comment by zenoslin** [comment]
@haledeng 我这边执行了一下并没有问题，请检查一下网络面板看测试素材 frames.pag 是否加载成功。
