### ISSUE TITLE
WebGL: context lost.

### ISSUE THREAD

**Issue by VaJoy** [Tencent/libpag#762]
Error occurs as PAG animation changes frequently:
<img width="1343" alt="444-1" src="https://user-images.githubusercontent.com/7721635/222615432-93958e1d-d30c-4aad-9758-43073f515e70.png">

And the page behaves like this:
<img width="361" alt="66674" src="https://user-images.githubusercontent.com/7721635/222616117-26aa8398-c985-4715-a316-69abea229cfc.png">

We are now using `libpag@4.1.40`, any way to fix this problem?

**Comment by zenoslin** [comment]
@VaJoy You should call the set composition if you want to render different PAG files in the same canvas. 
I saw your question in the PAG forum.
If you can provide a simple demo to review the error, it can help us find the error in your project faster.

**Comment by VaJoy** [comment]
Sad story that [setComposition](https://pag.art/apis/web/classes/pag_view.PAGView.html#setComposition) does not save my multi-animations-in-one-canvas  scenario.

Then I try to create new canvas dynamically for new animation after removing the old canvas which carrying old animation, it still resolves nothing, even I remove the context of old canvas manually :

```js
const destroyPagViewAndCanvas = () => {
  const canvasElement = pagView.canvasElement
  pagView?.freeCache()
  canvasElement.getContext('webgl')?.getExtension('WEBGL_lose_context')?.loseContext()
  pagView?.destroy()
  pagView = null

  // remove canvas from page
  canvasElement.width = 0
  canvasElement.height = 0
  containerElm.removeChild(canvasElement)
}
```

After that I use dynamic iframe to carry pag animation, but the GPU'll still crash after creating iframe certain times (Of course old iframe would be removed, there is always single iframe in my page).

Imo, once a context of WebGL has been created, it'll be extraordinary difficult to get rid of.

What's more, [There's tons of ways to accidentally keep references to HTML elements like the canvas as well as WebGL objects](http://www.javascriptkit.com/javatutors/closuresleak/index3.shtml), so maybe PAG should checkout the [destroy](https://github.com/Tencent/libpag/blob/05bfca12d5bb2b4addb22d35dda01397b1461055/web/src/pag-view.ts#L403) API that whether it does clean all the references to the WebGL's context.

Maybe I'll make a demo about this sometime and I'll open a new issue for this.
