### ISSUE TITLE
支持60FPS的BMP合成

### ISSUE THREAD

**Issue by howieY** [Tencent/libpag#770]
## ⭐ Suggestion

在业务开发中，BMP效果，仅支持30FPS的合成。对比60FPS的动画效果，30FPS不够流畅。希望支持60FPS的帧率调节。

## 💻 Use Cases
1. 在手机的充电动画中，使用pag做充电的动画展示，30FPS对比60FPS不够流畅。
2. 现在的手机可以达到120FPS，60FPS的动画，一般来说，已经是最低要求了。手机性能也都可以满足这样的高帧率。

**Comment by howieY** [comment]
非常感谢dom的回复，Pag在AE中的帧率配置限制在30FPS以内， 纯矢量达不到设计师想要呈现的视觉效果，现有的开源透明视频方案在半透明的处理上有黑边问题。 而pag在透明处理上做的很好。我的应用场景，只在高端旗舰手机上使用，性能可以支持。如何解除pag在AE配置中最大不能超过30FPS的限制呢？很需要PAG的支持， 再次感谢dom

**Comment by domchen** [comment]
我发的文档里就有，ae插件的选项面板里设置一下

**Comment by howieY** [comment]
![image](https://user-images.githubusercontent.com/7400547/224891744-389b93d8-9b4e-4865-bc8f-a32bb74529c1.png)
这里最大只能设置到30FPS。

**Comment by domchen** [comment]
这里的UI展示有问题，我们近期修复一下。 你现在可以通过手动修改配置文件来实现帧率上限的调整，导出插件的配置文件路径在这里：/Users/本地用户名/Library/Application Support/PAGExporter/Config.xml ，打开后找到这个区域：
`<bitmap> 
 		<sequence-suffix>_bmp</sequence-suffix> 
 		<sequence-type>3</sequence-type> 
 		<sequence-quality>100</sequence-quality> 
 		<keyframe-interval>60</keyframe-interval> 
 		<max-resolution>2000</max-resolution> 
 		<sequences> 
 			<sequence scale="1" framerate="30" /> 
 		</sequences> 
 	</bitmap> `
将里面的 <sequence scale="1" framerate="30" />  改为 <sequence scale="1" framerate="60" /> 即可。
