### ISSUE TITLE
低电量模式无法检查

### ISSUE THREAD

**Issue by ambar** [Tencent/libpag#776]
现状：
播放不了，没有异常信息抛出。

已知：
可以用软解，但它的性能太差，影响了页面上的其他交互。

期望：
能有异常信息，能方便用户做其他回退方案。

---
在 `PAGView.init()` 过程中实际上有异常发生，但没有抛出，导致 init 返回永远是 pending 状态：

https://github.com/Tencent/libpag/blob/e48160e25f096d12e309817828eb0920e3544fc9/web/src/core/video-reader.ts#L232

异常是 `Unhandled Promise Rejection: NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.`

**Comment by zenoslin** [comment]
PAGView.init() 中 Video 不能播放产生的 error 是能被 catch 到的。如果你那么还是有这个问题，可以提供一个简单的复现 demo 给到我们。
<img width="873" alt="Snipaste_2023-03-15_11-19-08" src="https://user-images.githubusercontent.com/24915910/225197147-0365ae40-f817-4e9d-b45e-c7b14c32ac8a.png">

**Comment by ambar** [comment]
@zenoslin  修改自官网的示例：https://codesandbox.io/s/pagview-init-bug-in-power-saving-mode-m0eyzw?file=/src/index.js (https://m0eyzw.csb.app/)

现在只有用全局 unhandledrejection 事件才能捕获，iOS 16 Mobile Safari。

**Comment by zenoslin** [comment]
@ambar 非常感谢反馈，已经找到问题所在，会在下个版本中修复这个问题。
