### ISSUE TITLE
lite 版本在 Chrome/Android 是模糊的

### ISSUE THREAD

**Issue by ambar** [Tencent/libpag#777]
- iOS 正常
- Chrome 切换为 canvas2d 也正常

**Comment by zenoslin** [comment]
在几个主流的 Chrome/Android 下测试过，并没有发现模糊的情况。能否提供一些更为详细的平台信息。

**Comment by ambar** [comment]
@zenoslin 
https://codesandbox.io/s/pag-lite-blurring-pwy8sh?file=/src/index.js

> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
> MacBook Pro (13-inch, M1, 2020)
