### ISSUE TITLE
关于获取 getTransformMatrix 后 ComputeTextureSize 方法的问题

### ISSUE THREAD

**Issue by hexleo** [Tencent/libpag#804]
获取 getTransformMatrix 后 ComputeTextureSize 的计算规则是什么？看到用到了第4行的值，按我的理解scale应该不用第4行的值才对，

而且我用组参数，利用这个公式计算的值不对

参数如下，实际纹理1920 * 1088，需要渲染的大小是 1920 * 1088
1.0,0.0,0.0,0.0,
0.0,-0.97282606,0.0,0.0,
0.0,0.0,1.0,0.0,
0.0,0.9755435,0.0,1.0

真心求教

<img width="554" alt="image" src="https://user-images.githubusercontent.com/3285051/226836982-5301c800-52c4-471a-884e-c9ace0c7e1e5.png">

**Comment by domchen** [comment]
这个规则是测试出来的。具体可以看一下 Android 这块的源码的计算过程。但通常情况下你正确的用法应该是直接把这个matrix传给opengl渲染。而不是去还原宽高。PAG里之所以要这样是因为我们内部的渲染框架没有传递额外matrix的能力。才要还原尺寸。

**Comment by domchen** [comment]
我看你的描述好像没有理解为什么会有这个SurfaceTexture的Matrix。首先你这句话就不对：「实际纹理1920 * 1088，需要渲染的大小是 1920 * 1088」，如果你的实际纹理等于你渲染的尺寸，是不可能返回一个非恒等矩阵给你的。返回这样的矩阵给你的意思就是实际纹理大于你预期的 1920*1088，解码器有一系列对齐的原因，并不会按照视频的实际画面尺寸给你返回纹理尺寸，会有一些边框。我们这个计算公式就是为了根据Matrix反推实际的纹理尺寸。

**Comment by domchen** [comment]
https://cs.android.com/android/platform/superproject/+/master:frameworks/native/libs/nativedisplay/surfacetexture/SurfaceTexture.cpp;l=275;drc=master;bpv=0;bpt=1
https://stackoverflow.com/questions/6023400/opengl-es-texture-coordinates-slightly-off
这有两个链接你可以参考了解下细节

**Comment by hexleo** [comment]
非常感谢解答
