### ISSUE TITLE
libpag-lite 播放特效只播放一遍的时候没有正确停留在最后一帧

### ISSUE THREAD

**Issue by backrunner** [Tencent/libpag#805]
特效没有正确停留在最后一帧，而是往后多跳了一帧，表现为特效播放一遍播放完停留在了开头第一帧。

## Which Version of libpag are you using?

libpag-lite 0.0.6

## What Platform are you on? 

Chrome latest

## Expected Behavior 
播放完成之后特效停留在最后一帧。

## Actual Behavior
由于video在特效一轮播放完之后还跟了特效开头的一些帧，在进行setProgress的时候往后多跳了一帧，导致特效如果repeatCount是1，播放完一轮会跳回开头。

## Related Code

web/lite/src/view/view.ts:L95

```ts
public setProgress(progress: number) {
    if (progress < 0 || progress > 1) throw new Error('progress must be between 0.0 and 1.0!');
    // 这里添加一个 -1，行为正常，应该是这里多跳了一帧，而且Math.round也有可能多跳帧？
    const currentFrame = Math.round(progress * this.videoSequence.frameCount) - 1;
    if (this.currentFrame !== currentFrame) {
      this.needSeek = true;
      this.currentFrame = currentFrame;
    }
  }
```

**Comment by zenoslin** [comment]
不太理解上面 -1 的建议，能否给出一个复现的 demo 让我理解到问题所在，我们再一起讨论？

**Comment by backrunner** [comment]
用最小demo暂时没办法复现了，考虑是其他的问题，先close...
