### ISSUE TITLE
setProgress: 偶现崩溃

### ISSUE THREAD

**Issue by O0Oy** [Tencent/libpag#817]
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/6157101/228143486-fafa2e37-8738-4968-852d-6df6b1127bbc.png">

<img width="744" alt="image" src="https://user-images.githubusercontent.com/6157101/228144121-61787ab8-fac0-4ecf-be3b-b7433aa13c02.png">

## Which Version of libpag are you using?

libpag 4.1.13

## Code Example
~~~
- (void)setPAGView:(PAGView *)pagView progress:(double)progress  {
    [pagView setProgress:progress];
    [pagView flush];
}
~~~

**Comment by domchen** [comment]
这个堆栈的内容看起来符号跟代码没匹配上，运行flush的时候是不可能执行到Layer的verify函数的。完全是不同 的阶段。你确认这个堆栈还原的准确吗？建议检查一下是不是用的符号包上传错了。

**Comment by domchen** [comment]
如果你确认符号没有问题，但是确实还原出了有问题的堆栈，那可能就是有野指针了，篡改了程序地址。这个就很随机了，可能来自内部也可能来自外部。如果是野指针造成的，报错地方并不是原因。看看本地是否有机会复现，即使只能概率复现也可以测试，在xcode里把如下配置勾选上，这样出现野指针的时候，会断点挂在真正出错的地方。看那个调用堆栈才有意义。
<img width="996" alt="image" src="https://user-images.githubusercontent.com/6849001/228520448-a00e4014-6569-4128-81a2-53bf10b52a14.png">

**Comment by O0Oy** [comment]
感谢，堆栈是bugly还原的，符号表应该没有问题。我尝试复现下野指针的问题。
