### ISSUE TITLE
iOS 16.4 Safari/微信 webview 无法播放

### ISSUE THREAD

**Issue by jiangyijie27** [Tencent/libpag#824]
你好，今天微信 webview / Safari 发现 pag 播不动。fork 了官网的 simple demo

https://wxa.wxs.qq.com/wxad-design/yijie/test-pag-yijie.html

我初步排查下来，是因为我昨天更新了 iOS 16.4。我试了另一台 iPhone 是可以的。

麻烦看下是否能尽快解决，业务页面已上线，感谢！

企业微信: yijiejiang

**Comment by backrunner** [comment]
+1，libpag-lite也遇到同样问题，目前有可用的workaround嘛？

**Comment by zenoslin** [comment]
@jiangyijie27 这个问题已经在 #831 PR中解决。
主要原因是因为 iOS 16.4 开始 Safari 支持 OffscreenCanvas (https://caniuse.com/?search=OffscreenCanvas) 但是 Safari 上 WebGL 相关的接口依然限制 OffscreenCanvas 的使用，从而出现了冲突。
处理方式，在 Safari 上统一不使用 OffscreenCanvas，后续看看 Safari 是否会处理这个冲突再考虑修改这部分逻辑。

**Comment by zenoslin** [comment]
@backrunner libpag-lite 并没有使用到 OffscreenCanvas，所以不可能出现本 issue 提到的问题。并且使用你提供的 Demo 链接在 Safari 16.4 运行正常并没有报错信息。如果是渲染效果有差异等其他问题，可以带上代码 Demo 到我们的论坛 https://pag.art/进行提问，两个工作日内都会有回复。

**Comment by zenoslin** [comment]
这个问题已经在libpag@ [4.2.41](https://www.npmjs.com/package/libpag/v/4.2.41) 中修复。

**Comment by vivid05** [comment]
> +1，libpag-lite也遇到同样问题，目前有可用的workaround嘛？
> 
> 附问题demo：https://vfiles.gtimg.cn/1680147641270.html

请问后续有解决吗

**Comment by vivid05** [comment]
> [@backrunner](https://github.com/backrunner) libpag-lite 并没有使用到 OffscreenCanvas，所以不可能出现本 issue 提到的问题。并且使用你提供的 Demo 链接在 Safari 16.4 运行正常并没有报错信息。如果是渲染效果有差异等其他问题，可以带上代码 Demo 到我们的论坛 https://pag.art/ 进行提问，两个工作日内都会有回复。

libpag-lite 同样在16版本，无法播放

**Comment by vivid05** [comment]
原因是：ios16版本，播放Vidoos是1的就不行
