### ISSUE TITLE
iOS podspec 使用废弃的字段

### ISSUE THREAD

**Issue by hao-feng** [Tencent/libpag#829]
iOS podspec中使用了'VALID_ARCHS'， 而这个字段已经废弃了

https://github.com/CocoaPods/Specs/blob/master/Specs/c/c/e/libpag/4.1.49/libpag.podspec.json#L35

**Comment by kevingpqi123** [comment]
感谢反馈，我们将在下个版本完善

**Comment by domchen** [comment]
最新版本已经移除

**Comment by rodger1017** [comment]
https://github.com/CocoaPods/Specs/blob/master/Specs/c/c/e/libpag/4.3.9/libpag.podspec.json

**Comment by rodger1017** [comment]
@kevingpqi123 最新版本仍然存在VALID_ARCHS
https://github.com/CocoaPods/Specs/blob/master/Specs/c/c/e/libpag/4.3.9/libpag.podspec.json
<img width="290" alt="image" src="https://github.com/Tencent/libpag/assets/3436556/f627beaa-3dda-4b44-940f-fd9fd549a981">
