### ISSUE TITLE
替换视频是不是有BUG？

### ISSUE THREAD

**Issue by a6965921** [Tencent/libpag#83]
我谷歌浏览器最新版本97   运行视频没动呀  用的官方demo  只是显示篮球
![image](https://user-images.githubusercontent.com/1198840/151968914-bea0743c-38bf-47ae-900f-b49b787a7016.png)
篮球没视频动画的

**Comment by domchen** [comment]
请根据 issue 模板提示把对应的 PAG 文件上传上来以及对应，提这样的一句话 bug 我们也没法帮助你解决。

**Comment by a6965921** [comment]
> 请根据 issue 模板提示把对应的 PAG 文件上传上来以及对应，提这样的一句话 bug 我们也没法帮助你解决。

解决了环境搭建问题
