### ISSUE TITLE
我视频素材导入进去导出来PAG没有视频了

### ISSUE THREAD

**Issue by a6965921** [Tencent/libpag#84]
我视频素材导入进去导出来PAG没有视频了  不用BMP与合成  只能用矢量图了码

**Comment by domchen** [comment]
参考这个文档进行导出：https://pag.io/docs/ae-bmp-guide.html 使用问题请到 Discussions 里提问，这里是记录 Bug 的地方，不是用来提问的。也可以加入QQ群提问。
