### ISSUE TITLE
手机设置中：开发者选项--关闭（窗口动画缩放/过渡动画缩放/动画程序时长缩放），结果PagView.play()动画播放不了？

### ISSUE THREAD

**Issue by smallKinson** [Tencent/libpag#848]
## Which Version of libpag are you using?

libpag 4.1.19

## What Platform are you on? 

Android 13

**Comment by domchen** [comment]
这个开发者选项的功能就是关闭动画的作用，如果还能播放才是不正常的吧。你的预期是什么呢？

**Comment by smallKinson** [comment]
预期：开发者选项--关闭动画后，PagView还能正常播放动画。
问题：sdk是否有api能控制实现？

**Comment by kevingpqi123** [comment]
感觉有个地方你理解错了，关闭动画用户就是不需要动画哈，这里关闭的不仅仅是 PAG 的 动画，而是所有依赖于 ValueAnimator 的动画
如果你一定需要动画，基于 PAGPlayer、PAGSuface、PAGComposition 自己封装吧，初始化一个定时器，然后控制每一帧的渲染
