### ISSUE TITLE
为什么我ae 弄的图片和文字 导出pag都是变成可编辑了 不是自己控制的码

### ISSUE THREAD

**Issue by a6965921** [Tencent/libpag#85]
为什么我ae 弄的图片和文字 导出pag都是变成可编辑了 不是自己控制的码 自己控制要不要编辑

**Comment by domchen** [comment]
PAG SDK没有去限制图层否可编辑，所有的文本和占位图图层都是可以编辑的。这个是业务侧做的逻辑。你可以跟设计师约定用什么图层名字的图层表示可编辑。图层名字可以带很多的附加信息。运行时可以通过 PAGLayer.layerName 获取对应图层名。使用问题请到 Discussions 里提问，这里是记录 Bug 的地方，不是用来提问的。也可以加入QQ群提问。

**Comment by h3clikejava** [comment]
那AE导出的时候设置面板中的“占位图层”-“素材格式”-“不替换”功能是干啥用的？
