### ISSUE TITLE
ios safari 播放报错Can't find variable: OffscreenCanvas

### ISSUE THREAD

**Issue by LinsRock** [Tencent/libpag#855]
ios safari在访问官方demo https://wxa.wxs.qq.com/wxad-design/yijie/test-pag-yijie.html  时报错 Unhandled Promise Rejection: ReferenceError: Can't find variable: OffscreenCanvas
目前已经遇到两个pag素材在ios safari中报这个错导致播放不了，官方有解决方案么？

![image](https://user-images.githubusercontent.com/24631029/231387672-869c390b-7804-4186-8bd6-61cede8cc497.png)

## Which Version of libpag are you using?

libpag 4.1.8

## What Platform are you on? 

iOS 16.0 (20A357)

**Comment by domchen** [comment]
你好，这个是已知问题，我们在这个issue里跟进：https://github.com/Tencent/libpag/issues/824 下个版本会修复。

**Comment by zenoslin** [comment]
这个问题已经在libpag@ [4.2.41](https://www.npmjs.com/package/libpag/v/4.2.41) 中修复。

**Comment by LinsRock** [comment]
> 

我们现在用的就是4.2.41, web端的，还是有问题

**Comment by zenoslin** [comment]
@LinsRock 我在iPhone11 iOS 16.4 Safari 和 iMac Safari 16.4 上都验证了你上述链接  https://wxa.wxs.qq.com/wxad-design/yijie/test-pag-yijie.html 是正常播放的。能否提供你出现问题的机器信息？

**Comment by LinsRock** [comment]
@zenoslin 设备：iPhone14 iOS 16.0 Safari

**Comment by LinsRock** [comment]
@zenoslin 目前测试的测试机对这个demo展示都有这个问题，还有问题的设备：
iPhone7p iOS 14.4 Safari
报错都是一样  ReferenceError: Can't find variable: OffscreenCanvas

**Comment by zenoslin** [comment]
@LinsRock 非常感谢反馈，已在 #860 中修复，可以升级到 libpag@4.2.56 验证

**Comment by LinsRock** [comment]
> 

@zenoslin libpag@4.2.56还没发布么
![image](https://user-images.githubusercontent.com/24631029/231653974-142c4f7b-c876-4fad-a051-616f899a9430.png)

**Comment by LinsRock** [comment]
> @LinsRock 非常感谢反馈，已在 #860 中修复，可以升级到 libpag@4.2.56 验证

@zenoslin 根据修改记录我修改源码后patch，是不会报Can't find variable: OffscreenCanvas了，iPhone14 iOS 16.0 Safari也正常播放了，但iPhone7p iOS 14.4 Safari播放同一个源时报 ReferenceError: Can't find variable: ImageBitmap
![image](https://user-images.githubusercontent.com/24631029/231657254-85aa0ef6-e17e-4b12-acdc-3acd804f90fb.png)

**Comment by LinsRock** [comment]
@zenoslin 看ImageBitmap从safari15才开始支持 https://caniuse.com/?search=ImageBitmap，建议使用ImageBitmap时判断当前是否存在，目前这样修改后播放正常了

![image](https://user-images.githubusercontent.com/24631029/231658521-2a8b3361-e206-475f-b754-fb894fd5edb8.png)

**Comment by zenoslin** [comment]
非常感谢你的反馈，OffscreenCanvas和ImageBitmap的类型检查问题是在4.2重构代码中引入的。在 #861 中已经把所有全局类的判断加上了防空报错，已经发布到beta tag上libpag@4.2.59
<img width="790" alt="image" src="https://user-images.githubusercontent.com/24915910/231684856-48f0c644-5694-4ef1-9211-31e03c69a211.png">

**Comment by songxiaoliang** [comment]
@Explorer-Carbon 我也遇到同样的问题了, 在4.2.41版本, Can't find variable: ImageBitmap  和 Can't find variable: OffscreenCanvas 这两个错误都遇到了, 请问你解决了吗?

**Comment by zhalice2011** [comment]
> libpag@4.2.59在iPhone7p iOS 14.4 Safari依旧存在报 ReferenceError: Can't find variable: ImageBitmap 的问题，我在 [#861](https://github.com/Tencent/libpag/pull/861) 中注意到方法releaseNativeImage中的ImageBitmap前没有添加globalThis。

感谢您的反馈, 此问题已在 https://github.com/Tencent/libpag/pull/884 中修复, 并且在libpag@4.2.64版本发布https://cdn.jsdelivr.net/npm/libpag@4.2.64/lib/libpag.min.js
