### ISSUE TITLE
4.2.20渲染出来的动画会显示不全

### ISSUE THREAD

**Issue by 1079107009** [Tencent/libpag#856]
## Which Version of libpag are you using?

libpag 4.2.20

## What Platform are you on? 

Android 11

## Expected Behavior 
这是我用4.1.49版本加载出来的动画，在线预览也是没有问题。
![image](https://user-images.githubusercontent.com/24666023/231401587-523999d3-fcd3-418c-9aef-611c2cddc7ee.png)

## Actual Behavior
![image](https://user-images.githubusercontent.com/24666023/231400322-6fddc0a5-254f-4bcb-ac8f-1a1a94599923.png)

**Comment by 1079107009** [comment]
pag文件地址：https://igpicture-test.oss-cn-beijing.aliyuncs.com/test2.pag

**Comment by domchen** [comment]
可以跟新到 4.2.55 版本试一下。

**Comment by XuanXiaoSa** [comment]
还是不行，反而问题更多了，都重影了，你们能好好自测一下不

**Comment by kevingpqi123** [comment]
我在 Android、iOS 和 Web 预览三个地方都测试过，都是渲染 OK，请问你这边的复现场景

**Comment by 1079107009** [comment]
更新到4.2.55已经好了
