### ISSUE TITLE
类名冲突, 想通过重新编译来解决, 请教一下官方的输出 XCFramework 的命令

### ISSUE THREAD

**Issue by moonclock** [Tencent/libpag#859]
## Question

因为 PAGPlayer 与第三方广告库类名冲突, 导致 PAGPlayer 功能不可用, 想通过修改文件名, 重新编译来解决, 请教一下官方的输出 XCFramework 的命令,  以便跟官方XCFramework保持一致, 谢谢

**Comment by kevingpqi123** [comment]
这些内容都是通用的，可以看下这篇文章：https://www.jianshu.com/p/b2e438bc4ac0

**Comment by moonclock** [comment]
感谢回复, 先暂时用 framework 代替, 辛苦啦

**Comment by moonclock** [comment]
感谢回复, 先暂时用 framework 代替, 辛苦啦
