### ISSUE TITLE
关于setRepeatCount

### ISSUE THREAD

**Issue by huannan** [Tencent/libpag#867]
## 问题

```
/**
 * Sets the number of times the animation will repeat. The default is 1, which means the animation
 * will play only once. 0 means the animation will play infinity times.
 */
public void setRepeatCount(int value) {
    if (value < 0) {
        value = 0;
    }
    animator.setRepeatCount(value - 1);
}
```

setRepeatCount这个API为什么要设计成跟Android的不一样？RepeatCount是重复播放的次数，目前的设计是不重复需要传1，理解起来有点奇怪甚至有点误导人。应该设置成0就是不重复播放。

**Comment by domchen** [comment]
并不是所有的平台对 repeatCount 的理解都是一致的，现在几种动效方案包括 PAG，Lottie 和 SVGA 在内都是在复刻当年 Flash 的工作流到移动端，所以一开始设计 API 的时候多少都会受到 Flash 的影响, Adobe 对 repeatCount 的理解一直都是直白的播放次数的意思：https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/utils/Timer.html#repeatCount  。1 就是播放一次，0 或负数就是无限播放。可能这样设计也是为了避免还需要再指定一个无穷大的常量数字来实现无限循环，因为各个平台对无穷大的数字定义也不一样，没有统一的值。不然你只是一个比较大的数字，但并不是真的无限循环。不管最开始的原因是什么，但现在 API 都要保持向后兼容性，也已经无法改了。不然其他已经使用的业务都会出问题。
