### ISSUE TITLE
android手机web端,chrome浏览器UC浏览器，微信浏览器等大尺寸不显示

### ISSUE THREAD

**Issue by fengcheche** [Tencent/libpag#87]
#### 问题

>1、 当一个pag本身的size>900x1700整个动画就不会加载出来，换成小尺寸（600左右x1500）就显示出来。2、而且在web端的渲染像看PPT一样的，很卡很慢不流畅。

#### 重现

> [就用的一个很600K的pag文件，就2个text和2个img，pag本身尺寸1080x1920，这个尺寸web端不会显示出来，换成更小的尺寸700x1500左右又显示出来了]
> PAG 素材可以在压缩之后，随这个 Bug 上传。

#### 环境

libpag 版本：libpag-ios（v3.2.4.37），libpag-android（v3.2.5.1），PAGViewer（2.1.33 beta）  
设备：红米note 9 5G  android-10，可以加我qq421160896联系

#### Demo（可选）

> 请给一个 Demo 项目，我们可以运行并重现这个问题。

#### 其他（可选）

> 如果还有其他信息可以帮助我们定位问题，请添加其他内容。

**Comment by zenoslin** [comment]
移动端Web开发中，会因为 devicePixelRatio 影响图像渲染。
PAG 代码中已经对 devicePixelRatio 的渲染清晰度做了处理，所以在设置 canvas 尺寸的时候，请不要使用过大的尺寸，当底层 GPU 渲染过大尺寸图像时，会出现无法预测的显示异常，这在 Web 的代码层是没有报错提示的。
所以，我们添加了一条警告逻辑，当 size * devicePixelRatio 大于2560的时候，会提示实际渲染尺寸大于2560，在某些低性能的平台可能会出现渲染异常。

**Comment by sangenan** [comment]
@zenoslin   "GPU 渲染过大尺寸图像时，会出现无法预测的显示异常"  这个在其他平台如Linux上也会这样么？
