### ISSUE TITLE
pag prepare anr

### ISSUE THREAD

**Issue by gmfzxl** [Tencent/libpag#878]
"main" prio=5 tid=1 Native
  | group="main" sCount=1 ucsCount=0 flags=1 obj=0x71e6d720 self=0xb400007752dff380
  | sysTid=27752 nice=-10 cgrp=top-app sched=0/0 handle=0x79234224f8
  | state=S schedstat=( 5090864385 276313226 21895 ) utm=329 stm=180 core=7 HZ=100
  | stack=0x7fc7b30000-0x7fc7b32000 stackSize=8188KB
  | held mutexes=
  native: #00 pc 000000000004eb70  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+32) (BuildId: fad1c6a9cfd9d04f64cd99336e69b21b)
  native: #01 pc 0000000000053558  /apex/com.android.runtime/lib64/bionic/libc.so (__futex_wait_ex(void volatile*, bool, int, bool, timespec const*)+148) (BuildId: fad1c6a9cfd9d04f64cd99336e69b21b)
  native: #02 pc 00000000000bb9ec  /apex/com.android.runtime/lib64/bionic/libc.so (NonPI::MutexLockWithTimeout(pthread_mutex_internal_t*, bool, timespec const*)+352) (BuildId: fad1c6a9cfd9d04f64cd99336e69b21b)
  native: #03 pc 00000000000bb6f0  /apex/com.android.runtime/lib64/bionic/libc.so (pthread_mutex_lock+224) (BuildId: fad1c6a9cfd9d04f64cd99336e69b21b)
  native: #04 pc 00000000001ede08  /product/app/nio-voice-assistant/nio-voice-assistant.apk (offset 2dac000) (???) (BuildId: f146fe8b3b6c2757bad9728e552192423def7c56)
  native: #05 pc 000000000007c6d8  /product/app/nio-voice-assistant/nio-voice-assistant.apk (offset 2dac000) (???) (BuildId: f146fe8b3b6c2757bad9728e552192423def7c56)
  native: #06 pc 00000000000d7178  /product/app/nio-voice-assistant/nio-voice-assistant.apk (offset 2dac000) (Java_org_libpag_PAGPlayer_prepare+68) (BuildId: f146fe8b3b6c2757bad9728e552192423def7c56)
  native: #07 pc 000000000021a354  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+148) (BuildId: db93c9d47713bf7f6b81fc06e934ddb0)
  native: #08 pc 000000000020a2b0  /apex/com.android.art/lib64/libart.so (nterp_helper+4016) (BuildId: db93c9d47713bf7f6b81fc06e934ddb0)
  native: #09 pc 000000000029bf64  /product/app/nio-voice-assistant/nio-voice-assistant.apk (org.libpag.PAGView.f+4)
  native: #10 pc 000000000020a254  /apex/com.android.art/lib64/libart
## Which Version of libpag are you using?

libpag 4.1.8

## What Platform are you on? 

iOS 12, Android 10, macOS 10.15.3, Chrome 87.0  ...

**Comment by kevingpqi123** [comment]
There is no valid information because they are all system stacks.
It would be better to provide complete stack information and usage methods.
