### ISSUE TITLE
文档是否写错了？

### ISSUE THREAD

**Issue by wardenlzr** [Tencent/libpag#889]
## Question

为了实现跨平台及保持各平台端的渲染一致性，PAG 的主体渲染是在 C++ 层，而不是依赖于平台侧的渲染接口。同时 PAG 是纯 GPU 渲染的方案，任何一个 GPU 渲染的方案都会有一个初始的屏幕缓冲区开销，如果测试的时候是全屏的，每个像素 都需要占用 4 字节的内存，加上双缓冲整体还要乘以 2，已经占用了几十 M 内存了。这个本身不是 PAG 动效占用的内存， 而是任何 GPU 渲染方案的基本占用。如果一个页面中含有多个 PAGView，其内存占用和 CPU 占用就会大一些。

最后一句话是否写错了，是GPU占用就会大一些。

**Comment by kevingpqi123** [comment]
没有问题，每一个 PAGView 需要一个纯 GPU 渲染的环境，需要一个初始的屏幕缓冲区开销，不是不占内存，任何 GPU 渲染都需要占用内存

**Comment by wardenlzr** [comment]
不好意思表达不够清晰；内存占用和 GPU 占用就会大一些。

**Comment by domchen** [comment]
移动端内存和GPU显存是都计入内存，物里上是同一个硬件。是不是这里理解有问题？

**Comment by wardenlzr** [comment]
感谢大佬回复； 
我理解播放动画的时候，CPU的工作是不是只需要把这些即将要显示的数据处理号然后交给GPU去渲染就可以了？不知道这个理解有没有问题；

**Comment by domchen** [comment]
你理解的内存和显存会有区分一般是桌面端的概念，在移动端都是计入内存，物理上移动端的显卡也是用的内存，没有独立的显存。所以我们在移动端一般不会特别说GPU显存的概念，都统一叫内存。xcode也只有内存一个指标。申请的纹理在xcode也都以内存占用呈现。移动端这样设计才实现了更好的性能优化，才会有 HardwareBuffer 这类提交纹理也不需要拷贝一次到 GPU 的共享内存对象。本来也就是这样的设计才是合理的，桌面是因为历史原因 GPU 和 CPU 一直被设计成了分开的模块。

**Comment by wardenlzr** [comment]
明白了，感谢感谢
