### ISSUE TITLE
java.lang.UnsatisfiedLinkError: No implementation found for void org.libpag.PAGPlayer.nativeInit() (tried 

### ISSUE THREAD

**Issue by wardenlzr** [Tencent/libpag#896]
## Question

你们提供的工程可以正常运行，我自己新建的工程，报如下错误，请问是什么原因
 Caused by: java.lang.UnsatisfiedLinkError: No implementation found for void org.libpag.PAGPlayer.nativeInit() (tried Java_org_libpag_PAGPlayer_nativeInit and Java_org_libpag_PAGPlayer_nativeInit__)
        at org.libpag.PAGPlayer.nativeInit(Native Method)
        at org.libpag.PAGPlayer.<clinit>(SourceFile:3)
        at org.libpag.PAGView.k(SourceFile:4)
        at org.libpag.PAGView.<init>(SourceFile:1004)

所有代码如下：
APP的guild.gradle下：
    implementation 'com.tencent.tav:libpag-enterprise:latest.release'
    implementation 'androidx.exifinterface:exifinterface:1.3.3'

然后再Activity 一个按钮的onclick 里面：
        final PAGView pagView = new PAGView(this);
        pagView.setLayoutParams(new RelativeLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT));
        ((ViewGroup) binding.getRoot()).addView(pagView);

        PAGFile pagFile1 = PAGFile.Load(getAssets(), "xue.pag");
        pagView.setComposition(pagFile1);
        pagView.setRepeatCount(0);
        pagView.play();

我在你们demo中也没有找到什么初始化的方法，请问下这个是哪里还缺点什么吗

**Comment by domchen** [comment]
这个报错是因为so没找到或者架构不对。你检查一下是不是严格按照接入文档里的步骤集成的：https://github.com/Tencent/libpag/wiki/mobile-sdk-guide  ，如果你拆开了aar，自己做so的下发，要自己负责loadlibrary，是直接用aar集成的，就检查一下是不是下载的架构不对。以及自己工程里的abifilter相关的参数。

**Comment by scsfwgy** [comment]
@domchen 
线上只有三个用户遇到这个问题：
Model ：mainline (QD4A.200805.003)   Archs：arm64-v8a
Model ： Nexus 5X (OSM1.180201.031)    Archs：x86

```
UnsatisfiedLinkError
No implementation found for void org.libpag.PAGPlayer.nativeInit() (tried Java_org_libpag_PAGPlayer_nativeInit and Java_org_libpag_PAGPlayer_nativeInit__)

org.libpag.PAGPlayer in nativeInit
System
org.libpag.PAGPlayer in <clinit> at line 3
System
org.libpag.PAGView in k at line 3
System
org.libpag.PAGView in <init> at line 20
System
com.lbank.android.business.main.fragment.SplashNavigationFragment$initByTemplateFragment$1$3 in newView at line 64
System
com.lbank.lib_base.utils.view.viewpager.CommonPagerAdapter in instantiateItem at line 32
System
androidx.viewpager.widget.ViewPager in addNewItem at line 1012
System
androidx.viewpager.widget.ViewPager in populate at line 1158
System
androidx.viewpager.widget.ViewPager in populate at line 1092
System
androidx.viewpager.widget.ViewPager in onMeasure at line 1622
System
android.view.View in measure at line 24530

```

**Comment by scsfwgy** [comment]
![image](https://github.com/Tencent/libpag/assets/16045179/16bd7c28-c822-4041-aa09-0c0db8763e26)
<img width="1022" alt="image" src="https://github.com/Tencent/libpag/assets/16045179/05244ca1-f469-44a9-b139-38c9e68bdd3e">

**Comment by PJYGit** [comment]
我这里也遇到了这个问题，在插件化下发时，android 5.x系统上，有概率复现这个问题，报错
dlopen failed: library "libffavc.so" not found

**Comment by scsfwgy** [comment]
该问题算是解决了，全部出现在谷歌商店渠道上，配置以下属性即可。仅供参考

android {

 bundle {
       //这一块
        abi {
            enableSplit = false
        }
    }
}

**Comment by qingyunhuohuo** [comment]
@scsfwgy hello，请问一下你遇到这个问题时使用的 pag 是什么版本的？
