### ISSUE TITLE
多个图层使用同一张图替换会引起crash

### ISSUE THREAD

**Issue by ICECHN** [Tencent/libpag#909]
## Question
pag版本：4.2.55
平台：android
现象：一个pag文件，有三个层可以替换图片；
情况一：用同一张图同时替换三个层，有时正常显示，有时出现so异常，概率约30%；
情况二：用不同的图替换三个层，可以正常显示；

请问这种情况怎么处理？
<img width="911" alt="image" src="https://user-images.githubusercontent.com/11832023/236479977-83fcfcb1-dbb0-454d-b229-d85ac3d76823.png">

**Comment by kevingpqi123** [comment]
1、我这边使用含有 5 个占位图的 PAG 文件渲染播放，用一张图片替换 5 个占位图，运行 20 次没有发现异常，如果你这边有可以复现的 demo ，建议附上 demo 工程；
2、如果有 crash 堆栈信息，我们的每个版本都提供有 obj 文件，可以基于对应的 obj 文件还原出堆栈信息，提供还原后的堆栈信息，没有还原过的 crash 堆栈啥也看不到，没有价值
