### ISSUE TITLE
iOS libpag 使用libpag开屏动画，第一次安装系统弹权限弹窗导致开屏动画不播放

### ISSUE THREAD

**Issue by tianjackyang** [Tencent/libpag#914]
## Which Version of libpag are you using?

libpag 4.2.55

## What Platform are you on? 

iOS 16.12

**Comment by tianjackyang** [comment]
iOS libpag 使用libpag开屏动画，第一次安装系统弹权限弹窗导致开屏动画不播放

**Comment by kevingpqi123** [comment]
这个不是什么问题吧，大部分的 APP 刚启动的时候都会弹出需要网络请求的权限弹框，仅仅是应用安装的首次，如果允许了网络请求，不会再弹出

**Comment by tianjackyang** [comment]
第一次安装播放启动动画播放不了， 后面就可以正常播放了，没解决这个问题你们就关闭了

**Comment by tianjackyang** [comment]
都说了 第一次用户安装，然后有授权弹窗导致pag动画播放动画没有显示，处于卡死状态， 后面启动就可以正常播放了，就app安装第一次有问题

**Comment by ninjalogxio** [comment]
> 

他说的不是弹出弹出权限框的问题；
而是 权限框 弹出之后，PAG 动画不会播放；

**Comment by ninjalogxio** [comment]
> 这个不是什么问题吧，大部分的 APP 刚启动的时候都会弹出需要网络请求的权限弹框，仅仅是应用安装的首次，如果允许了网络权限，不会再弹出

说的不是弹不弹框的问题，而是弹框之后 PAG 动画不会播放。。。

**Comment by xiaopengLOVEcode** [comment]
还是没解决呀 我刚接入这个框架就碰到了

**Comment by xiaopengLOVEcode** [comment]
本地的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Dom Chen ***@***.***&gt;
发送时间: 2023年11月9日 17:20
收件人: Tencent/libpag ***@***.***&gt;
抄送: xiaoxiaopeng ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Tencent/libpag] iOS libpag 使用libpag开屏动画，第一次安装系统弹权限弹窗导致开屏动画不播放 (Issue #914)





 
你的PAG文件是加载的还是内置的？如果是网络加载的，第一次弹窗没有网络权限加载不了PAG文件，肯定是播放不了的。

**Comment by domchen** [comment]
目前这个体验对大部分用户都可以接受，影响面有限，也缺少复现的环境排查，如果你自己调试定位出具体的问题，欢迎提交修复的PR。

**Comment by xiaopengLOVEcode** [comment]
好的 感谢回复



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Dom Chen ***@***.***&gt;
发送时间: 2023年11月10日 11:46
收件人: Tencent/libpag ***@***.***&gt;
抄送: xiaoxiaopeng ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Tencent/libpag] iOS libpag 使用libpag开屏动画，第一次安装系统弹权限弹窗导致开屏动画不播放 (Issue #914)





 
目前这个体验对大部分用户都可以接受，影响面有限，也缺少复现的环境排查，如果你自己调试定位出具体的问题，欢迎提交修复的PR。
