### ISSUE TITLE
是否可以使用http协议的pag文件路径，目前看设置path为http协议路径是无效的

### ISSUE THREAD

**Issue by YJTruevoice** [Tencent/libpag#917]

**Comment by kevingpqi123** [comment]
预计 PAG 4.3 版本支持，大概在 6月 初

**Comment by YJTruevoice** [comment]
期待啊

**Comment by YJTruevoice** [comment]
> 预计 PAG 4.3 版本支持，大概在 6 月初

请问用下面的这个方式传进去一个byte数组只能第一次播放有效，下次播放就无效了
public static [PAGFile](https://pag.art/apis/android/org/libpag/PAGFile.html) Load(byte[] bytes)
