### ISSUE TITLE
PagView flush crash

### ISSUE THREAD

**Issue by iceAnson** [Tencent/libpag#919]
## Which Version of libpag are you using?

libpag 4.1.19

## What Platform are you on? 

Android 11,

## Actual Behavior

 上线后有一些少量的pagview闪退。

## crash log：

java.util.ArrayList.get(ArrayList.java:437)
2
android.animation.ValueAnimator.animateValue(ValueAnimator.java:1566)
3
android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:692)
4
android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:655)
5
org.libpag.PAGView.flush(SourceFile:8)
6
org.libpag.PAGView.updateView(SourceFile:2)
7
org.libpag.PAGView.access$000(SourceFile:1)
8
org.libpag.PAGView$PAGViewHandler.handleMessage(SourceFile:16)
9
android.os.Handler.dispatchMessage(Handler.java:106)
10
android.os.Looper.loop(Looper.java:257)
11
android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by kevingpqi123** [comment]
麻烦升级至最新版本，如果使用 4.1 版本升级至 4.1.49, 4.2 版本升级至 4.2.77

**Comment by iceAnson** [comment]
我的版本就是[4.1.49]
