### ISSUE TITLE
 PAGInit fail! Please check .wasm file path valid.  

### ISSUE THREAD

**Issue by vaynevayne** [Tencent/libpag#922]
```jsx
<body>
    <!-- <slot /> -->
    <canvas class="canvas" id="pag"></canvas>
    <script src="https://cdn.jsdelivr.net/npm/libpag@latest/lib/libpag.min.js"
    ></script>
    <script>
 window.onload = async () => {
    // Initialize pag webassembly module.
    const PAG = await window.libpag.PAGInit();
    // Fetch pag file data.
    const buffer = await fetch('/assets/交互.pag').then((response) => response.arrayBuffer());
    // Load the PAGFile from data.
    const pagFile = await PAG.PAGFile.load(buffer);
    // Set canvas size from the PAGFile size.
    const canvas = document.getElementById('pag');
    canvas.width = pagFile.width();
    canvas.height = pagFile.height();
    // Create PAGView.
    const pagView = await PAG.PAGView.init(pagFile, canvas);
    // Play PAGView.
    await pagView.play();
  };
    </script>
    <script>
      import "@scripts/dialog.js"
    </script>
  </body>
```

<img width="886" alt="image" src="https://github.com/Tencent/libpag/assets/124666577/20a01a00-bcb5-48ef-bcf5-0692aa84f57b">

**Comment by zhalice2011** [comment]
Hello, please review the document regarding the loading of wasm files: https://github.com/Tencent/libpag/wiki/use-web-sdk

How to fix it? 

1. download wasm file from https://cdn.jsdelivr.net/npm/libpag@latest/lib/ or npm module
2. put wasm file in some position you want
3. use locateFile to load wasm file

check vite config demo: https://github.com/libpag/pag-web/tree/main/vue/vue3

**Comment by vaynevayne** [comment]
可以提供一个 在线 demo?

**Comment by zhalice2011** [comment]
Please drag your PAG file to pag official website: [pag.art](https://pag.art/player.html)

And you can check the source code: view-source:https://pag.art/player.html

or download vite config demo and run it in your local: https://github.com/libpag/pag-web

**Comment by hejun311** [comment]
同样的报错

**Comment by zhalice2011** [comment]
> 同样的报错

你好, 请提供可以复现的demo, 下面是正常运行的示例

在线示例: https://pagtest.zhalice.com/pages/simple.html

源代码: view-source:https://pagtest.zhalice.com/pages/simple.html

**Comment by guoguo1991** [comment]
你好 请问问题是如何解决的呢。在使用pag过程中有同样的报错。

**Comment by kindesa** [comment]
我也是，PC端没有问题，手机端的chrome浏览器有报这个
