### ISSUE TITLE
iOS libpag 使用libpag开屏动画，第一次安装系统弹权限弹窗导致开屏动画不播放  都说了 第一次用户安装，然后有授权弹窗导致pag动画播放动画没有显示，处于卡死状态， 后面启动就可以正常播放了，就app安装第一次有问题

### ISSUE THREAD

**Issue by tianjackyang** [Tencent/libpag#923]
## Which Version of libpag are you using?

libpag 4.2.55

## What Platform are you on? 

iOS 16.12

**Comment by kevingpqi123** [comment]
这里需要网络连接，不是正常的吗，你在 APP Store 新下载一个 APP，很多 APP 不都是会弹出网络、以及其它的弹出框吗

**Comment by kevingpqi123** [comment]
描述问题为正常现象，提问者没有再提供进一步的信息，关闭该 issue

**Comment by WELONG** [comment]
![Image](https://github.com/user-attachments/assets/7cf08d0d-9989-4a4a-a158-682b3c5b13cb)

空工程只引入libPag,运行就会请求网络。应该是埋点触发的
