### ISSUE TITLE
求助：iOS版本手动集成发生崩溃

### ISSUE THREAD

**Issue by aolan** [Tencent/libpag#928]
## Question

问题描述：采用 pods 集成，可以运行正常。但是手动引入 libpag.xcframework，运行到 模拟器立马崩溃。

![SoZTMhiBHo](https://github.com/Tencent/libpag/assets/6744261/21e141ae-08f6-4608-b30a-36306e12d23d)

## 环境：
MacOS版本：13.2.1 (22D68) M1芯片
Xcode版本：Version 14.3 (14E222b)
模拟器版本：iPhone 14 Pro - iOS16.4
libpag版本：4.2.75

## 我的引入步骤

1、创建一个空 Swift（storyboard） 工程
2、然后参照 https://www.simpleswiftguide.com/how-to-add-xcframework-to-xcode-project/ 文档，将 libPag.xcframework 导入到工程
3、Build Settings - Excluded Architectures 添加 Any iOS Simulator SDK，然后value设置为 arm64
4、Build Settings - User Defined 添加 VALID_ARCHS，value为 arm64 armv7 x86_64

至于为什么有第三步和第四步，原因是参照 podspec 文件中的 配置

![image](https://github.com/Tencent/libpag/assets/6744261/59df68c4-8c72-494f-85e0-48aec30fd168)

然后开始运行，依然崩溃。

**Comment by aolan** [comment]
使用的 libpag 版本应该是最新的

**Comment by hcsaaron** [comment]
我也遇到同样的问题，使用的是libpag_4.0.5.79（其他版本存在其他问题尚未解决），解决了运行崩溃的问题：
选中Target - Build Phases - Link Binary With Libraries - 添加 libc++.tbd、VideoToolbox.framework、CoreMedia.framework。
（建议iOS接入中补充说明手动继承需要添加的依赖，最好有手动集成的demo，否则你们的开发人员发现不了手动集成存在的问题。）

目前手动集成，在模拟器中无法显示包含视频帧的pag文件，我已在论坛中提问，PAG开发人员回复将会解决该问题，但目前仍未解决。https://bbs.pag.art/thread/846?postId=3270

**Comment by quentinfasquel** [comment]
I also encounter this issue, it's not working on simulator, regardless of adding the linked binaries.
Explicitly adding system libraries in 'Link Binary With Libraries' is usually not necessary anymore..

**Comment by quentinfasquel** [comment]
@domchen I was wondering, I tried building for macOS, but somehow it built a static lib for x86_64 although I'm on an Apple Silicon

**Comment by kevingpqi123** [comment]
> 我也遇到同样的问题，使用的是libpag_4.0.5.79，解决了运行崩溃的问题： 选中Target - Build Phases - Link Binary With Libraries - 添加 libc++.tbd、VideoToolbox.framework、CoreMedia.framework。
> 
> （建议iOS接入文档中补充说明手动继承需要添加的依赖，最好有手动集成的demo，否则你们的开发人员发现不了手动集成存在的问题。）
> 
> 目前手动集成libpag_4.0.5.79，在模拟器中无法显示包含视频帧的pag文件，我已在论坛中提问，PAG开发人员回复将会解决该问题，但目前仍未解决。https://bbs.pag.art/thread/846?postId=3270

可以升级至 4.2.88，该问题已修复

**Comment by kevingpqi123** [comment]
从 4.2.100 版本开始，该问题已修复

**Comment by domchen** [comment]
> I also encountered this issue, it wasn't working on simulator... regardless of adding the linked binaries. The DYLD crash is related to loading the dynamic library. Therefore I changed and use the arm64_armv7_simulator_static.zip instead of the xcframework provided in the iOS example repo. Now it works.
> 
> Also know that explicitly adding system libraries in 'Link Binary With Libraries' is usually not necessary anymore when you are in Apple platform environment, they get resolved automatically. They still might be needed on C/C++ projects but not in the current situation.

@quentinfasquel It is an issue related to CodeSign, which has been fixed in 4.2.100.
