### ISSUE TITLE
Android NullPointException

### ISSUE THREAD

**Issue by Disguiser99** [Tencent/libpag#938]
Attempt to invoke virtual method 'java.lang.String java.io.File.getPath()' on a null object reference

org.libpag.PAGDiskCache.java.lang.String GetCacheDir()(PAGDiskCache.java:3)

## Which Version of libpag are you using?

libpag 4.2.77

## What Platform are you on? 
Android 8、9

**Comment by h3r3x3** [comment]
升级到81版本测试下

**Comment by Disguiser99** [comment]
还是有相同问题

**Comment by Disguiser99** [comment]
> 还是有相同问题

**Comment by Disguiser99** [comment]
> 升级到81版本测试下

还是有相同问题

**Comment by Disguiser99** [comment]
> 升级到81版本测试下

还是有相同问题

**Comment by domchen** [comment]
建议提供一个可以复现的demo上传上来，报错的内容连调用堆栈都没有，看不出来是哪行出现的问题。

**Comment by Disguiser99** [comment]
> 

<img width="714" alt="image" src="https://github.com/Tencent/libpag/assets/41035123/535efea1-10dd-4345-9ac0-daf4a72bdcf4">
