### ISSUE TITLE
Android Anr

### ISSUE THREAD

**Issue by zenglihao** [Tencent/libpag#943]
## Which Version of libpag are you using?

Android libpag 4.2.41

## What Platform are you on? 

Android 12 Moto G Stylus 5G (2022)

Anr log

pag-renderer (native):tid=99 systid=14452 
#00 pc 0x4dab0 libc.so (syscall + 32) (BuildId: 37a328c30fb8c595fc3ebc7c80be6ac1)
#01 pc 0x3a9ae4 libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*) + 140) (BuildId: 12e00d030bcfeb51f978c01791e0cd24)
#02 pc 0x5f8160 libart.so (art::JNI<false>::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list) + 2660) (BuildId: 12e00d030bcfeb51f978c01791e0cd24)
#03 pc 0xb1bf8 libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...) + 124) (BuildId: 2f03e6e9b1ecd88536475951bc5ac90a)
#04 pc 0x118a48 libandroid_runtime.so (android::JNISurfaceTextureContext::onFrameAvailable(android::BufferItem const&) + 68) (BuildId: 2f03e6e9b1ecd88536475951bc5ac90a)
#05 pc 0xaa95c libgui.so (android::ConsumerBase::onFrameAvailable(android::BufferItem const&) + 176) (BuildId: 0fc7f7562fde3adb718e68c7fef2d5fc)
#06 pc 0x7d230 libgui.so (android::BufferQueue::ProxyConsumerListener::onFrameAvailable(android::BufferItem const&) + 108) (BuildId: 0fc7f7562fde3adb718e68c7fef2d5fc)
#07 pc 0x880b4 libgui.so (android::BufferQueueProducer::queueBuffer(int, android::IGraphicBufferProducer::QueueBufferInput const&, android::IGraphicBufferProducer::QueueBufferOutput*) + 2132) (BuildId: 0fc7f7562fde3adb718e68c7fef2d5fc)
#08 pc 0xe4e00 libgui.so (android::Surface::queueBuffer(ANativeWindowBuffer*, int) + 616) (BuildId: 0fc7f7562fde3adb718e68c7fef2d5fc)
#09 pc 0xe2ec eglSubDriverAndroid.so (BuildId: 49a8fd7ad6797b897c3dad4075a3b5a1)
#10 pc 0x2a09d8 libGLESv2_adreno.so (!!!0000!10f39af3d5dda97a64124dee6a3783!f3aa497c33! + 240) (BuildId: b173b449aacc10ec99a5568d468655cd)
#11 pc 0x287c80 libGLESv2_adreno.so (!!!0000!04fe7c7713a0660472688458ecb7a2!f3aa497c33! + 144) (BuildId: b173b449aacc10ec99a5568d468655cd)
#12 pc 0x202d0 libEGL.so (android::eglSwapBuffersWithDamageKHRImpl(void*, void*, int*, int) + 508) (BuildId: a9f49fa8a4660e1dd25dd0442985b100)
#13 pc 0x1ca14 libEGL.so (eglSwapBuffers + 56) (BuildId: a9f49fa8a4660e1dd25dd0442985b100)
#14 pc 0xe7058 split_config.arm64_v8a.apk + 12136448 (BuildId: 9aa24e0464a90d9a993bf80c168e4d1c0f6bed76)
#15 pc 0x8d744 split_config.arm64_v8a.apk (pag::PAGSurface::draw(pag::RenderCache*, std::__ndk1::shared_ptr<pag::Graphic>, pag::BackendSemaphore*, bool) + 532) (BuildId: 9aa24e0464a90d9a993bf80c168e4d1c0f6bed76)
#16 pc 0x8b9d4 split_config.arm64_v8a.apk (pag::PAGPlayer::flushInternal(pag::BackendSemaphore*) + 208) (BuildId: 9aa24e0464a90d9a993bf80c168e4d1c0f6bed76)
#17 pc 0x8b8cc split_config.arm64_v8a.apk (pag::PAGPlayer::flush() + 88) (BuildId: 9aa24e0464a90d9a993bf80c168e4d1c0f6bed76)
#18 pc 0xde498 split_config.arm64_v8a.apk (Java_org_libpag_PAGPlayer_flushAndFenceSync + 204) (BuildId: 9aa24e0464a90d9a993bf80c168e4d1c0f6bed76)
       at org.libpag.PAGPlayer.flushAndFenceSync(Native method)
       at org.libpag.PAGPlayer.flush(unavailable:1)
       at org.libpag.PAGView.flush(unavailable:2)
       at org.libpag.PAGView.updateView(unavailable:12)
       at org.libpag.PAGView.access$000(unavailable)
       at org.libpag.PAGView$PAGViewHandler.handleMessage(unavailable:94)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loopOnce(Looper.java:238)
       at android.os.Looper.loop(Looper.java:357)
       at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by kevingpqi123** [comment]
Report the issue in one place,  there's no need to repeat the problem.
https://bbs.pag.art/thread/956
