### ISSUE TITLE
anr出现很多 libpag_GPUDecoder_release_decoder线程

### ISSUE THREAD

**Issue by gmfzxl** [Tencent/libpag#963]
为什么会有这么多libpag_GPUDecoder_release_decoder线程 源码不应该限制最多10个吗
	行 1723: "libpag_GPUDecoder_release_decoder" daemon prio=5 tid=56 Native
	行 1739: "libpag_GPUDecoder_release_decoder" daemon prio=5 tid=84 Native
	行 1755: "libpag_GPUDecoder_release_decoder" daemon prio=5 tid=85 Native
	行 1771: "libpag_GPUDecoder_release_decoder" daemon prio=5 tid=86 Native
	行 1787: "libpag_GPUDecoder_release_decoder" daemon prio=5 tid=87 Native
	行 1812: "libpag_GPUDecoder_release_decoder" daemon prio=5 tid=88 Native
	行 1837: "libpag_GPUDecoder_release_decoder" daemon prio=5 tid=89 Native
	行 1862: "libpag_GPUDecoder_release_decoder" daemon prio=5 tid=91 Native
	行 1887: "libpag_GPUDecoder_release_decoder" daemon prio=5 tid=92 Native
	行 1912: "libpag_GPUDecoder_release_decoder" daemon prio=5 tid=72 Native
	行 1937: "libpag_GPUDecoder_release_decoder" daemon prio=5 tid=83 Native
	行 1962: "libpag_GPUDecoder_release_decoder" daemon prio=5 tid=94 Native

Subject: executing service com.skyui.voiceassistant/.SpeechService

--- CriticalEventLog ---
capacity: 20
timestamp_ms: 1685513584301
window_ms: 300000

Subject: executing service com.skyui.voiceassistant/.SpeechService

--- CriticalEventLog ---
capacity: 20
timestamp_ms: 1685513584301
window_ms: 300000

----- pid 7448 at 2023-05-31 14:13:07.470459259+0800 -----
Cmd line: com.skyui.voiceassistant
Build fingerprint: 'DFQ/N2301/davinci:13/TKQ1.230227.001/33.1684149871:userdebug/release-keys'
ABI: 'arm64'
Build type: optimized
Zygote loaded classes=20929 post zygote classes=4624
Dumping registered class loaders
#0 dalvik.system.PathClassLoader: [], parent #1
#1 java.lang.BootClassLoader: [], no parent
#2 dalvik.system.PathClassLoader: [/system/framework/tcmclient.jar], parent #0
#3 dalvik.system.PathClassLoader: [], parent #0
#4 dalvik.system.PathClassLoader: [/data/app/~~7TwB-onW8IFlupF9E0r_tA==/com.skyui.voiceassistant-EnZdc_OkOxVJsUAt88wqzA==/base.apk!classes18.dex:/data/app/~~7TwB-onW8IFlupF9E0r_tA==/com.skyui.voiceassistant-EnZdc_OkOxVJsUAt88wqzA==/base.apk!classes6.dex:/data/app/~~7TwB-onW8IFlupF9E0r_tA==/com.skyui.voiceassistant-EnZdc_OkOxVJsUAt88wqzA==/base.apk!classes2.dex:/data/app/~~7TwB-onW8IFlupF9E0r_tA==/com.skyui.voiceassistant-EnZdc_OkOxVJsUAt88wqzA==/base.apk!classes13.dex:/data/app/~~7TwB-onW8IFlupF9E0r_tA==/com.skyui.voiceassistant-EnZdc_OkOxVJsUAt88wqzA==/base.apk!classes8.dex:/data/app/~~7TwB-onW8IFlupF9E0r_tA==/com.skyui.voiceassistant-EnZdc_OkOxVJsUAt88wqzA==/base.apk!classes21.dex:/data/app/~~7TwB-onW8IFlupF9E0r_tA==/com.skyui.voiceassistant-EnZdc_OkOxVJsUAt88wqzA==/base.apk!classes7.dex:/data/app/~~7TwB-onW8IFlupF9E0r_tA==/com.skyui.voiceassistant-EnZdc_OkOxVJsUAt88wqzA==/base.apk!classes20.dex:/data/app/~~7TwB-onW8IFlupF9E0r_tA==/com.skyui.voiceassistant-EnZdc_OkOxVJsUAt88wqzA==/base.apk!classes25.dex-transformed:/data/app/~~7TwB-onW8IFlupF9E0r_tA==/com.skyui.voiceassistant-EnZdc_OkOxVJsUAt88wqzA==/base.apk!classes17.dex:/data/app/~~7TwB-onW8IFlupF9E0r_tA==/com.skyui.voiceassistant-EnZdc_OkOxVJsUAt88wqzA==/base.apk!classes3.dex:/data/app/~~7TwB-onW8IFlupF9E0r_tA==/com.skyui.voiceassistant-EnZdc_OkOxVJsUAt88wqzA==/base.apk!classes9.dex:/

**Comment by domchen** [comment]
源码限制的是同时存在的最多线程数量。你看看你的日志是不是不同的时间段搜集的信息，不是同时存在的线程数量。不过这块逻辑在 #969 也已经优化了，现在是会复用C++侧渲染引擎已有的线程池，不再由平台端自己创建。

**Comment by gmfzxl** [comment]
是同时存在的 另外 你这个969的修改 什么时候可以出出来正式包 我们可以测试这个问题
