### ISSUE TITLE
华为EMUI10.0.0无法播放动画

### ISSUE THREAD

**Issue by DuranShelf** [Tencent/libpag#970]
## Which Version of libpag are you using?

libpag 4.1.49  试了一下, 最新的 4.2.88 也是一样的, 没法播放动画

## What Platform are you on? 

Android 华为 EMUI10.0.0

**Comment by kevingpqi123** [comment]
Please report the issue to one place only.
There is no need to ask the same question in multiple places.
https://bbs.pag.art/thread/1102
