### ISSUE TITLE
使用PAGConvertor素材迁移工具将mp4转pag，转换后的pag右边多出空隙

### ISSUE THREAD

**Issue by LazyIonEs** [Tencent/libpag#976]
## Question
使用PAGConvertor   ##[素材迁移工具将mp4转pag，转换后的pag右边多出空隙，原视频比例为1:1，转换后的pag比例虽然也是1:1，但是视频的最右边有明显的空隙
![image](https://github.com/Tencent/libpag/assets/86482436/b9c1823f-0078-496c-b951-16957e547f38)

![image](https://github.com/Tencent/libpag/assets/86482436/bf391b66-a1d5-434c-9553-5aa50b7a91e0)

**Comment by Hparty** [comment]
如果方便请发一下能复现的素材，也请描述下素材格式和分辨率大小

**Comment by LazyIonEs** [comment]
https://github.com/Tencent/libpag/assets/86482436/927d8589-31e9-4295-a062-a2320a0ea01b

mp4,h.264,分辨率820x820

**Comment by Hparty** [comment]
已复现，感谢提供素材。可以先通过AE中PAG插件导出成素材文件，后续我们会修复这个bug

**Comment by Hparty** [comment]
fix，可以用附件进行测试。是由于ffmpeg在相同大小下转换带有绿边的yuv数据到rgba时会进行裁剪导致的，现在已经修复。
[pagConvertor.zip](https://github.com/Tencent/libpag/files/11754890/pagConvertor.zip)
