### ISSUE TITLE
3D Rotations

### ISSUE THREAD

**Issue by quentinfasquel** [Tencent/libpag#984]
## ⭐ Suggestion

I found that Lottie can handle natively 3D rotations from After Effects. Would it be possible to handle natively every feature that Lottie already supports ?

## 💻 Use Cases

I have a 3D rotations on layers that need their image to be replaced.

**Comment by kevingpqi123** [comment]
This is the AE feature support list for PAG, https://pag.art/feature.html#ae 
The enterprise version of PAG supports 3D vector rendering and placeholder image replacement.
