### ISSUE TITLE
web端在不支持WebAssembly的低端手机上如何使用？

### ISSUE THREAD

**Issue by lkl0304** [Tencent/libpag#985]
## Question

我们准备在web端接入pag，但目前还是存在一些用户设备不支持WebAssembly，请问有啥方法能兼容运行下呢？

**Comment by zhalice2011** [comment]
Hello, in addition to WebAssembly, WebGL support is also required. On mobile devices, the support for WebAssembly and WebGL is basically consistent.(https://caniuse.com/).

If the PAG you create is a single video sequence frame, you can use the lite version to be compatible with lower version machines: https://github.com/Tencent/libpag/blob/main/web/lite/README.md.
